//! Application core — orchestrates crypto, store, and net.
//!
//! This is the main entry point for client applications. It wires together the
//! three foundation crates:
//!
//! - **crypto** — X3DH session initiation, Double Ratchet encrypt/decrypt
//! - **store** — local SQLCipher database for sessions, prekeys, messages
//! - **net** — HTTP client for the homeserver API
//!
//! `app-core` owns the high-level flows: account creation, sending a DM,
//! receiving messages, and prekey management. Mobile apps (via UniFFI) and
//! integration tests call into this crate.
//!
//! # FFI design
//!
//! UniFFI-exported methods are synchronous. They block on an internal tokio
//! runtime. Mobile callers should invoke them from a background
//! thread/dispatch queue, never from the main/UI thread.

pub mod connection;
pub mod error;
pub mod groups;
pub mod messaging;
pub mod plc;
pub mod profile;
pub mod recovery;

pub mod proto {
    // Generated by prost from proto/content.proto at build time (see build.rs)
    include!(concat!(env!("OUT_DIR"), "/actnet.rs"));

    /// Group-state plaintext message types (docs/03-groups.md §3.1). Lives
    /// here in `app-core` because the server never sees these — they're
    /// the contents of the encrypted state blob.
    pub mod groups {
        include!(concat!(env!("OUT_DIR"), "/actnet.groups.rs"));
    }
}

use std::path::Path;
use std::sync::Arc;

use base64::prelude::*;
use crypto::session::DeviceAddress;
use error::{AppError, AppErrorFfi};
use net::types::{RegisterRequest, ReplaceDeviceRequest};
use proto::{content_message::Body, receipt_message, ContentMessage, ReceiptMessage, TextMessage};
use prost::Message as _;
use rand::TryRngCore as _;
use store::account::RegistrationInfo;
use tokio::sync::Mutex;
use types::{AccountId, DeviceId, Timestamp};

uniffi::setup_scaffolding!();

/// Shared tokio runtime for FFI blocking calls. Created once, lives forever.
pub(crate) fn ffi_runtime() -> &'static tokio::runtime::Runtime {
    static RT: std::sync::OnceLock<tokio::runtime::Runtime> = std::sync::OnceLock::new();
    RT.get_or_init(|| tokio::runtime::Runtime::new().expect("failed to create tokio runtime"))
}

/// Install a tracing subscriber that writes formatted log lines to stderr.
/// Idempotent — subsequent calls are no-ops. `filter` uses `RUST_LOG`
/// syntax (e.g. `"info"`, `"app_core=debug,net=debug"`); an invalid filter
/// falls back to `"info"`.
///
/// Xcode captures stderr from the running app into its debug console, so
/// after calling this from Swift on launch, Rust `tracing::*!` output
/// shows up alongside Swift `print()`.
#[uniffi::export]
pub fn init_logging(filter: String) {
    use tracing_subscriber::{fmt, EnvFilter};
    let env_filter = EnvFilter::try_new(&filter).unwrap_or_else(|_| EnvFilter::new("info"));
    let _ = fmt()
        .with_env_filter(env_filter)
        .with_writer(std::io::stderr)
        .with_ansi(false)
        .with_target(true)
        .try_init();
}

/// A Project available on the homeserver.
#[derive(uniffi::Record)]
pub struct ProjectInfoFfi {
    pub name: String,
    pub url: String,
    pub description: String,
}

/// A decrypted inbound message.
#[derive(uniffi::Record, Clone, Debug)]
pub struct DecryptedMessage {
    pub server_id: i64,
    pub sender_did: String,
    pub sender_device_id: u32,
    pub plaintext: Vec<u8>,
    /// Sender's sent_at timestamp (from envelope). None for legacy messages.
    pub sent_at_ms: Option<i64>,
    /// URL-safe-no-pad base64 of the group_id when this message arrived as a
    /// `proto::GroupMessage` body. `None` for plain DMs.
    pub group_id: Option<String>,
}

/// A message from local history (persisted in SQLCipher).
#[derive(uniffi::Record)]
pub struct StoredMessageFfi {
    pub id: String,
    pub conversation_id: String,
    pub sender_did: String,
    pub body: String,
    pub sent_at_ms: i64,
    pub edited_at_ms: Option<i64>,
    /// NULL = unread, Some = unix millis when marked read.
    pub read_at_ms: Option<i64>,
    /// 0 = sending, 1 = sent, 2 = delivered, 3 = read.
    pub delivery_status: u8,
}

/// A conversation summary used to build the chat list on startup: one row
/// per conversation that has at least one persisted message, with the most
/// recent message attached.
#[derive(uniffi::Record)]
pub struct ConversationSummaryFfi {
    pub conversation_id: String,
    pub last_message: StoredMessageFfi,
}

/// A delivery status update for an outgoing message (e.g. read receipt received).
#[derive(uniffi::Record, Clone, Debug)]
pub struct DeliveryStatusUpdate {
    pub conversation_id: String,
    pub sent_at_ms: i64,
    pub delivery_status: u8,
}

/// Result of `create_group`. `group_id` is URL-safe-no-pad base64;
/// `master_key` is the 32-byte zkgroup master key (caller stashes for
/// invite links).
#[derive(uniffi::Record, Debug, Clone)]
pub struct CreatedGroupFfi {
    pub group_id: String,
    pub master_key: Vec<u8>,
}

/// A member's row in a group, decrypted under the group key.
#[derive(uniffi::Record, Debug, Clone)]
pub struct GroupMemberFfi {
    pub did: String,
    /// URL-safe-no-pad base64 of the encrypted_member_id. Pass this verbatim
    /// to admin actions (remove_member, change_member_role, …).
    pub encrypted_member_id: String,
    /// 0 = Member, 1 = Admin.
    pub role: i16,
    pub joined_at_ms: i64,
}

/// A pending invite or approval entry. `timestamp_ms` carries either
/// `invited_at_ms` (for invites) or `requested_at_ms` (for approvals).
#[derive(uniffi::Record, Debug, Clone)]
pub struct GroupPendingFfi {
    pub encrypted_member_id: String,
    pub timestamp_ms: i64,
}

/// Snapshot of a group's decrypted state.
#[derive(uniffi::Record, Debug, Clone)]
pub struct GroupSummaryFfi {
    pub group_id: String,
    pub master_key: Vec<u8>,
    pub revision: i64,
    pub title: String,
    pub description: String,
    pub expiry_seconds: u32,
    pub members: Vec<GroupMemberFfi>,
    pub pending_invites: Vec<GroupPendingFfi>,
    pub pending_approvals: Vec<GroupPendingFfi>,
}

/// Outcome of `join_via_link`.
#[derive(uniffi::Enum, Debug, Clone, Copy)]
pub enum JoinResultFfi {
    /// Admitted directly into `member_credentials` (OpenLink policy).
    Member,
    /// Placed in `members_pending_approval` (RequestToJoin policy);
    /// admins must approve before the requester can act.
    Pending,
}

fn summary_to_ffi(s: groups::GroupSummary) -> GroupSummaryFfi {
    GroupSummaryFfi {
        group_id: s.group_id,
        master_key: s.master_key,
        revision: s.revision,
        title: s.title,
        description: s.description,
        expiry_seconds: s.expiry_seconds,
        members: s
            .members
            .into_iter()
            .map(|m| GroupMemberFfi {
                did: m.did,
                encrypted_member_id: m.encrypted_member_id,
                role: m.role,
                joined_at_ms: m.joined_at_ms,
            })
            .collect(),
        pending_invites: s
            .pending_invites
            .into_iter()
            .map(|p| GroupPendingFfi {
                encrypted_member_id: p.encrypted_member_id,
                timestamp_ms: p.timestamp_ms,
            })
            .collect(),
        pending_approvals: s
            .pending_approvals
            .into_iter()
            .map(|p| GroupPendingFfi {
                encrypted_member_id: p.encrypted_member_id,
                timestamp_ms: p.timestamp_ms,
            })
            .collect(),
    }
}

/// Minimal contact-list row backing the compose autocomplete and the People
/// list. `display_name` is the cached profile display name (empty if no
/// profile has been fetched yet — callers fall back to the DID).
#[derive(uniffi::Record, Debug, Clone)]
pub struct ContactRowFfi {
    pub did: String,
    pub display_name: String,
    pub is_curated: bool,
    pub last_interaction_at_ms: i64,
}

/// Public metadata for an account: display name and bot flag.
///
/// `display_name` is only populated for bot accounts. Human display names are
/// exchanged via encrypted profile bundles (client-to-client), never stored on
/// the server.
#[derive(uniffi::Record)]
pub struct AccountInfoFfi {
    pub did: String,
    pub display_name: Option<String>,
    pub is_bot: bool,
}

/// Liveness of the connection to the homeserver.
///
/// Owned by the `AppCore` background reconnect task; observed by UI via
/// `connection_state()` and `wait_for_connection_state_change()`.
#[derive(uniffi::Enum, Debug, Clone, PartialEq, Eq)]
pub enum ConnectionState {
    /// Initial state; reconnect task hasn't run yet.
    Disconnected,
    /// An attempt is in flight (handshake / lazy auth).
    Connecting,
    /// WebSocket is open. Steady state.
    Connected,
    /// Last attempt failed; backing off until `next_attempt_at_ms`.
    Reconnecting { next_attempt_at_ms: i64 },
}

/// A single event surfaced to the FFI from the background reconnect task.
/// Drained in batches by `next_events()`.
#[derive(uniffi::Enum, Debug, Clone)]
pub enum IncomingEvent {
    /// A decrypted content message.
    Message { msg: DecryptedMessage },
    /// A delivery status update from a read receipt.
    ReceiptUpdate { update: DeliveryStatusUpdate },
}

/// Admin-only events surfaced to a separate queue, drained by
/// `next_admin_events_async()`. NOT exported to UniFFI — mobile clients
/// never see these. Consumed exclusively by admin Projects (today: the
/// adminbot, via the napi binding).
///
/// Future variants (e.g. `ServerBuildEvent`) will land here so admin pushes
/// can grow without breaking the consumer-facing `IncomingEvent` enum.
#[derive(Debug, Clone)]
pub enum AdminEvent {
    /// A new account just registered on this homeserver. Only delivered to
    /// bot accounts whose authed DID matches the server's pinned
    /// `ADMINBOT_DID` — for any other session the channel stays empty.
    AccountJoined { did: String, joined_at_ms: i64 },
}

/// Implementation of `net::Signer` backed by the device's libsignal identity
/// key. Used by `net::Client` to perform challenge/response on demand
/// (initial auth + transparent 401 retry).
///
/// Stores the identity as serialized bytes and deserializes on each sign call.
/// Signing happens once per auth round (rare); the per-call deserialization
/// cost is negligible and avoids Clone constraints on `IdentityKeyPair`.
pub(crate) struct IdentitySigner {
    pub(crate) identity_bytes: Vec<u8>,
}

impl net::Signer for IdentitySigner {
    fn sign(&self, nonce: &[u8]) -> Result<Vec<u8>, String> {
        let identity = crypto::IdentityKeyPair::deserialize(&self.identity_bytes)
            .map_err(|e| format!("identity deserialize: {e}"))?;
        identity
            .private_key()
            .calculate_signature(nonce, &mut rand::rngs::OsRng.unwrap_err())
            .map(|s| s.into_vec())
            .map_err(|e| format!("signal signing error: {e}"))
    }
}

/// Build a `net::Client` for an authenticated session. Captures the identity
/// key in an `Arc<dyn Signer>` so the client can re-auth on 401 without
/// holding a reference to the store or identity locally.
pub(crate) fn build_authed_client(
    server_url: &str,
    did: String,
    device_id: u32,
    identity: &crypto::IdentityKeyPair,
    initial_token: Option<String>,
) -> net::Client {
    let signer: Arc<dyn net::Signer> = Arc::new(IdentitySigner {
        identity_bytes: identity.serialize(),
    });
    net::Client::new(server_url).with_signer(did, device_id, signer, initial_token)
}

/// The main client handle. Holds local state and a server connection.
///
/// Thread-safe: all mutable state is behind an async Mutex, and the object
/// is wrapped in Arc by UniFFI. Safe to call from multiple Swift/Kotlin threads.
///
/// Exported methods are blocking — call from a background thread.
///
/// Connection state lives here too: a background reconnect task (spawned by
/// the FFI constructors) owns the WebSocket lifecycle. UI observes state via
/// `connection_state` / `wait_for_connection_state_change` and reads
/// decrypted messages + receipt updates via `next_events`.
#[derive(uniffi::Object)]
pub struct AppCore {
    pub(crate) inner: Mutex<AppCoreInner>,
    /// Canonical connection-state observable. The reconnect task publishes;
    /// each waiter calls `state_tx.subscribe()` to get its own receiver.
    pub(crate) state_tx: tokio::sync::watch::Sender<ConnectionState>,
    /// Sender side of the events queue. The reconnect task pushes; FFI
    /// `next_events` drains via `event_rx`.
    pub(crate) event_tx: tokio::sync::mpsc::UnboundedSender<IncomingEvent>,
    /// Single-consumer event receiver. Wrapped in a tokio Mutex because
    /// `recv().await` is held across an await.
    pub(crate) event_rx: Mutex<tokio::sync::mpsc::UnboundedReceiver<IncomingEvent>>,
    /// Sender side of the admin-event queue. Parallel to `event_tx`; not
    /// FFI-exported. Drained via `next_admin_events_async`.
    pub(crate) admin_event_tx: tokio::sync::mpsc::UnboundedSender<AdminEvent>,
    /// Single-consumer admin-event receiver.
    pub(crate) admin_event_rx: Mutex<tokio::sync::mpsc::UnboundedReceiver<AdminEvent>>,
    /// Handle to the background reconnect task. Held so it doesn't get
    /// detached; the task self-exits when the last `Arc<AppCore>` drops.
    pub(crate) reconnect_task: std::sync::Mutex<Option<tokio::task::JoinHandle<()>>>,
    /// Live WebSocket connection, if any. Set by the reconnect loop on a
    /// successful connect and cleared when the receive loop exits.
    /// `send_dm` prefers the WS when present and falls back to HTTP `POST
    /// /v1/messages` otherwise.
    pub(crate) ws: std::sync::Mutex<Option<net::ws::WsConnection>>,
}

pub(crate) struct AppCoreInner {
    pub(crate) store: store::Store,
    pub(crate) client: net::Client,
    pub(crate) local_address: DeviceAddress,
    pub(crate) did: String,
    pub(crate) device_id: u32,
}

impl AppCore {
    /// Construct an `AppCore` with fresh state/event channels. Does **not**
    /// spawn the reconnect task — that requires an `Arc` and happens in
    /// `start_reconnect_task` after wrapping.
    fn build(inner: AppCoreInner) -> Self {
        let (state_tx, _) = tokio::sync::watch::channel(ConnectionState::Disconnected);
        let (event_tx, event_rx) = tokio::sync::mpsc::unbounded_channel();
        let (admin_event_tx, admin_event_rx) = tokio::sync::mpsc::unbounded_channel();
        Self {
            inner: Mutex::new(inner),
            state_tx,
            event_tx,
            event_rx: Mutex::new(event_rx),
            admin_event_tx,
            admin_event_rx: Mutex::new(admin_event_rx),
            reconnect_task: std::sync::Mutex::new(None),
            ws: std::sync::Mutex::new(None),
        }
    }

    /// Spawn the background reconnect task. Idempotent — second call is a no-op.
    /// Call after wrapping `AppCore` in `Arc` so the task can hold a `Weak`.
    ///
    /// The FFI constructors (`login`, `create_account`, etc.) call this
    /// automatically. Tests and the testbot must call it explicitly after
    /// wrapping in `Arc`.
    ///
    /// Why `spawn_blocking` + a dedicated current-thread runtime: libsignal
    /// futures are not `Send` (see CLAUDE.md), so we can't `tokio::spawn` an
    /// async task that touches the store. The blocking worker thread owns
    /// its own runtime and drives the loop locally.
    pub fn start_reconnect_task(self: &Arc<Self>) {
        let mut slot = self.reconnect_task.lock().unwrap();
        if slot.is_some() {
            return;
        }
        let weak = Arc::downgrade(self);
        let handle = ffi_runtime().spawn_blocking(move || {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("reconnect runtime build");
            rt.block_on(connection::reconnect_loop(weak));
        });
        *slot = Some(handle);
    }

    /// Publish a connection-state change. Uses `send_if_modified` so duplicate
    /// values don't wake waiters.
    pub(crate) fn publish_state(&self, new_state: ConnectionState) {
        self.state_tx.send_if_modified(|current| {
            if *current != new_state {
                *current = new_state.clone();
                true
            } else {
                false
            }
        });
    }
}

#[uniffi::export]
impl AppCore {
    /// Create a new account on the server.
    ///
    /// `prf_output` is the 32-byte WebAuthn PRF output from the just-completed
    /// passkey ceremony. The rotation key and the recovery-blob key are both
    /// derived from it via HKDF. Pass an empty vec for the no-passkey path
    /// (random rotation key, no recovery blob — identity is unrecoverable on
    /// device loss).
    ///
    /// `display_name` is the user's chosen display name. A profile key is
    /// generated, the name is encrypted under it, and the blob is uploaded
    /// atomically with registration. The profile key travels with outgoing
    /// messages so contacts can fetch and decrypt the blob.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn create_account(
        server_url: String,
        db_path: String,
        db_key: String,
        prf_output: Vec<u8>,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let prepared = PreparedAccountState::prepare(server_url, &prf_output, true)
            .map_err(AppErrorFfi::from)?;
        let inner = rt.block_on(Self::create_inner(prepared, store, Some(display_name), false, None))
            .map_err(AppErrorFfi::from)?;

        {
            let core = Arc::new(Self::build(inner));
            core.start_reconnect_task();
            Ok(core)
        }
    }

    /// Create a new bot account on the server.
    ///
    /// Bot accounts skip the PLC directory and receive a `did:local:...` DID
    /// assigned by the server. `display_name` is sent plaintext (server stores
    /// it directly for bot-name lookup); humans use [`Self::create_account`]
    /// instead, which encrypts the display name into a profile blob.
    ///
    /// No recovery blob is uploaded — bots are operator-managed and don't use
    /// the passkey recovery flow.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn create_bot_account(
        server_url: String,
        db_path: String,
        db_key: String,
        display_name: String,
        did_suffix: Option<String>,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let prepared = PreparedAccountState::prepare(server_url, &[], false)
            .map_err(AppErrorFfi::from)?;
        let inner = rt.block_on(Self::create_inner(prepared, store, Some(display_name), true, did_suffix))
            .map_err(AppErrorFfi::from)?;

        let core = Arc::new(Self::build(inner));
        core.start_reconnect_task();
        Ok(core)
    }

    /// Finalize account registration using a previously prepared identity.
    ///
    /// Use this when the signup flow needs the DID up front: do the passkey
    /// ceremony, call [`PreparedAccount::new`] with the PRF output to derive
    /// the DID, then call this to submit the PLC ops, encrypt the recovery
    /// blob (using the same passkey-derived key), and complete server
    /// registration.
    ///
    /// The `prepared` handle is consumed (its inner state is moved out); a
    /// second call with the same handle returns an error.
    #[uniffi::constructor]
    pub fn finalize_account(
        prepared: Arc<PreparedAccount>,
        db_path: String,
        db_key: String,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let state = prepared
            .state
            .blocking_lock()
            .take()
            .ok_or_else(|| AppError::Protocol("PreparedAccount already consumed".into()))
            .map_err(AppErrorFfi::from)?;

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let inner = rt.block_on(Self::create_inner(state, store, Some(display_name), false, None))
            .map_err(AppErrorFfi::from)?;

        {
            let core = Arc::new(Self::build(inner));
            core.start_reconnect_task();
            Ok(core)
        }
    }

    /// Recover an account from a passkey-protected recovery blob.
    ///
    /// 1. Downloads the encrypted blob from `server_url` keyed by `did`.
    /// 2. Decrypts with `recovery_key` (32-byte PRF-derived symmetric key).
    /// 3. Extracts the identity keypair, rotation key, and server list.
    /// 4. Generates a new `device_id`, fresh prekeys, and a fresh registration ID.
    /// 5. Signs a replacement payload with the rotation key and POSTs to
    ///    `/v1/devices/replace` on the primary server (first in the blob's
    ///    server list, falling back to `server_url`). The server revokes the
    ///    old device's sessions/prekeys and registers the new one, returning a
    ///    session token.
    /// 6. Opens a fresh local SQLCipher store at `db_path` and persists the
    ///    restored identity, rotation key, registration, and prekeys.
    /// 7. Returns an `AppCore` ready to send/receive messages.
    ///
    /// The recovered account keeps the original identity key, so contacts see
    /// no safety-number change.
    ///
    /// `display_name` is optional — pass an empty string to leave it unset
    /// (the user can update it from Settings later). The blob does not carry
    /// the original profile key, so a fresh profile key is generated.
    ///
    /// **Multi-server caveat:** if the blob lists more than one server, only
    /// the primary one is replaced. Replacing on the remaining servers is a TODO.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn recover_from_blob(
        server_url: String,
        did: String,
        prf_output: Vec<u8>,
        db_path: String,
        db_key: String,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();
        rt.block_on(async move {
            if prf_output.len() != 32 {
                return Err(AppError::Protocol("prf_output must be 32 bytes".into()));
            }
            // Derive both keys from the PRF: the rotation key (re-derived,
            // never on any server) and the blob-encryption key.
            let (rot_seed, blob_key) = recovery::derive_recovery_keys_from_prf(&prf_output);
            let (rotation_key_private, rotation_key_public) =
                recovery::derive_rotation_key_from_seed(&rot_seed);

            // Resolve the homeserver URL from PLC for did:plc: DIDs. The
            // caller-supplied `server_url` is used as a fallback for
            // did:local: bots (no PLC entry) and as a last resort if the PLC
            // lookup fails for transient reasons.
            let bootstrap_server = if did.starts_with("did:plc:") {
                match plc::resolve_homeserver_url(&did).await {
                    Ok(url) => url,
                    Err(e) => {
                        tracing::warn!(
                            "PLC resolution failed during recovery for {did}: {e}; \
                             falling back to caller-supplied server_url"
                        );
                        server_url.clone()
                    }
                }
            } else {
                server_url.clone()
            };

            // Download the blob and the current device list (one unauthenticated call).
            let bundle = net::Client::new(&bootstrap_server).get_recovery_blob(&did).await?;
            let plaintext = recovery::decrypt_recovery_blob(&bundle.blob, &blob_key)?;

            // Restore identity keypair.
            let identity_bytes = BASE64_STANDARD
                .decode(&plaintext.identity_keypair)
                .map_err(|_| AppError::Protocol("invalid base64 identity in blob".into()))?;
            let identity = crypto::IdentityKeyPair::deserialize(&identity_bytes)?;

            // Pick the server we'll talk to (and that AppCore will be bound to).
            // Prefer the blob's server list; if empty, reuse the bootstrap
            // server (PLC-resolved for did:plc:, caller-supplied otherwise).
            let primary_server = plaintext
                .servers
                .first()
                .cloned()
                .unwrap_or_else(|| bootstrap_server.clone());

            // Pick the existing device_id from the bundle and reuse it for
            // the new device so existing senders keep working. The server
            // deletes the old device row before inserting the new one, so
            // reusing the ID doesn't conflict with UNIQUE (account_id, device_id).
            //
            // `min()` is arbitrary here — we expect exactly one device today.
            // For multi-device, this is wrong: recovery means "I lost one
            // device" and shouldn't silently kill the others. Revisit to
            // either register a fresh device_id alongside the existing ones,
            // or prompt the user to pick which device to replace.
            let old_device_id: u32 = bundle
                .device_ids
                .iter()
                .copied()
                .min()
                .map(|d| d as u32)
                .unwrap_or(1);
            let new_device_id: u32 = old_device_id;
            let new_registration_id = rand::Rng::random::<u32>(&mut rand::rng()) & 0x3FFF;

            // Fresh prekeys signed by the restored identity.
            let signed = crypto::prekeys::generate_signed_prekey(&identity, 1)?;
            let one_time = crypto::prekeys::generate_one_time_prekeys(1, 20)?;
            let kyber = crypto::prekeys::generate_kyber_prekey(&identity, 1)?;
            let one_time_kyber: Vec<crypto::prekeys::GeneratedKyberPreKey> = (1u32..=20)
                .map(|id| crypto::prekeys::generate_kyber_prekey(&identity, id))
                .collect::<Result<_, _>>()?;

            // Challenge → sign with rotation key → replace.
            let primary_client = net::Client::new(&primary_server);
            let nonce = primary_client.challenge(&did, old_device_id as i32).await?;
            let replace_payload =
                format!("replace:{did}:{old_device_id}:{new_device_id}:{nonce}");
            let rotation_sig =
                recovery::sign_with_rotation_key(&rotation_key_private, replace_payload.as_bytes())?;

            let reg_resp = primary_client
                .replace_device(&ReplaceDeviceRequest {
                    did: did.clone(),
                    old_device_id: old_device_id as i32,
                    new_device_id: new_device_id as i32,
                    new_identity_key: identity.public_key().serialize(),
                    new_registration_id: new_registration_id as i32,
                    nonce,
                    rotation_key_signature: rotation_sig,
                    rotation_key: rotation_key_public.clone(),
                    signed_prekey_id: signed.wire.id as i32,
                    signed_prekey_public: signed.wire.public_key.clone(),
                    signed_prekey_signature: signed.wire.signature.clone(),
                    one_time_prekeys: one_time
                        .iter()
                        .map(|k| (k.wire.id as i32, k.wire.public_key.clone()))
                        .collect(),
                    kyber_prekey_id: kyber.wire.id as i32,
                    kyber_prekey_public: kyber.wire.public_key.clone(),
                    kyber_prekey_signature: kyber.wire.signature.clone(),
                    recovery_blob: None,
                })
                .await?;

            // Open the local store and persist the restored identity.
            let store = store::Store::open(
                Path::new(&db_path),
                &store::DatabaseKey::from_passphrase(db_key),
            )
            .await
            .map_err(AppError::from)?;

            store.save_identity(&identity, new_registration_id).await?;
            store
                .save_rotation_key(&rotation_key_private, &rotation_key_public)
                .await?;
            store
                .save_registration(&RegistrationInfo {
                    account_id: did.clone(),
                    server_url: primary_server.clone(),
                    registered_at: Timestamp::now(),
                    device_id: new_device_id,
                })
                .await?;
            store.save_signed_prekey(signed.wire.id, &signed.record).await?;
            store
                .save_one_time_prekeys(
                    &one_time
                        .iter()
                        .map(|k| (k.wire.id, k.record.clone()))
                        .collect::<Vec<_>>(),
                )
                .await?;
            store
                .save_kyber_prekeys(&[(kyber.wire.id, kyber.record.clone())])
                .await?;
            store
                .save_kyber_prekeys(
                    &one_time_kyber
                        .iter()
                        .map(|k| (k.wire.id, k.record.clone()))
                        .collect::<Vec<_>>(),
                )
                .await?;

            // Restore the user's profile from the blob if it carries one.
            // Newer blobs include profile_key + display_name so we can keep
            // the same identity contacts already have cached. Older blobs
            // (created before that field existed) won't have these — fall
            // back to the FFI `display_name` parameter and mint a fresh key.
            //
            // `profile_to_restore` holds the (32-byte key, display name) pair
            // we will persist locally and re-upload to the server.
            let blob_profile_key: Option<Vec<u8>> = if plaintext.profile_key.is_empty() {
                None
            } else {
                Some(BASE64_STANDARD
                    .decode(&plaintext.profile_key)
                    .map_err(|_| AppError::Protocol("invalid base64 profile_key in blob".into()))?)
            };

            let profile_to_restore: Option<(Vec<u8>, String)> = match blob_profile_key {
                Some(key) if key.len() == profile::PROFILE_KEY_LEN => {
                    Some((key, plaintext.display_name.clone()))
                }
                _ if !display_name.is_empty() => {
                    let key = profile::generate_profile_key();
                    Some((key.to_vec(), display_name.clone()))
                }
                _ => None,
            };

            if let Some((key, name)) = &profile_to_restore {
                store
                    .save_own_profile(&store::profiles::OwnProfile {
                        profile_key: key.clone(),
                        display_name: name.clone(),
                    })
                    .await?;
            }

            // Authenticated client carries the session token returned by replace
            // and the identity signer for transparent re-auth on 401.
            let client = build_authed_client(
                &primary_server,
                did.clone(),
                new_device_id,
                &identity,
                Some(reg_resp.session_token),
            );

            // Upload one-time Kyber public halves separately (matching create_inner).
            client
                .upload_prekeys(&net::types::UploadPrekeysRequest {
                    signed_prekey: None,
                    one_time_prekeys: None,
                    kyber_prekey: None,
                    one_time_kyber_prekeys: Some(
                        one_time_kyber
                            .iter()
                            .map(|k| {
                                (
                                    k.wire.id as i32,
                                    k.wire.public_key.clone(),
                                    k.wire.signature.clone(),
                                )
                            })
                            .collect(),
                    ),
                })
                .await?;

            // Re-upload the encrypted profile so the server-side blob matches
            // the (possibly freshly minted) profile_key. Without this, contacts
            // that see our profile_key on outbound messages would fail to
            // decrypt the server's stored blob.
            if let Some((key, name)) = &profile_to_restore {
                let mut key_arr = [0u8; profile::PROFILE_KEY_LEN];
                key_arr.copy_from_slice(key);
                let encrypted = profile::encrypt_profile(
                    &profile::ProfilePlaintext { display_name: name.clone() },
                    &key_arr,
                )?;
                client.put_profile(&encrypted).await?;
            }

            let local_address = DeviceAddress::new(
                AccountId::new(&crypto::groups::did_to_service_id_string(&did)),
                DeviceId::new(new_device_id),
            );

            let core = Arc::new(Self::build(AppCoreInner {
                store,
                client,
                local_address,
                did,
                device_id: new_device_id,
            }));
            core.start_reconnect_task();
            Ok::<_, AppError>(core)
        })
        .map_err(AppErrorFfi::from)
    }

    /// Load an existing account from the local store and authenticate.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn login(
        db_path: String,
        db_key: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let inner = rt.block_on(Self::login_inner(store))
            .map_err(AppErrorFfi::from)?;

        {
            let core = Arc::new(Self::build(inner));
            core.start_reconnect_task();
            Ok(core)
        }
    }

    pub fn did(&self) -> String {
        self.inner.blocking_lock().did.clone()
    }

    pub fn device_id(&self) -> u32 {
        self.inner.blocking_lock().device_id
    }

    /// Send an encrypted DM to a recipient. Plaintext is wrapped in a
    /// content envelope (with the sender's timestamp) before encryption.
    /// Internally fans out one ciphertext per active recipient device.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn send_dm(
        &self,
        recipient_did: String,
        plaintext: Vec<u8>,
        sent_at_ms: i64,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let ws = self.ws.lock().expect("ws mutex poisoned").clone();
            let mut inner = self.inner.lock().await;
            let body = String::from_utf8_lossy(&plaintext).into_owned();
            let profile_key = inner.own_profile_key().await;
            let msg = ContentMessage {
                body: Some(Body::Text(TextMessage { body })),
                timestamp_ms: sent_at_ms as u64,
                profile_key,
            };
            inner.send_dm(ws.as_ref(), &recipient_did, &msg.encode_to_vec(), None).await?;
            // Sending a DM is a deliberate gesture (docs/35 §"What changes a row").
            let _ = inner
                .store
                .touch_contact(&recipient_did, true, Timestamp::now())
                .await;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Fetch and decrypt all pending messages from the server.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn receive_messages(&self) -> Result<Vec<DecryptedMessage>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let ws = self.ws.lock().expect("ws mutex poisoned").clone();
            let mut inner = self.inner.lock().await;
            inner.receive_messages(ws.as_ref()).await
        }).map_err(AppErrorFfi::from)
    }

    /// Fetch the list of Projects installed on the homeserver.
    pub fn fetch_projects(&self) -> Result<Vec<ProjectInfoFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let projects = inner.client.fetch_projects().await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(projects.into_iter().map(|p| ProjectInfoFfi {
                name: p.name,
                url: p.url,
                description: p.description,
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Request a Project token for opening a Project webview.
    pub fn request_project_token(&self, project_url: String) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let resp = inner.client.request_project_token(&project_url).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(resp.token)
        }).map_err(AppErrorFfi::from)
    }

    /// Send a read receipt to a recipient for the given message timestamps.
    /// Fans out to all of the recipient's active devices.
    pub fn send_read_receipt(
        &self,
        recipient_did: String,
        timestamps: Vec<i64>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let ws = self.ws.lock().expect("ws mutex poisoned").clone();
            let mut inner = self.inner.lock().await;
            let profile_key = inner.own_profile_key().await;
            let msg = ContentMessage {
                body: Some(Body::Receipt(ReceiptMessage {
                    r#type: receipt_message::Type::Read as i32,
                    timestamps: timestamps.into_iter().map(|t| t as u64).collect(),
                })),
                timestamp_ms: 0,
                profile_key,
            };
            inner.send_dm(ws.as_ref(), &recipient_did, &msg.encode_to_vec(), None).await
        }).map_err(AppErrorFfi::from)
    }

    /// Cheap snapshot of current connection state. Non-blocking.
    pub fn connection_state(&self) -> ConnectionState {
        self.state_tx.borrow().clone()
    }

    /// Block until the connection state differs from `last`, then return the
    /// new value. iOS runs this in a tight loop on a dedicated task and
    /// publishes to its UI state.
    ///
    /// Returns `Err` if the underlying watch sender is dropped (i.e. the
    /// `AppCore` is being torn down).
    pub fn wait_for_connection_state_change(
        &self,
        last: ConnectionState,
    ) -> Result<ConnectionState, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let mut rx = self.state_tx.subscribe();
            let current = rx.borrow().clone();
            if current != last {
                return Ok::<_, AppError>(current);
            }
            rx.changed()
                .await
                .map_err(|_| AppError::Protocol("connection state channel closed".into()))?;
            let new_state = rx.borrow().clone();
            Ok(new_state)
        })
        .map_err(AppErrorFfi::from)
    }

    /// Block until at least one event is available; drain the queue and
    /// return the batch.
    ///
    /// Single-consumer: concurrent FFI callers serialize on the receiver
    /// mutex. Returns `Err` if the event channel is closed (`AppCore` torn
    /// down).
    pub fn next_events(&self) -> Result<Vec<IncomingEvent>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let mut rx = self.event_rx.lock().await;
            let first = rx
                .recv()
                .await
                .ok_or_else(|| AppError::Protocol("event channel closed".into()))?;
            let mut batch = vec![first];
            while let Ok(more) = rx.try_recv() {
                batch.push(more);
            }
            Ok::<_, AppError>(batch)
        })
        .map_err(AppErrorFfi::from)
    }

    /// Save a message to local history (SQLCipher).
    pub fn save_message(&self, msg: StoredMessageFfi) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.save_message(&store::messages::HistoryMessage {
                id: msg.id,
                conversation_id: msg.conversation_id,
                sender_did: msg.sender_did,
                body: msg.body,
                sent_at: Timestamp(msg.sent_at_ms),
                edited_at: msg.edited_at_ms.map(Timestamp),
                read_at: msg.read_at_ms.map(Timestamp),
                delivery_status: msg.delivery_status,
            }).await.map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Load messages for a conversation from local history.
    pub fn load_messages(&self, conversation_id: String) -> Result<Vec<StoredMessageFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let msgs = inner.store.load_messages(&conversation_id).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(msgs.into_iter().map(|m| StoredMessageFfi {
                id: m.id,
                conversation_id: m.conversation_id,
                sender_did: m.sender_did,
                body: m.body,
                sent_at_ms: m.sent_at.as_millis(),
                edited_at_ms: m.edited_at.map(|t| t.as_millis()),
                read_at_ms: m.read_at.map(|t| t.as_millis()),
                delivery_status: m.delivery_status,
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Enumerate every conversation that has at least one persisted message,
    /// with that conversation's most recent message attached. One row per
    /// conversation, sorted newest-first. The mobile chat list is derived
    /// directly from this — no parallel persistence in UserDefaults.
    pub fn load_conversations(&self) -> Result<Vec<ConversationSummaryFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let rows = inner.store.load_conversations().await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(rows.into_iter().map(|c| ConversationSummaryFfi {
                conversation_id: c.conversation_id,
                last_message: StoredMessageFfi {
                    id: c.last_message.id,
                    conversation_id: c.last_message.conversation_id,
                    sender_did: c.last_message.sender_did,
                    body: c.last_message.body,
                    sent_at_ms: c.last_message.sent_at.as_millis(),
                    edited_at_ms: c.last_message.edited_at.map(|t| t.as_millis()),
                    read_at_ms: c.last_message.read_at.map(|t| t.as_millis()),
                    delivery_status: c.last_message.delivery_status,
                },
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Load just the most recent message for a conversation. Returns `None`
    /// if the conversation has no messages. Used to restore conversation list
    /// previews after app restart — the plaintext body is encrypted-at-rest
    /// in SQLCipher and isn't carried in iOS UserDefaults.
    pub fn load_last_message(&self, conversation_id: String) -> Result<Option<StoredMessageFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let msg = inner.store.load_last_message(&conversation_id).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(msg.map(|m| StoredMessageFfi {
                id: m.id,
                conversation_id: m.conversation_id,
                sender_did: m.sender_did,
                body: m.body,
                sent_at_ms: m.sent_at.as_millis(),
                edited_at_ms: m.edited_at.map(|t| t.as_millis()),
                read_at_ms: m.read_at.map(|t| t.as_millis()),
                delivery_status: m.delivery_status,
            }))
        }).map_err(AppErrorFfi::from)
    }

    /// Mark messages as read up to a given sent_at timestamp.
    /// Returns the number of messages newly marked.
    pub fn mark_messages_read(&self, conversation_id: String, up_to_sent_at_ms: i64) -> Result<u64, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.mark_messages_read(
                &conversation_id,
                Timestamp(up_to_sent_at_ms),
                Timestamp::now(),
            ).await.map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Count unread messages in a conversation.
    pub fn unread_count(&self, conversation_id: String) -> Result<u64, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.unread_count(&conversation_id, &inner.did).await
                .map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Fetch public metadata for an account: display name and bot flag.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn get_account_info(&self, did: String) -> Result<AccountInfoFfi, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let info = inner.client.get_account_info(&did).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(AccountInfoFfi {
                did: info.did,
                display_name: info.display_name,
                is_bot: info.is_bot,
            })
        }).map_err(AppErrorFfi::from)
    }

    /// Register / refresh the push registration for this device.
    ///
    /// Always re-uploads the current `(pseudonym, device_token, platform,
    /// environment)` to the relay and the pseudonym to the homeserver —
    /// both endpoints accept idempotent re-registers, and re-uploading on
    /// every launch is the easiest way to recover from changes the client
    /// can't detect locally (relay URL change, relay losing its SQLite,
    /// device_token churn, etc.).
    ///
    /// Rotates the pseudonym (and unregisters the old one) when the
    /// existing registration is older than [`PUSH_ROTATION_MAX_AGE_SECONDS`]
    /// or its `(device_token, platform)` has changed.
    ///
    /// - `platform`: `"apns"` (iOS) or `"fcm"` (Android).
    /// - `relay_url`: base URL of the push relay.
    /// - `environment`: `"sandbox"` (debug builds) or `"production"` (App Store/TestFlight).
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn register_push_token(
        &self,
        device_token: String,
        platform: String,
        relay_url: String,
        environment: String,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let existing = inner.store.load_push_state().await.map_err(AppError::Store)?;
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs() as i64)
                .unwrap_or(0);

            let rotate = match &existing {
                None => true,
                Some(s) => {
                    s.device_token != device_token
                        || s.platform != platform
                        || now - s.registered_at >= PUSH_ROTATION_MAX_AGE_SECONDS
                }
            };

            let pseudonym = if rotate {
                let bytes: [u8; 32] = rand::Rng::random(&mut rand::rng());
                let new_pseudonym = base64::prelude::BASE64_URL_SAFE_NO_PAD.encode(bytes);
                inner.store.save_push_state(store::push::PushState {
                    pseudonym: new_pseudonym.clone(),
                    device_token: device_token.clone(),
                    platform: platform.clone(),
                    registered_at: 0, // ignored by save
                }).await.map_err(AppError::Store)?;
                new_pseudonym
            } else {
                existing.as_ref().unwrap().pseudonym.clone()
            };

            // Always re-register — relay+server treat this as INSERT OR REPLACE.
            inner.client
                .register_push_with_relay(&relay_url, &pseudonym, &device_token, &platform, &environment)
                .await.map_err(AppError::Net)?;
            inner.client.register_push_pseudonym(&pseudonym).await
                .map_err(AppError::Net)?;

            // If we rotated, retire the previous pseudonym. Best-effort —
            // a failure leaves a stranded row that the relay's GC reaps.
            if rotate {
                if let Some(old) = existing {
                    let _ = inner.client.unregister_push_with_relay(&relay_url, &old.pseudonym).await;
                    let _ = inner.client.unregister_push_pseudonym(&old.pseudonym).await;
                }
            }

            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Update the recovery blob on the server (e.g. after joining a new server).
    /// `prf_output` is the 32-byte WebAuthn PRF output; the blob-encryption
    /// key is derived from it via HKDF.
    /// `servers` is the updated list of homeserver URLs.
    pub fn update_recovery_blob(
        &self,
        prf_output: Vec<u8>,
        servers: Vec<String>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            if prf_output.len() != 32 {
                return Err(AppError::Protocol("prf_output must be 32 bytes".into()));
            }
            let (_, key) = recovery::derive_recovery_keys_from_prf(&prf_output);

            let inner = self.inner.lock().await;
            let identity = inner.store.load_identity().await?
                .ok_or(AppError::NoAccount)?;
            let own_profile = inner.store.load_own_profile().await?;

            let plaintext = recovery::build_recovery_plaintext(
                &identity.serialize(),
                &servers,
                own_profile.as_ref().map(|p| p.profile_key.as_slice()).unwrap_or(&[]),
                own_profile.as_ref().map(|p| p.display_name.as_str()).unwrap_or(""),
            );
            let blob = recovery::encrypt_recovery_blob(&plaintext, &key)?;
            inner.client.update_recovery_blob(&blob).await?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Return the user's own display name from the local profile cache.
    /// Empty string if no profile has been set yet.
    pub fn own_display_name(&self) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let name = inner.store.load_own_profile().await
                .map_err(AppError::from)?
                .map(|p| p.display_name)
                .unwrap_or_default();
            Ok::<_, AppError>(name)
        }).map_err(AppErrorFfi::from)
    }

    /// Update the user's display name. Re-encrypts the profile blob with the
    /// existing profile key and uploads it. The local cached name updates
    /// immediately on success.
    pub fn set_display_name(&self, display_name: String) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let own = inner.store.load_own_profile().await
                .map_err(AppError::from)?
                .ok_or_else(|| AppError::Protocol("no own profile (account not yet set up)".into()))?;
            if own.profile_key.len() != profile::PROFILE_KEY_LEN {
                return Err(AppError::Protocol("stored profile key has wrong length".into()));
            }
            let mut key = [0u8; profile::PROFILE_KEY_LEN];
            key.copy_from_slice(&own.profile_key);
            let blob = profile::encrypt_profile(
                &profile::ProfilePlaintext { display_name: display_name.clone() },
                &key,
            )?;
            inner.client.put_profile(&blob).await?;
            inner.store.update_own_display_name(&display_name).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Look up the cached display name for a contact. Returns empty string if
    /// no profile has been cached yet (the UI should fall back to the DID).
    pub fn contact_display_name(&self, did: String) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let name = inner.store.load_contact_profile(&did).await
                .map_err(AppError::from)?
                .map(|p| p.display_name)
                .unwrap_or_default();
            Ok::<_, AppError>(name)
        }).map_err(AppErrorFfi::from)
    }

    /// Re-fetch a contact's encrypted profile and update the cache if the
    /// decrypted name changed. Call this when the user opens a conversation
    /// — it's the primary change-detection path.
    ///
    /// Returns true if the cached display name was updated.
    pub fn refresh_contact_profile(&self, did: String) -> Result<bool, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let cached = inner.store.load_contact_profile(&did).await
                .map_err(AppError::from)?;
            let cached = match cached {
                Some(c) if c.profile_key.len() == profile::PROFILE_KEY_LEN => c,
                _ => return Ok::<_, AppError>(false),
            };

            let blob = match inner.client.get_profile(&did).await? {
                Some(b) => b,
                None => return Ok(false),
            };

            let mut key = [0u8; profile::PROFILE_KEY_LEN];
            key.copy_from_slice(&cached.profile_key);
            let plaintext = match profile::decrypt_profile(&blob, &key) {
                Ok(p) => p,
                Err(_) => return Ok(false),
            };

            let changed = plaintext.display_name != cached.display_name;
            inner.store.upsert_contact_profile(&store::profiles::ContactProfile {
                did,
                display_name: plaintext.display_name,
                profile_key: cached.profile_key,
                fetched_at: Timestamp::now(),
            }).await.map_err(AppError::from)?;
            Ok(changed)
        }).map_err(AppErrorFfi::from)
    }

    /// Enumerate every known contact, newest interaction first. Each row
    /// joins the curation flag from the `contacts` table with the cached
    /// display name from `contact_profiles` when available. The compose
    /// autocomplete shows `is_curated == true` rows under "People" and
    /// the rest under "Other".
    pub fn list_contacts(&self) -> Result<Vec<ContactRowFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let rows = inner.store.list_contacts().await.map_err(AppError::from)?;
            let own_did = inner.did.clone();
            let mut out = Vec::with_capacity(rows.len());
            for row in rows {
                // Don't show ourselves in our own contact list.
                if row.did == own_did {
                    continue;
                }
                let display_name = inner
                    .store
                    .load_contact_profile(&row.did)
                    .await
                    .ok()
                    .flatten()
                    .map(|p| p.display_name)
                    .unwrap_or_default();
                out.push(ContactRowFfi {
                    did: row.did,
                    display_name,
                    is_curated: row.is_curated,
                    last_interaction_at_ms: row.last_interaction_at.as_millis(),
                });
            }
            Ok::<_, AppError>(out)
        })
        .map_err(AppErrorFfi::from)
    }

    /// Touch a contact row, creating it if missing. `curated` flips
    /// `is_curated` to true (sticky); pass `false` to record an interaction
    /// without curating. The caller is responsible for tracking what's a
    /// deliberate gesture versus an automatic event.
    pub fn touch_contact(&self, did: String, curated: bool) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner
                .store
                .touch_contact(&did, curated, Timestamp::now())
                .await
                .map_err(AppError::from)
        })
        .map_err(AppErrorFfi::from)
    }

    /// Check whether this account has a recovery blob set up (has rotation key in store).
    pub fn has_recovery(&self) -> bool {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.load_rotation_key().await
                .map(|k| k.is_some())
                .unwrap_or(false)
        })
    }

}

/// How long a push pseudonym can live before [`AppCore::register_push_token`]
/// rotates it. Picked to match the relay's 7-day grace period after
/// `/v1/unregister` so old pseudonyms stay alive on the relay during the
/// brief overlap.
const PUSH_ROTATION_MAX_AGE_SECONDS: i64 = 7 * 24 * 60 * 60;

/// Resolve a `did:plc:*` against the PLC directory and return the homeserver
/// URL advertised in its DID document. Used by the recovery flow to locate
/// where the encrypted recovery blob lives without asking the user to type
/// their server URL. Returns an error for `did:local:*` (no PLC entry) or if
/// the DID has no `AvalancheHomeserver` service entry.
#[uniffi::export]
pub fn resolve_homeserver_from_plc(did: String) -> Result<String, AppErrorFfi> {
    ffi_runtime()
        .block_on(async { plc::resolve_homeserver_url(&did).await })
        .map_err(AppErrorFfi::from)
}

/// Download and decrypt a recovery blob from a homeserver (unauthenticated).
/// `server_url` is the homeserver URL, `did` is the DID to look up,
/// `prf_output` is the 32-byte WebAuthn PRF output; the blob-encryption key
/// is derived from it via HKDF. Returns the decrypted server list from the
/// blob.
#[uniffi::export]
pub fn download_recovery_blob(
    server_url: String,
    did: String,
    prf_output: Vec<u8>,
) -> Result<Vec<String>, AppErrorFfi> {
    ffi_runtime().block_on(async {
        if prf_output.len() != 32 {
            return Err(AppError::Protocol("prf_output must be 32 bytes".into()));
        }
        let (_, key) = recovery::derive_recovery_keys_from_prf(&prf_output);

        let client = net::Client::new(&server_url);
        let bundle = client.get_recovery_blob(&did).await?;
        let plaintext = recovery::decrypt_recovery_blob(&bundle.blob, &key)?;
        Ok(plaintext.servers)
    }).map_err(AppErrorFfi::from)
}

/// Derive the rotation-key public bytes + DID that a given PRF output and
/// signup server URL would produce. Used by recovery flows that need to
/// know the DID before fetching anything — particularly when the user's
/// blob has been lost and the home server is unreachable: the passkey +
/// the original signup server URL (stored in the WebAuthn userHandle) is
/// enough to recompute the DID.
#[uniffi::export]
pub fn derive_did_from_passkey(
    prf_output: Vec<u8>,
    signup_server_url: String,
) -> Result<String, AppErrorFfi> {
    if prf_output.len() != 32 {
        return Err(AppErrorFfi::from(AppError::Protocol(
            "prf_output must be 32 bytes".into(),
        )));
    }
    let (rot_seed, _) = recovery::derive_recovery_keys_from_prf(&prf_output);
    let (rot_priv, rot_pub) = recovery::derive_rotation_key_from_seed(&rot_seed);
    let genesis = plc::build_genesis_op(&rot_pub, &signup_server_url);
    let signed = plc::sign_plc_op(&genesis, &rot_priv).map_err(AppErrorFfi::from)?;
    plc::derive_did(&signed).map_err(AppErrorFfi::from)
}

/// Decoded invite token info returned to the mobile layer.
#[derive(uniffi::Record)]
pub struct InviteInfo {
    pub server_url: String,
    pub server_name: String,
    pub inviter_did: Option<String>,
    pub post_onboarding_redirect: Option<String>,
    /// Inviter's plaintext display name from the token. Shown on the invite
    /// acceptance screen before any server communication. The encrypted
    /// profile blob is the source of truth once fetched.
    pub inviter_display_name: Option<String>,
    /// Inviter's 32-byte profile key from the token, base64url-encoded.
    /// The new client primes its contact_profiles cache with this so the
    /// auto-DM can show the inviter's name from the very first frame.
    pub inviter_profile_key: Option<Vec<u8>>,
}

/// Parse and validate an invite token.
/// `token` is the base64url-encoded JSON payload from the invite URL.
/// Decodes locally to extract the server URL, then calls the server to validate.
#[uniffi::export]
pub fn validate_invite(token: String) -> Result<InviteInfo, AppErrorFfi> {
    ffi_runtime().block_on(async {
        let json_bytes = BASE64_URL_SAFE_NO_PAD
            .decode(&token)
            .map_err(|_| AppError::Protocol("invalid base64url invite token".into()))?;

        #[derive(serde::Deserialize)]
        struct TokenPayload {
            server_url: String,
            #[serde(default)]
            inviter_did: Option<String>,
            #[serde(default)]
            inviter_display_name: Option<String>,
            /// base64url-encoded 32-byte profile key.
            #[serde(default)]
            inviter_profile_key: Option<String>,
        }

        let payload: TokenPayload = serde_json::from_slice(&json_bytes)
            .map_err(|_| AppError::Protocol("invalid invite token JSON".into()))?;

        let client = net::Client::new(&payload.server_url);
        let resp = client.validate_invite(&token).await?;

        let inviter_profile_key = payload.inviter_profile_key
            .as_deref()
            .map(|b| BASE64_URL_SAFE_NO_PAD.decode(b))
            .transpose()
            .map_err(|_| AppError::Protocol("invalid base64url inviter_profile_key".into()))?
            .filter(|b| b.len() == profile::PROFILE_KEY_LEN);

        Ok::<_, AppError>(InviteInfo {
            server_url: payload.server_url,
            server_name: resp.server_name,
            inviter_did: payload.inviter_did,
            post_onboarding_redirect: resp.post_onboarding_redirect,
            inviter_display_name: payload.inviter_display_name,
            inviter_profile_key,
        })
    }).map_err(AppErrorFfi::from)
}

/// Prime the local contact_profiles cache with an inviter's profile key and
/// display name extracted from an invite token. Called by the mobile layer
/// after `create_account` when an invite was accepted, so the auto-DM with
/// the inviter shows their name from the first frame.
#[uniffi::export]
impl AppCore {
    pub fn prime_contact_profile(
        &self,
        did: String,
        display_name: String,
        profile_key: Vec<u8>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            if profile_key.len() != profile::PROFILE_KEY_LEN {
                return Err(AppError::Protocol("profile_key must be 32 bytes".into()));
            }
            let inner = self.inner.lock().await;
            inner.store.upsert_contact_profile(&store::profiles::ContactProfile {
                did,
                display_name,
                profile_key,
                fetched_at: Timestamp::now(),
            }).await.map_err(AppError::from)?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }
}

// ── Prepared account state ──────────────────────────────────────────────────

/// Pre-computed identity material with both PLC ops already signed.
///
/// The rotation key is derived from the user's passkey PRF output (or
/// random in the no-passkey path). The genesis op binds the DID to
/// `(rotation_pub, server_url)` only — the identity key is added in a
/// chained update op. Both ops are signed up front and submitted by
/// [`AppCore::finalize_account`].
///
/// The `blob_key` (when present) is also derived from the PRF and used to
/// encrypt the recovery blob during finalize, without needing iOS to pass
/// the blob key separately.
struct PreparedAccountState {
    server_url: String,
    identity: crypto::IdentityKeyPair,
    rotation_key_private: Vec<u8>,
    rotation_key_public: Vec<u8>,
    /// Some when we're using the PLC directory; submitted during finalize.
    signed_genesis: Option<plc::PlcOperation>,
    /// Identity-key update op chained to the genesis op. Submitted right
    /// after genesis at finalize time so the DID document has a verification
    /// method as soon as it's resolvable.
    signed_identity_update: Option<plc::PlcOperation>,
    did: Option<String>,
    /// 32-byte AES-GCM key for the recovery blob, derived from the PRF via
    /// HKDF label `"actnet-blob-v1"`. `None` when the user skipped passkey
    /// creation (no recovery blob is written in that case).
    blob_key: Option<[u8; 32]>,
}

impl PreparedAccountState {
    /// Build prepared state.
    ///
    /// - `prf_output`: 32-byte WebAuthn PRF output. Empty/wrong-length =
    ///   no-passkey path: random rotation key, no blob key, identity is
    ///   unrecoverable on device loss.
    /// - `use_plc_directory`: when `false`, no PLC ops are built; the
    ///   account uses a server-assigned DID (bot/test path).
    fn prepare(
        server_url: String,
        prf_output: &[u8],
        use_plc_directory: bool,
    ) -> Result<Self, AppError> {
        let identity = crypto::IdentityKeyPair::generate();

        // Derive rotation key from PRF if available, else random.
        let (rot_priv, rot_pub, blob_key) = if prf_output.len() == 32 {
            let (rot_seed, blob_key) = recovery::derive_recovery_keys_from_prf(prf_output);
            let (priv_bytes, pub_bytes) = recovery::derive_rotation_key_from_seed(&rot_seed);
            (priv_bytes, pub_bytes, Some(blob_key))
        } else {
            let (priv_bytes, pub_bytes) = recovery::generate_rotation_key();
            (priv_bytes, pub_bytes, None)
        };

        let (signed_genesis, signed_identity_update, did) = if use_plc_directory {
            let genesis_op = plc::build_genesis_op(&rot_pub, &server_url);
            let signed_genesis = plc::sign_plc_op(&genesis_op, &rot_priv)?;
            let did = plc::derive_did(&signed_genesis)?;
            let genesis_cid = plc::plc_op_cid(&signed_genesis)?;

            let identity_pub_bytes = identity.public_key().serialize();
            let identity_update_op = plc::build_identity_update_op(
                &rot_pub,
                &identity_pub_bytes,
                &server_url,
                &genesis_cid,
            );
            let signed_identity_update = plc::sign_plc_op(&identity_update_op, &rot_priv)?;

            (Some(signed_genesis), Some(signed_identity_update), Some(did))
        } else {
            (None, None, None)
        };

        Ok(Self {
            server_url,
            identity,
            rotation_key_private: rot_priv,
            rotation_key_public: rot_pub,
            signed_genesis,
            signed_identity_update,
            did,
            blob_key,
        })
    }
}

/// FFI handle wrapping a [`PreparedAccountState`]. Consumed by
/// [`AppCore::finalize_account`] (the inner state is moved out).
#[derive(uniffi::Object)]
pub struct PreparedAccount {
    state: Mutex<Option<PreparedAccountState>>,
}

#[uniffi::export]
impl PreparedAccount {
    /// Generate identity + rotation keys and derive the DID locally.
    ///
    /// `prf_output` is the 32-byte WebAuthn PRF output from the just-completed
    /// passkey ceremony. Pass an empty vec for the no-passkey path; the
    /// rotation key is then random and the identity is unrecoverable on
    /// device loss.
    ///
    /// Does **not** submit the PLC ops or contact the home server — those
    /// happen in [`AppCore::finalize_account`].
    #[uniffi::constructor]
    pub fn new(server_url: String, prf_output: Vec<u8>) -> Result<Arc<Self>, AppErrorFfi> {
        let state = PreparedAccountState::prepare(server_url, &prf_output, true)
            .map_err(AppErrorFfi::from)?;
        Ok(Arc::new(Self {
            state: Mutex::new(Some(state)),
        }))
    }

    /// The DID derived from the prepared keys. Empty string if the handle has
    /// already been consumed by `finalize_account`.
    pub fn did(&self) -> String {
        self.state
            .blocking_lock()
            .as_ref()
            .and_then(|s| s.did.clone())
            .unwrap_or_default()
    }
}

// ── Internal async implementation (not exported via FFI) ────────────────────

impl AppCore {
    async fn create_inner(
        prepared: PreparedAccountState,
        store: store::Store,
        display_name: Option<String>,
        is_bot: bool,
        did_suffix: Option<String>,
    ) -> Result<AppCoreInner, AppError> {
        let PreparedAccountState {
            server_url,
            identity,
            rotation_key_private,
            rotation_key_public,
            signed_genesis,
            signed_identity_update,
            did: client_did,
            blob_key,
        } = prepared;
        let server_url = server_url.as_str();

        let registration_id = rand::Rng::random::<u32>(&mut rand::rng()) & 0x3FFF;
        let device_id = 1u32;

        let signed = crypto::prekeys::generate_signed_prekey(&identity, 1)?;
        let one_time = crypto::prekeys::generate_one_time_prekeys(1, 20)?;
        let kyber = crypto::prekeys::generate_kyber_prekey(&identity, 1)?;
        let one_time_kyber: Vec<crypto::prekeys::GeneratedKyberPreKey> = (1u32..=20)
            .map(|id| crypto::prekeys::generate_kyber_prekey(&identity, id))
            .collect::<Result<_, _>>()?;

        // Submit the deferred PLC ops (if any). Genesis fixes the DID; the
        // identity-key update immediately adds our device verification method.
        if let (Some(signed_op), Some(did)) = (signed_genesis.as_ref(), client_did.as_ref()) {
            plc::submit_op(did, signed_op).await?;
            if let Some(update_op) = signed_identity_update.as_ref() {
                plc::submit_op(did, update_op).await?;
            }
        }

        // Generate profile key + encrypt the display name for human accounts.
        // Bots send plaintext display_name (server stores it directly for
        // looking up bot names). Humans send encrypted_profile instead, keyed
        // by a 32-byte profile key distributed via outgoing messages.
        //
        // Done before the recovery blob is built so the profile_key and
        // display_name can be sealed into the blob — letting recovery
        // restore the same profile without prompting the user again.
        let (profile_key, encrypted_profile, profile_display_name) =
            if !is_bot {
                let name = display_name.clone().unwrap_or_default();
                let key = profile::generate_profile_key();
                let blob = profile::encrypt_profile(
                    &profile::ProfilePlaintext { display_name: name.clone() },
                    &key,
                )?;
                (Some(key), Some(blob), Some(name))
            } else {
                (None, None, None)
            };

        // Build and encrypt recovery blob if we have a passkey-derived key.
        let recovery_blob = if let Some(key) = blob_key.as_ref() {
            let plaintext = recovery::build_recovery_plaintext(
                &identity.serialize(),
                &[server_url.to_string()],
                profile_key.as_ref().map(|k| k.as_slice()).unwrap_or(&[]),
                profile_display_name.as_deref().unwrap_or(""),
            );
            Some(recovery::encrypt_recovery_blob(&plaintext, key)?)
        } else {
            None
        };

        // Sign "register:{did}:{server_url}" with the identity key to prove possession.
        // Server URL is included to prevent cross-server replay of the signature.
        let identity_key_signature = if let Some(ref did) = client_did {
            let payload = format!("register:{did}:{server_url}");
            let sig = identity
                .private_key()
                .calculate_signature(payload.as_bytes(), &mut rand::rngs::OsRng.unwrap_err())
                .map_err(|e| AppError::Crypto(crypto::CryptoError::Signal(e.into())))?;
            Some(BASE64_URL_SAFE_NO_PAD.encode(&sig))
        } else {
            None
        };

        let client = net::Client::new(server_url);
        let reg_resp = client.register(&RegisterRequest {
            did: client_did.clone(),
            identity_key: identity.public_key().serialize(),
            registration_id: registration_id as i32,
            device_id: device_id as i32,
            signed_prekey_id: signed.wire.id as i32,
            signed_prekey_public: signed.wire.public_key.clone(),
            signed_prekey_signature: signed.wire.signature.clone(),
            one_time_prekeys: one_time.iter().map(|k| (k.wire.id as i32, k.wire.public_key.clone())).collect(),
            kyber_prekey_id: kyber.wire.id as i32,
            kyber_prekey_public: kyber.wire.public_key.clone(),
            kyber_prekey_signature: kyber.wire.signature.clone(),
            // Human accounts never put plaintext name on the server — name is
            // delivered via the encrypted profile blob below. Only bots use
            // server-side display_name.
            display_name: if is_bot { display_name } else { None },
            is_bot,
            did_suffix: did_suffix.clone(),
            recovery_blob,
            encrypted_profile: encrypted_profile.clone(),
            identity_key_signature,
        }).await?;

        store.save_identity(&identity, registration_id).await?;
        store.save_rotation_key(&rotation_key_private, &rotation_key_public).await?;

        // Persist own profile state locally so the UI can render our display
        // name without re-decrypting the blob.
        if let (Some(key), Some(name)) = (profile_key.as_ref(), profile_display_name.as_ref()) {
            store.save_own_profile(&store::profiles::OwnProfile {
                profile_key: key.to_vec(),
                display_name: name.clone(),
            }).await?;
        }
        store.save_registration(&RegistrationInfo {
            account_id: reg_resp.did.clone(),
            server_url: server_url.to_string(),
            registered_at: Timestamp::now(),
            device_id,
        }).await?;

        store.save_signed_prekey(signed.wire.id, &signed.record).await?;
        store.save_one_time_prekeys(
            &one_time.iter().map(|k| (k.wire.id, k.record.clone())).collect::<Vec<_>>(),
        ).await?;
        store.save_kyber_prekeys(
            &[(kyber.wire.id, kyber.record.clone())],
        ).await?;
        // Also store the one-time Kyber prekeys locally (same store as last-resort).
        store.save_kyber_prekeys(
            &one_time_kyber.iter().map(|k| (k.wire.id, k.record.clone())).collect::<Vec<_>>(),
        ).await?;

        let client = build_authed_client(
            server_url,
            reg_resp.did.clone(),
            device_id,
            &identity,
            Some(reg_resp.session_token),
        );

        // Upload one-time Kyber public halves to the server after registration.
        client.upload_prekeys(&net::types::UploadPrekeysRequest {
            signed_prekey: None,
            one_time_prekeys: None,
            kyber_prekey: None,
            one_time_kyber_prekeys: Some(
                one_time_kyber.iter().map(|k| (k.wire.id as i32, k.wire.public_key.clone(), k.wire.signature.clone())).collect(),
            ),
        }).await?;
        let local_address = DeviceAddress::new(
            AccountId::new(&crypto::groups::did_to_service_id_string(&reg_resp.did)),
            DeviceId::new(device_id),
        );

        Ok(AppCoreInner {
            store,
            client,
            local_address,
            did: reg_resp.did,
            device_id,
        })
    }

    async fn login_inner(store: store::Store) -> Result<AppCoreInner, AppError> {
        let identity = store.load_identity().await?
            .ok_or(AppError::NoAccount)?;
        let reg = store.load_registration().await?
            .ok_or(AppError::NoAccount)?;

        // Offline-safe: build the Client with a signer but no token. The first
        // authenticated request (HTTP send_authed or the reconnect task's WS
        // open) will trigger lazy challenge/response.
        let client = build_authed_client(
            &reg.server_url,
            reg.account_id.clone(),
            reg.device_id,
            &identity,
            None,
        );
        let device_id = reg.device_id;

        let local_address = DeviceAddress::new(
            AccountId::new(&crypto::groups::did_to_service_id_string(&reg.account_id)),
            DeviceId::new(device_id),
        );

        Ok(AppCoreInner {
            store,
            client,
            local_address,
            did: reg.account_id,
            device_id,
        })
    }

    /// Create account with a pre-opened store (for tests and bots that run inside
    /// an existing tokio runtime).
    ///
    /// `display_name` should only be set for bot accounts. Human display names
    /// are exchanged via encrypted profile bundles, not stored on the server.
    pub async fn create_account_with_store(
        server_url: &str,
        store: store::Store,
        display_name: Option<String>,
        is_bot: bool,
    ) -> Result<Self, AppError> {
        let prepared = PreparedAccountState::prepare(server_url.to_string(), &[], false)?;
        let inner = Self::create_inner(prepared, store, display_name, is_bot).await?;
        Ok(Self::build(inner))
    }

    /// Login with a pre-opened store (for tests).
    /// Does not spawn the reconnect task; callers that want it must wrap in
    /// `Arc` and call `start_reconnect_task()` themselves.
    pub async fn login_with_store(store: store::Store) -> Result<Self, AppError> {
        let inner = Self::login_inner(store).await?;
        Ok(Self::build(inner))
    }

    /// Async send_read_receipt for use in tests and the testbot.
    /// Fans out across all of the recipient's active devices.
    pub async fn send_read_receipt_async(
        &self,
        recipient_did: &str,
        timestamps: Vec<i64>,
    ) -> Result<(), AppError> {
        let ws = self.ws.lock().expect("ws mutex poisoned").clone();
        let mut inner = self.inner.lock().await;
        let profile_key = inner.own_profile_key().await;
        let msg = ContentMessage {
            body: Some(Body::Receipt(ReceiptMessage {
                r#type: receipt_message::Type::Read as i32,
                timestamps: timestamps.into_iter().map(|t| t as u64).collect(),
            })),
            timestamp_ms: 0,
            profile_key,
        };
        inner.send_dm(ws.as_ref(), recipient_did, &msg.encode_to_vec(), None).await
    }

    /// Async send_dm for use in tests running inside a tokio runtime.
    /// Wraps plaintext in a content envelope before encryption. Fans out
    /// across all of the recipient's active devices.
    pub async fn send_dm_async(
        &self,
        recipient_did: &str,
        plaintext: &[u8],
        sent_at_ms: i64,
    ) -> Result<(), AppError> {
        let ws = self.ws.lock().expect("ws mutex poisoned").clone();
        let mut inner = self.inner.lock().await;
        let body = String::from_utf8_lossy(plaintext).into_owned();
        let profile_key = inner.own_profile_key().await;
        let msg = ContentMessage {
            body: Some(Body::Text(TextMessage { body })),
            timestamp_ms: sent_at_ms as u64,
            profile_key,
        };
        inner.send_dm(ws.as_ref(), recipient_did, &msg.encode_to_vec(), None).await
    }

    /// Async receive_messages for use in tests running inside a tokio runtime.
    pub async fn receive_messages_async(&self) -> Result<Vec<DecryptedMessage>, AppError> {
        let ws = self.ws.lock().expect("ws mutex poisoned").clone();
        let mut inner = self.inner.lock().await;
        inner.receive_messages(ws.as_ref()).await
    }

    /// Get DID (async-friendly, for tests).
    pub async fn did_async(&self) -> String {
        self.inner.lock().await.did.clone()
    }

    /// Look up a cached contact's display name (async, for tests and bots).
    /// Returns `None` if no profile has been received yet for this DID.
    pub async fn contact_display_name_async(&self, did: &str) -> Option<String> {
        let inner = self.inner.lock().await;
        inner.store.load_contact_profile(did).await
            .ok()
            .flatten()
            .map(|p| p.display_name)
            .filter(|n| !n.is_empty())
    }

    /// Get device_id (async-friendly, for tests).
    pub async fn device_id_async(&self) -> u32 {
        self.inner.lock().await.device_id
    }

    /// Async variant of `create_group` (for tests / testbot). Seeds the
    /// founder's own Sender Key locally on success.
    pub async fn create_group_async(
        &self,
        title: &str,
        description: &str,
        expiry_seconds: u32,
    ) -> Result<groups::CreatedGroup, AppError> {
        let mut inner = self.inner.lock().await;
        let did = inner.did.clone();
        let device_id = inner.device_id;
        let server_url = inner.client.server_url().to_string();
        let created = groups::create_group(
            &inner.store,
            &inner.client,
            &server_url,
            &did,
            title,
            description,
            expiry_seconds,
        )
        .await?;
        let mk: [u8; 32] = created
            .master_key
            .clone()
            .try_into()
            .map_err(|_| AppError::Protocol("master_key length != 32".into()))?;
        let _ = groups::seed_own_sender_key(&mut inner.store, &did, device_id, &mk).await?;
        Ok(created)
    }

    /// Async variant of `fetch_group_state`.
    pub async fn fetch_group_state_async(
        &self,
        group_id: &str,
    ) -> Result<groups::GroupSummary, AppError> {
        let inner = self.inner.lock().await;
        let did = inner.did.clone();
        let server_url = inner.client.server_url().to_string();
        groups::fetch_group_state(&inner.store, &inner.client, &server_url, &did, group_id).await
    }

    /// Async variant of `invite_member`. Also sends the `GroupContext`
    /// DM + the inviter's SKDM (best-effort). Unlike the sync FFI
    /// version this doesn't talk to the WebSocket — tests use HTTP.
    pub async fn invite_member_async(
        &self,
        group_id: &str,
        recipient_did: &str,
        role: i16,
    ) -> Result<(), AppError> {
        let mut inner = self.inner.lock().await;
        let did = inner.did.clone();
        let device_id = inner.device_id;
        let row = inner
            .store
            .load_group(group_id)
            .await?
            .ok_or_else(|| AppError::Protocol("group not found".into()))?;
        let hosting_server_url = row.hosting_server_url.clone();
        let master_key_vec = row.master_key.clone();
        let mk: [u8; 32] = master_key_vec
            .clone()
            .try_into()
            .map_err(|_| AppError::Protocol("master_key length != 32".into()))?;
        let group_id_bytes = groups::b64d(group_id)?;
        groups::invite_member(
            &inner.store,
            &inner.client,
            &did,
            group_id,
            recipient_did,
            role,
        )
        .await?;

        let skdm = groups::seed_own_sender_key(&mut inner.store, &did, device_id, &mk).await?;

        let ctx = ContentMessage {
            body: Some(Body::GroupContext(proto::GroupContext {
                group_master_key: master_key_vec,
                hosting_server_url,
                inviter_did: did.clone(),
                invited_at_ms: Timestamp::now().as_millis(),
                invite_link_password: Vec::new(),
            })),
            timestamp_ms: Timestamp::now().as_millis() as u64,
            profile_key: inner.own_profile_key().await,
        };
        inner
            .send_dm(None, recipient_did, &ctx.encode_to_vec(), None)
            .await?;
        let skdm_msg = ContentMessage {
            body: Some(Body::SenderKeyDistribution(proto::SenderKeyDistribution {
                group_id: group_id_bytes,
                distribution_id: groups::distribution_id_for(&mk).as_bytes().to_vec(),
                skdm,
            })),
            timestamp_ms: Timestamp::now().as_millis() as u64,
            profile_key: Vec::new(),
        };
        inner
            .send_dm(None, recipient_did, &skdm_msg.encode_to_vec(), None)
            .await?;
        Ok(())
    }

    /// Async variant of `accept_invite`. After promoting, generates our
    /// own Sender Key and broadcasts the SKDM as a DM to every other
    /// member listed in our cached group state.
    pub async fn accept_invite_async(&self, group_id: &str) -> Result<(), AppError> {
        let mut inner = self.inner.lock().await;
        let did = inner.did.clone();
        let device_id = inner.device_id;
        groups::accept_invite(&inner.store, &inner.client, &did, group_id).await?;

        let mk = groups::master_key_for(&inner.store, group_id).await?;
        let skdm = groups::seed_own_sender_key(&mut inner.store, &did, device_id, &mk).await?;
        let group_id_bytes = groups::b64d(group_id)?;
        let recipients = groups::other_member_dids(&inner.store, group_id, &did).await?;
        for rdid in recipients {
            let skdm_msg = ContentMessage {
                body: Some(Body::SenderKeyDistribution(
                    proto::SenderKeyDistribution {
                        group_id: group_id_bytes.clone(),
                        distribution_id: groups::distribution_id_for(&mk).as_bytes().to_vec(),
                        skdm: skdm.clone(),
                    },
                )),
                timestamp_ms: Timestamp::now().as_millis() as u64,
                profile_key: Vec::new(),
            };
            inner
                .send_dm(None, &rdid, &skdm_msg.encode_to_vec(), None)
                .await?;
        }
        Ok(())
    }

    /// Drain queued sealed-sender group messages for `group_id` via the
    /// HTTP offline-pickup endpoint, decrypt + validate each, and return
    /// the plaintexts in delivery order. Acked server-side as part of
    /// the call. Used by the e2e tests; the production receive path is
    /// the WS `GroupDeliverRequest` push.
    pub async fn fetch_group_messages_async(
        &self,
        group_id: &str,
    ) -> Result<Vec<groups::ReceivedGroupMessage>, AppError> {
        let mut inner = self.inner.lock().await;
        let did = inner.did.clone();
        let server_url = inner.client.server_url().to_string();
        let AppCoreInner {
            ref mut store,
            ref client,
            ..
        } = *inner;
        groups::fetch_group_messages(store, client, &server_url, &did, group_id).await
    }

    /// Async variant of `send_group_message`. Builds a sealed-sender SSv2
    /// envelope over a SenderKey ciphertext of `plaintext` and POSTs it to
    /// `/v1/groups/{id}/send`. Per-recipient routing is by
    /// `group_push_pseudonym` (looked up server-side from the EMI we
    /// supply); the server cannot link the message to either the sender
    /// or the recipient DIDs.
    pub async fn send_group_message_async(
        &self,
        group_id: &str,
        plaintext: &[u8],
    ) -> Result<(), AppError> {
        let mut inner = self.inner.lock().await;
        let did = inner.did.clone();
        let device_id = inner.device_id;
        let server_url = inner.client.server_url().to_string();
        let AppCoreInner {
            ref mut store,
            ref client,
            ..
        } = *inner;
        groups::send_group_message(
            store, client, &server_url, &did, device_id, group_id, plaintext,
        )
        .await?;
        Ok(())
    }

    /// Block on the next batch of events from the reconnect task. Async
    /// equivalent of the FFI `next_events`. Used by the testbot.
    ///
    /// The reconnect task must be running (`start_reconnect_task`) for events
    /// to arrive.
    pub async fn next_events_async(&self) -> Result<Vec<IncomingEvent>, AppError> {
        let mut rx = self.event_rx.lock().await;
        let first = rx
            .recv()
            .await
            .ok_or_else(|| AppError::Protocol("event channel closed".into()))?;
        let mut batch = vec![first];
        while let Ok(more) = rx.try_recv() {
            batch.push(more);
        }
        Ok(batch)
    }

    /// Block on the next batch of admin events. Mirror of `next_events_async`
    /// but for the admin-only `AdminEvent` queue. Not FFI-exported — used by
    /// the napi binding and (via that) admin Projects like the adminbot.
    ///
    /// For non-adminbot sessions the queue stays empty and this future
    /// pends forever; callers should only drive it on bot sessions.
    pub async fn next_admin_events_async(&self) -> Result<Vec<AdminEvent>, AppError> {
        let mut rx = self.admin_event_rx.lock().await;
        let first = rx
            .recv()
            .await
            .ok_or_else(|| AppError::Protocol("admin event channel closed".into()))?;
        let mut batch = vec![first];
        while let Ok(more) = rx.try_recv() {
            batch.push(more);
        }
        Ok(batch)
    }
}

