//! Application core — orchestrates crypto, store, and net.
//!
//! This is the main entry point for client applications. It wires together the
//! three foundation crates:
//!
//! - **crypto** — X3DH session initiation, Double Ratchet encrypt/decrypt
//! - **store** — local SQLCipher database for sessions, prekeys, messages
//! - **net** — HTTP client for the homeserver API
//!
//! `app-core` owns the high-level flows: account creation, sending a DM,
//! receiving messages, and prekey management. Mobile apps (via UniFFI) and
//! integration tests call into this crate.
//!
//! # FFI design
//!
//! UniFFI-exported methods are synchronous. They block on an internal tokio
//! runtime. Mobile callers should invoke them from a background
//! thread/dispatch queue, never from the main/UI thread.

pub mod error;
pub mod plc;
pub mod profile;
pub mod recovery;

pub mod proto {
    // Generated by prost from proto/content.proto at build time (see build.rs)
    include!(concat!(env!("OUT_DIR"), "/actnet.rs"));
}

use std::path::Path;
use std::sync::Arc;

use base64::prelude::*;
use crypto::session::{self, DeviceAddress, EncryptedMessage, MessageKind};
use error::{AppError, AppErrorFfi};
use net::types::{OutboundMessage, RegisterRequest, ReplaceDeviceRequest};
use proto::{content_message::Body, receipt_message, ContentMessage, ReceiptMessage, TextMessage};
use prost::Message as _;
use rand::TryRngCore as _;
use store::account::RegistrationInfo;
use tokio::sync::Mutex;
use types::{AccountId, DeviceId, Timestamp};

uniffi::setup_scaffolding!();

/// Shared tokio runtime for FFI blocking calls. Created once, lives forever.
fn ffi_runtime() -> &'static tokio::runtime::Runtime {
    static RT: std::sync::OnceLock<tokio::runtime::Runtime> = std::sync::OnceLock::new();
    RT.get_or_init(|| tokio::runtime::Runtime::new().expect("failed to create tokio runtime"))
}

/// A Project available on the homeserver.
#[derive(uniffi::Record)]
pub struct ProjectInfoFfi {
    pub name: String,
    pub url: String,
    pub description: String,
}

/// A decrypted inbound message.
#[derive(uniffi::Record)]
pub struct DecryptedMessage {
    pub server_id: i64,
    pub sender_did: String,
    pub sender_device_id: u32,
    pub plaintext: Vec<u8>,
    /// Sender's sent_at timestamp (from envelope). None for legacy messages.
    pub sent_at_ms: Option<i64>,
}

/// A message from local history (persisted in SQLCipher).
#[derive(uniffi::Record)]
pub struct StoredMessageFfi {
    pub id: String,
    pub conversation_id: String,
    pub sender_did: String,
    pub body: String,
    pub sent_at_ms: i64,
    pub edited_at_ms: Option<i64>,
    /// NULL = unread, Some = unix millis when marked read.
    pub read_at_ms: Option<i64>,
    /// 0 = sending, 1 = sent, 2 = delivered, 3 = read.
    pub delivery_status: u8,
}

/// A conversation summary used to build the chat list on startup: one row
/// per conversation that has at least one persisted message, with the most
/// recent message attached.
#[derive(uniffi::Record)]
pub struct ConversationSummaryFfi {
    pub conversation_id: String,
    pub last_message: StoredMessageFfi,
}

/// A delivery status update for an outgoing message (e.g. read receipt received).
#[derive(uniffi::Record, Clone)]
pub struct DeliveryStatusUpdate {
    pub conversation_id: String,
    pub sent_at_ms: i64,
    pub delivery_status: u8,
}

/// Public metadata for an account: display name and bot flag.
///
/// `display_name` is only populated for bot accounts. Human display names are
/// exchanged via encrypted profile bundles (client-to-client), never stored on
/// the server.
#[derive(uniffi::Record)]
pub struct AccountInfoFfi {
    pub did: String,
    pub display_name: Option<String>,
    pub is_bot: bool,
}

/// The main client handle. Holds local state and a server connection.
///
/// Thread-safe: all mutable state is behind an async Mutex, and the object
/// is wrapped in Arc by UniFFI. Safe to call from multiple Swift/Kotlin threads.
///
/// Exported methods are blocking — call from a background thread.
#[derive(uniffi::Object)]
pub struct AppCore {
    inner: Mutex<AppCoreInner>,
    /// WebSocket connection for real-time message delivery. Separate from
    /// `inner` so that `send_dm` can proceed while waiting for WS messages.
    ws: Mutex<Option<net::ws::WsConnection>>,
    /// Buffered delivery status updates from incoming read receipts.
    /// Drained by `drain_receipt_updates()` after each WS receive.
    receipt_updates: Mutex<Vec<DeliveryStatusUpdate>>,
}

struct AppCoreInner {
    store: store::Store,
    client: net::Client,
    local_address: DeviceAddress,
    did: String,
    device_id: u32,
}

#[uniffi::export]
impl AppCore {
    /// Create a new account on the server.
    ///
    /// `recovery_key` is a 32-byte symmetric key (from passkey PRF or recovery phrase).
    /// If provided, a recovery blob is encrypted and uploaded to the server.
    /// Pass an empty vec to skip recovery setup.
    ///
    /// `display_name` is the user's chosen display name. A profile key is
    /// generated, the name is encrypted under it, and the blob is uploaded
    /// atomically with registration. The profile key travels with outgoing
    /// messages so contacts can fetch and decrypt the blob.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn create_account(
        server_url: String,
        db_path: String,
        db_key: String,
        recovery_key: Vec<u8>,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let rk = if recovery_key.len() == 32 {
            let mut arr = [0u8; 32];
            arr.copy_from_slice(&recovery_key);
            Some(arr)
        } else {
            None
        };

        let prepared = PreparedAccountState::prepare(server_url, true)
            .map_err(AppErrorFfi::from)?;
        let inner = rt.block_on(Self::create_inner(prepared, store, Some(display_name), false, rk.as_ref()))
            .map_err(AppErrorFfi::from)?;

        Ok(Arc::new(Self { inner: Mutex::new(inner), ws: Mutex::new(None), receipt_updates: Mutex::new(Vec::new()) }))
    }

    /// Finalize account registration using a previously prepared identity.
    ///
    /// Use this when the passkey ceremony needs the DID up front: call
    /// [`PreparedAccount::new`] first to compute the DID locally, register the
    /// passkey with that DID, then call this to encrypt the recovery blob,
    /// submit the PLC genesis op, and complete server registration.
    ///
    /// The `prepared` handle is consumed (its inner state is moved out); a
    /// second call with the same handle returns an error.
    #[uniffi::constructor]
    pub fn finalize_account(
        prepared: Arc<PreparedAccount>,
        db_path: String,
        db_key: String,
        recovery_key: Vec<u8>,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let state = prepared
            .state
            .blocking_lock()
            .take()
            .ok_or_else(|| AppError::Protocol("PreparedAccount already consumed".into()))
            .map_err(AppErrorFfi::from)?;

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let rk = if recovery_key.len() == 32 {
            let mut arr = [0u8; 32];
            arr.copy_from_slice(&recovery_key);
            Some(arr)
        } else {
            None
        };

        let inner = rt.block_on(Self::create_inner(state, store, Some(display_name), false, rk.as_ref()))
            .map_err(AppErrorFfi::from)?;

        Ok(Arc::new(Self { inner: Mutex::new(inner), ws: Mutex::new(None), receipt_updates: Mutex::new(Vec::new()) }))
    }

    /// Recover an account from a passkey-protected recovery blob.
    ///
    /// 1. Downloads the encrypted blob from `server_url` keyed by `did`.
    /// 2. Decrypts with `recovery_key` (32-byte PRF-derived symmetric key).
    /// 3. Extracts the identity keypair, rotation key, and server list.
    /// 4. Generates a new `device_id`, fresh prekeys, and a fresh registration ID.
    /// 5. Signs a replacement payload with the rotation key and POSTs to
    ///    `/v1/devices/replace` on the primary server (first in the blob's
    ///    server list, falling back to `server_url`). The server revokes the
    ///    old device's sessions/prekeys and registers the new one, returning a
    ///    session token.
    /// 6. Opens a fresh local SQLCipher store at `db_path` and persists the
    ///    restored identity, rotation key, registration, and prekeys.
    /// 7. Returns an `AppCore` ready to send/receive messages.
    ///
    /// The recovered account keeps the original identity key, so contacts see
    /// no safety-number change.
    ///
    /// `display_name` is optional — pass an empty string to leave it unset
    /// (the user can update it from Settings later). The blob does not carry
    /// the original profile key, so a fresh profile key is generated.
    ///
    /// **Multi-server caveat:** if the blob lists more than one server, only
    /// the primary one is replaced. Replacing on the remaining servers is a TODO.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn recover_from_blob(
        server_url: String,
        did: String,
        recovery_key: Vec<u8>,
        db_path: String,
        db_key: String,
        display_name: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();
        rt.block_on(async move {
            if recovery_key.len() != 32 {
                return Err(AppError::Protocol("recovery_key must be 32 bytes".into()));
            }
            let mut rk = [0u8; 32];
            rk.copy_from_slice(&recovery_key);

            // Download the blob and the current device list (one unauthenticated call).
            let bundle = net::Client::new(&server_url).get_recovery_blob(&did).await?;
            let plaintext = recovery::decrypt_recovery_blob(&bundle.blob, &rk)?;

            // Restore identity keypair.
            let identity_bytes = BASE64_STANDARD
                .decode(&plaintext.identity_keypair)
                .map_err(|_| AppError::Protocol("invalid base64 identity in blob".into()))?;
            let identity = crypto::IdentityKeyPair::deserialize(&identity_bytes)?;

            // Restore rotation key (private), re-derive the public half.
            let rotation_key_private = BASE64_STANDARD
                .decode(&plaintext.rotation_key)
                .map_err(|_| AppError::Protocol("invalid base64 rotation key in blob".into()))?;
            let rotation_signing = p256::ecdsa::SigningKey::from_bytes(
                (&rotation_key_private[..]).into(),
            )
            .map_err(|e| AppError::Protocol(format!("invalid rotation private key: {e}")))?;
            let rotation_key_public = rotation_signing
                .verifying_key()
                .to_encoded_point(true)
                .as_bytes()
                .to_vec();

            // Pick the server we'll talk to (and that AppCore will be bound to).
            let primary_server = plaintext
                .servers
                .first()
                .cloned()
                .unwrap_or_else(|| server_url.clone());

            // Pick the existing device_id from the bundle and reuse it for
            // the new device so existing senders keep working. The server
            // deletes the old device row before inserting the new one, so
            // reusing the ID doesn't conflict with UNIQUE (account_id, device_id).
            //
            // `min()` is arbitrary here — we expect exactly one device today.
            // For multi-device, this is wrong: recovery means "I lost one
            // device" and shouldn't silently kill the others. Revisit to
            // either register a fresh device_id alongside the existing ones,
            // or prompt the user to pick which device to replace.
            let old_device_id: u32 = bundle
                .device_ids
                .iter()
                .copied()
                .min()
                .map(|d| d as u32)
                .unwrap_or(1);
            let new_device_id: u32 = old_device_id;
            let new_registration_id = rand::Rng::random::<u32>(&mut rand::rng()) & 0x3FFF;

            // Fresh prekeys signed by the restored identity.
            let signed = crypto::prekeys::generate_signed_prekey(&identity, 1)?;
            let one_time = crypto::prekeys::generate_one_time_prekeys(1, 20)?;
            let kyber = crypto::prekeys::generate_kyber_prekey(&identity, 1)?;
            let one_time_kyber: Vec<crypto::prekeys::GeneratedKyberPreKey> = (1u32..=20)
                .map(|id| crypto::prekeys::generate_kyber_prekey(&identity, id))
                .collect::<Result<_, _>>()?;

            // Challenge → sign with rotation key → replace.
            let primary_client = net::Client::new(&primary_server);
            let nonce = primary_client.challenge(&did, old_device_id as i32).await?;
            let replace_payload =
                format!("replace:{did}:{old_device_id}:{new_device_id}:{nonce}");
            let rotation_sig =
                recovery::sign_with_rotation_key(&rotation_key_private, replace_payload.as_bytes())?;

            let reg_resp = primary_client
                .replace_device(&ReplaceDeviceRequest {
                    did: did.clone(),
                    old_device_id: old_device_id as i32,
                    new_device_id: new_device_id as i32,
                    new_identity_key: identity.public_key().serialize(),
                    new_registration_id: new_registration_id as i32,
                    nonce,
                    rotation_key_signature: rotation_sig,
                    rotation_key: rotation_key_public.clone(),
                    signed_prekey_id: signed.wire.id as i32,
                    signed_prekey_public: signed.wire.public_key.clone(),
                    signed_prekey_signature: signed.wire.signature.clone(),
                    one_time_prekeys: one_time
                        .iter()
                        .map(|k| (k.wire.id as i32, k.wire.public_key.clone()))
                        .collect(),
                    kyber_prekey_id: kyber.wire.id as i32,
                    kyber_prekey_public: kyber.wire.public_key.clone(),
                    kyber_prekey_signature: kyber.wire.signature.clone(),
                    recovery_blob: None,
                })
                .await?;

            // Open the local store and persist the restored identity.
            let store = store::Store::open(
                Path::new(&db_path),
                &store::DatabaseKey::from_passphrase(db_key),
            )
            .await
            .map_err(AppError::from)?;

            store.save_identity(&identity, new_registration_id).await?;
            store
                .save_rotation_key(&rotation_key_private, &rotation_key_public)
                .await?;
            store
                .save_registration(&RegistrationInfo {
                    account_id: did.clone(),
                    server_url: primary_server.clone(),
                    registered_at: Timestamp::now(),
                    device_id: new_device_id,
                })
                .await?;
            store.save_signed_prekey(signed.wire.id, &signed.record).await?;
            store
                .save_one_time_prekeys(
                    &one_time
                        .iter()
                        .map(|k| (k.wire.id, k.record.clone()))
                        .collect::<Vec<_>>(),
                )
                .await?;
            store
                .save_kyber_prekeys(&[(kyber.wire.id, kyber.record.clone())])
                .await?;
            store
                .save_kyber_prekeys(
                    &one_time_kyber
                        .iter()
                        .map(|k| (k.wire.id, k.record.clone()))
                        .collect::<Vec<_>>(),
                )
                .await?;

            // Restore the user's profile from the blob if it carries one.
            // Newer blobs include profile_key + display_name so we can keep
            // the same identity contacts already have cached. Older blobs
            // (created before that field existed) won't have these — fall
            // back to the FFI `display_name` parameter and mint a fresh key.
            //
            // `profile_to_restore` holds the (32-byte key, display name) pair
            // we will persist locally and re-upload to the server.
            let blob_profile_key: Option<Vec<u8>> = if plaintext.profile_key.is_empty() {
                None
            } else {
                Some(BASE64_STANDARD
                    .decode(&plaintext.profile_key)
                    .map_err(|_| AppError::Protocol("invalid base64 profile_key in blob".into()))?)
            };

            let profile_to_restore: Option<(Vec<u8>, String)> = match blob_profile_key {
                Some(key) if key.len() == profile::PROFILE_KEY_LEN => {
                    Some((key, plaintext.display_name.clone()))
                }
                _ if !display_name.is_empty() => {
                    let key = profile::generate_profile_key();
                    Some((key.to_vec(), display_name.clone()))
                }
                _ => None,
            };

            if let Some((key, name)) = &profile_to_restore {
                store
                    .save_own_profile(&store::profiles::OwnProfile {
                        profile_key: key.clone(),
                        display_name: name.clone(),
                    })
                    .await?;
            }

            // Authenticated client carries the session token returned by replace.
            let client = net::Client::with_token(&primary_server, reg_resp.session_token);

            // Upload one-time Kyber public halves separately (matching create_inner).
            client
                .upload_prekeys(&net::types::UploadPrekeysRequest {
                    signed_prekey: None,
                    one_time_prekeys: None,
                    kyber_prekey: None,
                    one_time_kyber_prekeys: Some(
                        one_time_kyber
                            .iter()
                            .map(|k| {
                                (
                                    k.wire.id as i32,
                                    k.wire.public_key.clone(),
                                    k.wire.signature.clone(),
                                )
                            })
                            .collect(),
                    ),
                })
                .await?;

            // Re-upload the encrypted profile so the server-side blob matches
            // the (possibly freshly minted) profile_key. Without this, contacts
            // that see our profile_key on outbound messages would fail to
            // decrypt the server's stored blob.
            if let Some((key, name)) = &profile_to_restore {
                let mut key_arr = [0u8; profile::PROFILE_KEY_LEN];
                key_arr.copy_from_slice(key);
                let encrypted = profile::encrypt_profile(
                    &profile::ProfilePlaintext { display_name: name.clone() },
                    &key_arr,
                )?;
                client.put_profile(&encrypted).await?;
            }

            let local_address = DeviceAddress::new(
                AccountId::new(&did),
                DeviceId::new(new_device_id),
            );

            Ok::<_, AppError>(Arc::new(Self {
                inner: Mutex::new(AppCoreInner {
                    store,
                    client,
                    local_address,
                    did,
                    device_id: new_device_id,
                }),
                ws: Mutex::new(None),
                receipt_updates: Mutex::new(Vec::new()),
            }))
        })
        .map_err(AppErrorFfi::from)
    }

    /// Load an existing account from the local store and authenticate.
    ///
    /// Call from a background thread — this blocks until complete.
    #[uniffi::constructor]
    pub fn login(
        db_path: String,
        db_key: String,
    ) -> Result<Arc<Self>, AppErrorFfi> {
        let rt = ffi_runtime();

        let store = rt.block_on(store::Store::open(
            Path::new(&db_path),
            &store::DatabaseKey::from_passphrase(db_key),
        )).map_err(AppError::from).map_err(AppErrorFfi::from)?;

        let inner = rt.block_on(Self::login_inner(store))
            .map_err(AppErrorFfi::from)?;

        Ok(Arc::new(Self { inner: Mutex::new(inner), ws: Mutex::new(None), receipt_updates: Mutex::new(Vec::new()) }))
    }

    pub fn did(&self) -> String {
        self.inner.blocking_lock().did.clone()
    }

    pub fn device_id(&self) -> u32 {
        self.inner.blocking_lock().device_id
    }

    /// Send an encrypted DM to a recipient. Plaintext is wrapped in a
    /// content envelope (with the sender's timestamp) before encryption.
    /// Internally fans out one ciphertext per active recipient device.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn send_dm(
        &self,
        recipient_did: String,
        plaintext: Vec<u8>,
        sent_at_ms: i64,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let mut inner = self.inner.lock().await;
            let body = String::from_utf8_lossy(&plaintext).into_owned();
            let profile_key = inner.own_profile_key().await;
            let msg = ContentMessage {
                body: Some(Body::Text(TextMessage { body })),
                timestamp_ms: sent_at_ms as u64,
                profile_key,
            };
            inner.send_dm(&recipient_did, &msg.encode_to_vec(), None).await
        }).map_err(AppErrorFfi::from)
    }

    /// Fetch and decrypt all pending messages from the server.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn receive_messages(&self) -> Result<Vec<DecryptedMessage>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let mut inner = self.inner.lock().await;
            inner.receive_messages().await
        }).map_err(AppErrorFfi::from)
    }

    /// Fetch the list of Projects installed on the homeserver.
    pub fn fetch_projects(&self) -> Result<Vec<ProjectInfoFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let projects = inner.client.fetch_projects().await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(projects.into_iter().map(|p| ProjectInfoFfi {
                name: p.name,
                url: p.url,
                description: p.description,
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Request a Project token for opening a Project webview.
    pub fn request_project_token(&self, project_url: String) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let resp = inner.client.request_project_token(&project_url).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(resp.token)
        }).map_err(AppErrorFfi::from)
    }

    /// Send a read receipt to a recipient for the given message timestamps.
    /// Fans out to all of the recipient's active devices.
    pub fn send_read_receipt(
        &self,
        recipient_did: String,
        timestamps: Vec<i64>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let mut inner = self.inner.lock().await;
            let profile_key = inner.own_profile_key().await;
            let msg = ContentMessage {
                body: Some(Body::Receipt(ReceiptMessage {
                    r#type: receipt_message::Type::Read as i32,
                    timestamps: timestamps.into_iter().map(|t| t as u64).collect(),
                })),
                timestamp_ms: 0,
                profile_key,
            };
            inner.send_dm(&recipient_did, &msg.encode_to_vec(), None).await
        }).map_err(AppErrorFfi::from)
    }

    /// Drain buffered delivery status updates (from incoming read receipts).
    /// Call after each `receive_messages_ws` to get real-time status updates.
    pub fn drain_receipt_updates(&self) -> Vec<DeliveryStatusUpdate> {
        ffi_runtime().block_on(async {
            let mut updates = self.receipt_updates.lock().await;
            std::mem::take(&mut *updates)
        })
    }

    /// Save a message to local history (SQLCipher).
    pub fn save_message(&self, msg: StoredMessageFfi) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.save_message(&store::messages::HistoryMessage {
                id: msg.id,
                conversation_id: msg.conversation_id,
                sender_did: msg.sender_did,
                body: msg.body,
                sent_at: Timestamp(msg.sent_at_ms),
                edited_at: msg.edited_at_ms.map(Timestamp),
                read_at: msg.read_at_ms.map(Timestamp),
                delivery_status: msg.delivery_status,
            }).await.map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Load messages for a conversation from local history.
    pub fn load_messages(&self, conversation_id: String) -> Result<Vec<StoredMessageFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let msgs = inner.store.load_messages(&conversation_id).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(msgs.into_iter().map(|m| StoredMessageFfi {
                id: m.id,
                conversation_id: m.conversation_id,
                sender_did: m.sender_did,
                body: m.body,
                sent_at_ms: m.sent_at.as_millis(),
                edited_at_ms: m.edited_at.map(|t| t.as_millis()),
                read_at_ms: m.read_at.map(|t| t.as_millis()),
                delivery_status: m.delivery_status,
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Enumerate every conversation that has at least one persisted message,
    /// with that conversation's most recent message attached. One row per
    /// conversation, sorted newest-first. The mobile chat list is derived
    /// directly from this — no parallel persistence in UserDefaults.
    pub fn load_conversations(&self) -> Result<Vec<ConversationSummaryFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let rows = inner.store.load_conversations().await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(rows.into_iter().map(|c| ConversationSummaryFfi {
                conversation_id: c.conversation_id,
                last_message: StoredMessageFfi {
                    id: c.last_message.id,
                    conversation_id: c.last_message.conversation_id,
                    sender_did: c.last_message.sender_did,
                    body: c.last_message.body,
                    sent_at_ms: c.last_message.sent_at.as_millis(),
                    edited_at_ms: c.last_message.edited_at.map(|t| t.as_millis()),
                    read_at_ms: c.last_message.read_at.map(|t| t.as_millis()),
                    delivery_status: c.last_message.delivery_status,
                },
            }).collect())
        }).map_err(AppErrorFfi::from)
    }

    /// Load just the most recent message for a conversation. Returns `None`
    /// if the conversation has no messages. Used to restore conversation list
    /// previews after app restart — the plaintext body is encrypted-at-rest
    /// in SQLCipher and isn't carried in iOS UserDefaults.
    pub fn load_last_message(&self, conversation_id: String) -> Result<Option<StoredMessageFfi>, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let msg = inner.store.load_last_message(&conversation_id).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(msg.map(|m| StoredMessageFfi {
                id: m.id,
                conversation_id: m.conversation_id,
                sender_did: m.sender_did,
                body: m.body,
                sent_at_ms: m.sent_at.as_millis(),
                edited_at_ms: m.edited_at.map(|t| t.as_millis()),
                read_at_ms: m.read_at.map(|t| t.as_millis()),
                delivery_status: m.delivery_status,
            }))
        }).map_err(AppErrorFfi::from)
    }

    /// Mark messages as read up to a given sent_at timestamp.
    /// Returns the number of messages newly marked.
    pub fn mark_messages_read(&self, conversation_id: String, up_to_sent_at_ms: i64) -> Result<u64, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.mark_messages_read(
                &conversation_id,
                Timestamp(up_to_sent_at_ms),
                Timestamp::now(),
            ).await.map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Count unread messages in a conversation.
    pub fn unread_count(&self, conversation_id: String) -> Result<u64, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.unread_count(&conversation_id, &inner.did).await
                .map_err(AppError::from)
        }).map_err(AppErrorFfi::from)
    }

    /// Wait for the next message(s) via WebSocket, decrypt, and return.
    ///
    /// Lazily connects on first call. Blocks until at least one message
    /// arrives. Returns an empty vec if the connection is closed (caller
    /// should retry to reconnect).
    ///
    /// Call from a background thread — this blocks until messages arrive.
    pub fn receive_messages_ws(&self) -> Result<Vec<DecryptedMessage>, AppErrorFfi> {
        ffi_runtime().block_on(self.receive_messages_ws_async())
            .map_err(AppErrorFfi::from)
    }

    /// Fetch public metadata for an account: display name and bot flag.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn get_account_info(&self, did: String) -> Result<AccountInfoFfi, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let info = inner.client.get_account_info(&did).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(AccountInfoFfi {
                did: info.did,
                display_name: info.display_name,
                is_bot: info.is_bot,
            })
        }).map_err(AppErrorFfi::from)
    }

    /// Register a push device token with the homeserver via a fresh pseudonym.
    /// Generates a random pseudonym, persists it locally, and notifies the server.
    ///
    /// `platform` is `"apns"` (iOS) or `"fcm"` (Android).
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn register_push_token(&self, device_token: String, platform: String) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let bytes: [u8; 32] = rand::Rng::random(&mut rand::rng());
            let pseudonym = base64::prelude::BASE64_URL_SAFE_NO_PAD.encode(bytes);
            inner.store.save_push_state(store::push::PushState {
                pseudonym: pseudonym.clone(),
                device_token,
                platform,
            }).await.map_err(AppError::Store)?;
            inner.client.register_push_pseudonym(&pseudonym).await
                .map_err(AppError::Net)?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Update the recovery blob on the server (e.g. after joining a new server).
    /// `recovery_key` is the 32-byte symmetric key from passkey PRF.
    /// `servers` is the updated list of homeserver URLs.
    pub fn update_recovery_blob(
        &self,
        recovery_key: Vec<u8>,
        servers: Vec<String>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            if recovery_key.len() != 32 {
                return Err(AppError::Protocol("recovery_key must be 32 bytes".into()));
            }
            let mut key = [0u8; 32];
            key.copy_from_slice(&recovery_key);

            let inner = self.inner.lock().await;
            let identity = inner.store.load_identity().await?
                .ok_or(AppError::NoAccount)?;
            let rotation = inner.store.load_rotation_key().await?
                .ok_or(AppError::Protocol("no rotation key in store".into()))?;
            let own_profile = inner.store.load_own_profile().await?;

            let plaintext = recovery::build_recovery_plaintext(
                &rotation.0,
                &identity.serialize(),
                &servers,
                own_profile.as_ref().map(|p| p.profile_key.as_slice()).unwrap_or(&[]),
                own_profile.as_ref().map(|p| p.display_name.as_str()).unwrap_or(""),
            );
            let blob = recovery::encrypt_recovery_blob(&plaintext, &key)?;
            inner.client.update_recovery_blob(&blob).await?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Return the user's own display name from the local profile cache.
    /// Empty string if no profile has been set yet.
    pub fn own_display_name(&self) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let name = inner.store.load_own_profile().await
                .map_err(AppError::from)?
                .map(|p| p.display_name)
                .unwrap_or_default();
            Ok::<_, AppError>(name)
        }).map_err(AppErrorFfi::from)
    }

    /// Update the user's display name. Re-encrypts the profile blob with the
    /// existing profile key and uploads it. The local cached name updates
    /// immediately on success.
    pub fn set_display_name(&self, display_name: String) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let own = inner.store.load_own_profile().await
                .map_err(AppError::from)?
                .ok_or_else(|| AppError::Protocol("no own profile (account not yet set up)".into()))?;
            if own.profile_key.len() != profile::PROFILE_KEY_LEN {
                return Err(AppError::Protocol("stored profile key has wrong length".into()));
            }
            let mut key = [0u8; profile::PROFILE_KEY_LEN];
            key.copy_from_slice(&own.profile_key);
            let blob = profile::encrypt_profile(
                &profile::ProfilePlaintext { display_name: display_name.clone() },
                &key,
            )?;
            inner.client.put_profile(&blob).await?;
            inner.store.update_own_display_name(&display_name).await
                .map_err(AppError::from)?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }

    /// Look up the cached display name for a contact. Returns empty string if
    /// no profile has been cached yet (the UI should fall back to the DID).
    pub fn contact_display_name(&self, did: String) -> Result<String, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let name = inner.store.load_contact_profile(&did).await
                .map_err(AppError::from)?
                .map(|p| p.display_name)
                .unwrap_or_default();
            Ok::<_, AppError>(name)
        }).map_err(AppErrorFfi::from)
    }

    /// Re-fetch a contact's encrypted profile and update the cache if the
    /// decrypted name changed. Call this when the user opens a conversation
    /// — it's the primary change-detection path.
    ///
    /// Returns true if the cached display name was updated.
    pub fn refresh_contact_profile(&self, did: String) -> Result<bool, AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let cached = inner.store.load_contact_profile(&did).await
                .map_err(AppError::from)?;
            let cached = match cached {
                Some(c) if c.profile_key.len() == profile::PROFILE_KEY_LEN => c,
                _ => return Ok::<_, AppError>(false),
            };

            let blob = match inner.client.get_profile(&did).await? {
                Some(b) => b,
                None => return Ok(false),
            };

            let mut key = [0u8; profile::PROFILE_KEY_LEN];
            key.copy_from_slice(&cached.profile_key);
            let plaintext = match profile::decrypt_profile(&blob, &key) {
                Ok(p) => p,
                Err(_) => return Ok(false),
            };

            let changed = plaintext.display_name != cached.display_name;
            inner.store.upsert_contact_profile(&store::profiles::ContactProfile {
                did,
                display_name: plaintext.display_name,
                profile_key: cached.profile_key,
                fetched_at: Timestamp::now(),
            }).await.map_err(AppError::from)?;
            Ok(changed)
        }).map_err(AppErrorFfi::from)
    }

    /// Check whether this account has a recovery blob set up (has rotation key in store).
    pub fn has_recovery(&self) -> bool {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            inner.store.load_rotation_key().await
                .map(|k| k.is_some())
                .unwrap_or(false)
        })
    }

    /// Rotate the push pseudonym: register a new one, then unregister the old one.
    /// The relay keeps the old pseudonym active for a 7-day grace period.
    ///
    /// Call from a background thread — this blocks until complete.
    pub fn rotate_push_pseudonym(&self) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            let inner = self.inner.lock().await;
            let old = inner.store.load_push_state().await
                .map_err(AppError::Store)?;
            if let Some(old_state) = old {
                let bytes: [u8; 32] = rand::Rng::random(&mut rand::rng());
                let new_pseudonym = base64::prelude::BASE64_URL_SAFE_NO_PAD.encode(bytes);
                inner.store.save_push_state(store::push::PushState {
                    pseudonym: new_pseudonym.clone(),
                    device_token: old_state.device_token,
                    platform: old_state.platform,
                }).await.map_err(AppError::Store)?;
                inner.client.register_push_pseudonym(&new_pseudonym).await
                    .map_err(AppError::Net)?;
                inner.client.unregister_push_pseudonym(&old_state.pseudonym).await
                    .map_err(AppError::Net)?;
            }
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }
}

/// Download and decrypt a recovery blob from a homeserver (unauthenticated).
/// `server_url` is the homeserver URL, `did` is the DID to look up,
/// `recovery_key` is the 32-byte symmetric key from passkey PRF or phrase.
/// Returns the decrypted server list from the blob.
#[uniffi::export]
pub fn download_recovery_blob(
    server_url: String,
    did: String,
    recovery_key: Vec<u8>,
) -> Result<Vec<String>, AppErrorFfi> {
    ffi_runtime().block_on(async {
        if recovery_key.len() != 32 {
            return Err(AppError::Protocol("recovery_key must be 32 bytes".into()));
        }
        let mut key = [0u8; 32];
        key.copy_from_slice(&recovery_key);

        let client = net::Client::new(&server_url);
        let bundle = client.get_recovery_blob(&did).await?;
        let plaintext = recovery::decrypt_recovery_blob(&bundle.blob, &key)?;
        Ok(plaintext.servers)
    }).map_err(AppErrorFfi::from)
}

/// Decoded invite token info returned to the mobile layer.
#[derive(uniffi::Record)]
pub struct InviteInfo {
    pub server_url: String,
    pub server_name: String,
    pub inviter_did: Option<String>,
    pub post_onboarding_redirect: Option<String>,
    /// Inviter's plaintext display name from the token. Shown on the invite
    /// acceptance screen before any server communication. The encrypted
    /// profile blob is the source of truth once fetched.
    pub inviter_display_name: Option<String>,
    /// Inviter's 32-byte profile key from the token, base64url-encoded.
    /// The new client primes its contact_profiles cache with this so the
    /// auto-DM can show the inviter's name from the very first frame.
    pub inviter_profile_key: Option<Vec<u8>>,
}

/// Parse and validate an invite token.
/// `token` is the base64url-encoded JSON payload from the invite URL.
/// Decodes locally to extract the server URL, then calls the server to validate.
#[uniffi::export]
pub fn validate_invite(token: String) -> Result<InviteInfo, AppErrorFfi> {
    ffi_runtime().block_on(async {
        let json_bytes = BASE64_URL_SAFE_NO_PAD
            .decode(&token)
            .map_err(|_| AppError::Protocol("invalid base64url invite token".into()))?;

        #[derive(serde::Deserialize)]
        struct TokenPayload {
            server_url: String,
            #[serde(default)]
            inviter_did: Option<String>,
            #[serde(default)]
            inviter_display_name: Option<String>,
            /// base64url-encoded 32-byte profile key.
            #[serde(default)]
            inviter_profile_key: Option<String>,
        }

        let payload: TokenPayload = serde_json::from_slice(&json_bytes)
            .map_err(|_| AppError::Protocol("invalid invite token JSON".into()))?;

        let client = net::Client::new(&payload.server_url);
        let resp = client.validate_invite(&token).await?;

        let inviter_profile_key = payload.inviter_profile_key
            .as_deref()
            .map(|b| BASE64_URL_SAFE_NO_PAD.decode(b))
            .transpose()
            .map_err(|_| AppError::Protocol("invalid base64url inviter_profile_key".into()))?
            .filter(|b| b.len() == profile::PROFILE_KEY_LEN);

        Ok::<_, AppError>(InviteInfo {
            server_url: payload.server_url,
            server_name: resp.server_name,
            inviter_did: payload.inviter_did,
            post_onboarding_redirect: resp.post_onboarding_redirect,
            inviter_display_name: payload.inviter_display_name,
            inviter_profile_key,
        })
    }).map_err(AppErrorFfi::from)
}

/// Prime the local contact_profiles cache with an inviter's profile key and
/// display name extracted from an invite token. Called by the mobile layer
/// after `create_account` when an invite was accepted, so the auto-DM with
/// the inviter shows their name from the first frame.
#[uniffi::export]
impl AppCore {
    pub fn prime_contact_profile(
        &self,
        did: String,
        display_name: String,
        profile_key: Vec<u8>,
    ) -> Result<(), AppErrorFfi> {
        ffi_runtime().block_on(async {
            if profile_key.len() != profile::PROFILE_KEY_LEN {
                return Err(AppError::Protocol("profile_key must be 32 bytes".into()));
            }
            let inner = self.inner.lock().await;
            inner.store.upsert_contact_profile(&store::profiles::ContactProfile {
                did,
                display_name,
                profile_key,
                fetched_at: Timestamp::now(),
            }).await.map_err(AppError::from)?;
            Ok::<_, AppError>(())
        }).map_err(AppErrorFfi::from)
    }
}

// ── Prepared account state ──────────────────────────────────────────────────

/// Pre-computed identity material whose DID can be known *before* server
/// registration — useful when the passkey ceremony needs to write the DID
/// into the credential's user handle. PLC submission is deferred to
/// [`AppCore::finalize_account`] so that a cancelled passkey ceremony does
/// not leave a stranded DID in the directory.
struct PreparedAccountState {
    server_url: String,
    identity: crypto::IdentityKeyPair,
    rotation_key_private: Vec<u8>,
    rotation_key_public: Vec<u8>,
    /// Some when we're using the PLC directory (the signed genesis op is
    /// submitted during finalize); None for the bot/test path.
    signed_genesis: Option<plc::PlcOperation>,
    did: Option<String>,
}

impl PreparedAccountState {
    fn prepare(server_url: String, use_plc_directory: bool) -> Result<Self, AppError> {
        let identity = crypto::IdentityKeyPair::generate();
        let (rot_priv, rot_pub) = recovery::generate_rotation_key();

        let (signed_genesis, did) = if use_plc_directory {
            let identity_pub_bytes = identity.public_key().serialize();
            let genesis_op = plc::build_genesis_op(&rot_pub, &identity_pub_bytes, &server_url);
            let signed = plc::sign_plc_op(&genesis_op, &rot_priv)?;
            let did = plc::derive_did(&signed)?;
            (Some(signed), Some(did))
        } else {
            (None, None)
        };

        Ok(Self {
            server_url,
            identity,
            rotation_key_private: rot_priv,
            rotation_key_public: rot_pub,
            signed_genesis,
            did,
        })
    }
}

/// FFI handle wrapping a [`PreparedAccountState`]. Consumed by
/// [`AppCore::finalize_account`] (the inner state is moved out).
#[derive(uniffi::Object)]
pub struct PreparedAccount {
    state: Mutex<Option<PreparedAccountState>>,
}

#[uniffi::export]
impl PreparedAccount {
    /// Generate identity + rotation keys and derive the DID locally.
    /// Does **not** submit the PLC genesis op or contact the home server —
    /// those happen in [`AppCore::finalize_account`].
    #[uniffi::constructor]
    pub fn new(server_url: String) -> Result<Arc<Self>, AppErrorFfi> {
        let state = PreparedAccountState::prepare(server_url, true)
            .map_err(AppErrorFfi::from)?;
        Ok(Arc::new(Self {
            state: Mutex::new(Some(state)),
        }))
    }

    /// The DID derived from the prepared keys. Empty string if the handle has
    /// already been consumed by `finalize_account`.
    pub fn did(&self) -> String {
        self.state
            .blocking_lock()
            .as_ref()
            .and_then(|s| s.did.clone())
            .unwrap_or_default()
    }
}

// ── Internal async implementation (not exported via FFI) ────────────────────

impl AppCore {
    async fn create_inner(
        prepared: PreparedAccountState,
        store: store::Store,
        display_name: Option<String>,
        is_bot: bool,
        recovery_key: Option<&[u8; 32]>,
    ) -> Result<AppCoreInner, AppError> {
        let PreparedAccountState {
            server_url,
            identity,
            rotation_key_private,
            rotation_key_public,
            signed_genesis,
            did: client_did,
        } = prepared;
        let server_url = server_url.as_str();

        let registration_id = rand::Rng::random::<u32>(&mut rand::rng()) & 0x3FFF;
        let device_id = 1u32;

        let signed = crypto::prekeys::generate_signed_prekey(&identity, 1)?;
        let one_time = crypto::prekeys::generate_one_time_prekeys(1, 20)?;
        let kyber = crypto::prekeys::generate_kyber_prekey(&identity, 1)?;
        let one_time_kyber: Vec<crypto::prekeys::GeneratedKyberPreKey> = (1u32..=20)
            .map(|id| crypto::prekeys::generate_kyber_prekey(&identity, id))
            .collect::<Result<_, _>>()?;

        // Submit the deferred PLC genesis op (if any) — we already have the DID.
        if let (Some(signed_op), Some(did)) = (signed_genesis.as_ref(), client_did.as_ref()) {
            plc::submit_genesis(did, signed_op).await?;
        }

        // Generate profile key + encrypt the display name for human accounts.
        // Bots send plaintext display_name (server stores it directly for
        // looking up bot names). Humans send encrypted_profile instead, keyed
        // by a 32-byte profile key distributed via outgoing messages.
        //
        // Done before the recovery blob is built so the profile_key and
        // display_name can be sealed into the blob — letting recovery
        // restore the same profile without prompting the user again.
        let (profile_key, encrypted_profile, profile_display_name) =
            if !is_bot {
                let name = display_name.clone().unwrap_or_default();
                let key = profile::generate_profile_key();
                let blob = profile::encrypt_profile(
                    &profile::ProfilePlaintext { display_name: name.clone() },
                    &key,
                )?;
                (Some(key), Some(blob), Some(name))
            } else {
                (None, None, None)
            };

        // Build and encrypt recovery blob if a recovery key is provided.
        let recovery_blob = if let Some(key) = recovery_key {
            let plaintext = recovery::build_recovery_plaintext(
                &rotation_key_private,
                &identity.serialize(),
                &[server_url.to_string()],
                profile_key.as_ref().map(|k| k.as_slice()).unwrap_or(&[]),
                profile_display_name.as_deref().unwrap_or(""),
            );
            Some(recovery::encrypt_recovery_blob(&plaintext, key)?)
        } else {
            None
        };

        // Sign "register:{did}:{server_url}" with the identity key to prove possession.
        // Server URL is included to prevent cross-server replay of the signature.
        let identity_key_signature = if let Some(ref did) = client_did {
            let payload = format!("register:{did}:{server_url}");
            let sig = identity
                .private_key()
                .calculate_signature(payload.as_bytes(), &mut rand::rngs::OsRng.unwrap_err())
                .map_err(|e| AppError::Crypto(crypto::CryptoError::Signal(e.into())))?;
            Some(BASE64_URL_SAFE_NO_PAD.encode(&sig))
        } else {
            None
        };

        let client = net::Client::new(server_url);
        let reg_resp = client.register(&RegisterRequest {
            did: client_did.clone(),
            identity_key: identity.public_key().serialize(),
            registration_id: registration_id as i32,
            device_id: device_id as i32,
            signed_prekey_id: signed.wire.id as i32,
            signed_prekey_public: signed.wire.public_key.clone(),
            signed_prekey_signature: signed.wire.signature.clone(),
            one_time_prekeys: one_time.iter().map(|k| (k.wire.id as i32, k.wire.public_key.clone())).collect(),
            kyber_prekey_id: kyber.wire.id as i32,
            kyber_prekey_public: kyber.wire.public_key.clone(),
            kyber_prekey_signature: kyber.wire.signature.clone(),
            // Human accounts never put plaintext name on the server — name is
            // delivered via the encrypted profile blob below. Only bots use
            // server-side display_name.
            display_name: if is_bot { display_name } else { None },
            is_bot,
            recovery_blob,
            encrypted_profile: encrypted_profile.clone(),
            identity_key_signature,
        }).await?;

        store.save_identity(&identity, registration_id).await?;
        store.save_rotation_key(&rotation_key_private, &rotation_key_public).await?;

        // Persist own profile state locally so the UI can render our display
        // name without re-decrypting the blob.
        if let (Some(key), Some(name)) = (profile_key.as_ref(), profile_display_name.as_ref()) {
            store.save_own_profile(&store::profiles::OwnProfile {
                profile_key: key.to_vec(),
                display_name: name.clone(),
            }).await?;
        }
        store.save_registration(&RegistrationInfo {
            account_id: reg_resp.did.clone(),
            server_url: server_url.to_string(),
            registered_at: Timestamp::now(),
            device_id,
        }).await?;

        store.save_signed_prekey(signed.wire.id, &signed.record).await?;
        store.save_one_time_prekeys(
            &one_time.iter().map(|k| (k.wire.id, k.record.clone())).collect::<Vec<_>>(),
        ).await?;
        store.save_kyber_prekeys(
            &[(kyber.wire.id, kyber.record.clone())],
        ).await?;
        // Also store the one-time Kyber prekeys locally (same store as last-resort).
        store.save_kyber_prekeys(
            &one_time_kyber.iter().map(|k| (k.wire.id, k.record.clone())).collect::<Vec<_>>(),
        ).await?;

        let client = net::Client::with_token(server_url, reg_resp.session_token);

        // Upload one-time Kyber public halves to the server after registration.
        client.upload_prekeys(&net::types::UploadPrekeysRequest {
            signed_prekey: None,
            one_time_prekeys: None,
            kyber_prekey: None,
            one_time_kyber_prekeys: Some(
                one_time_kyber.iter().map(|k| (k.wire.id as i32, k.wire.public_key.clone(), k.wire.signature.clone())).collect(),
            ),
        }).await?;
        let local_address = DeviceAddress::new(
            AccountId::new(&reg_resp.did),
            DeviceId::new(device_id),
        );

        Ok(AppCoreInner {
            store,
            client,
            local_address,
            did: reg_resp.did,
            device_id,
        })
    }

    async fn login_inner(store: store::Store) -> Result<AppCoreInner, AppError> {
        let identity = store.load_identity().await?
            .ok_or(AppError::NoAccount)?;
        let reg = store.load_registration().await?
            .ok_or(AppError::NoAccount)?;

        let client = net::Client::new(&reg.server_url);
        let device_id = reg.device_id;

        // Challenge-response: fetch nonce, sign it with our Ed25519 identity key.
        let nonce = client.challenge(&reg.account_id, device_id as i32).await?;
        let nonce_bytes = BASE64_URL_SAFE_NO_PAD
            .decode(&nonce)
            .map_err(|_| AppError::Protocol("server returned invalid nonce encoding".into()))?;
        let signature = identity
            .private_key()
            .calculate_signature(&nonce_bytes, &mut rand::rngs::OsRng.unwrap_err())
            .map_err(|e| AppError::Crypto(crypto::CryptoError::Signal(e.into())))?;

        let auth = client.authenticate(&reg.account_id, device_id as i32, &nonce, &signature).await?;
        let client = net::Client::with_token(&reg.server_url, auth.session_token);

        let local_address = DeviceAddress::new(
            AccountId::new(&reg.account_id),
            DeviceId::new(device_id),
        );

        Ok(AppCoreInner {
            store,
            client,
            local_address,
            did: reg.account_id,
            device_id,
        })
    }

    /// Create account with a pre-opened store (for tests and bots that run inside
    /// an existing tokio runtime).
    ///
    /// `display_name` should only be set for bot accounts. Human display names
    /// are exchanged via encrypted profile bundles, not stored on the server.
    pub async fn create_account_with_store(
        server_url: &str,
        store: store::Store,
        display_name: Option<String>,
        is_bot: bool,
    ) -> Result<Self, AppError> {
        let prepared = PreparedAccountState::prepare(server_url.to_string(), false)?;
        let inner = Self::create_inner(prepared, store, display_name, is_bot, None).await?;
        Ok(Self { inner: Mutex::new(inner), ws: Mutex::new(None), receipt_updates: Mutex::new(Vec::new()) })
    }

    /// Login with a pre-opened store (for tests).
    pub async fn login_with_store(store: store::Store) -> Result<Self, AppError> {
        let inner = Self::login_inner(store).await?;
        Ok(Self { inner: Mutex::new(inner), ws: Mutex::new(None), receipt_updates: Mutex::new(Vec::new()) })
    }

    /// Async send_read_receipt for use in tests and the testbot.
    /// Fans out across all of the recipient's active devices.
    pub async fn send_read_receipt_async(
        &self,
        recipient_did: &str,
        timestamps: Vec<i64>,
    ) -> Result<(), AppError> {
        let mut inner = self.inner.lock().await;
        let profile_key = inner.own_profile_key().await;
        let msg = ContentMessage {
            body: Some(Body::Receipt(ReceiptMessage {
                r#type: receipt_message::Type::Read as i32,
                timestamps: timestamps.into_iter().map(|t| t as u64).collect(),
            })),
            timestamp_ms: 0,
            profile_key,
        };
        inner.send_dm(recipient_did, &msg.encode_to_vec(), None).await
    }

    /// Async send_dm for use in tests running inside a tokio runtime.
    /// Wraps plaintext in a content envelope before encryption. Fans out
    /// across all of the recipient's active devices.
    pub async fn send_dm_async(
        &self,
        recipient_did: &str,
        plaintext: &[u8],
        sent_at_ms: i64,
    ) -> Result<(), AppError> {
        let mut inner = self.inner.lock().await;
        let body = String::from_utf8_lossy(plaintext).into_owned();
        let profile_key = inner.own_profile_key().await;
        let msg = ContentMessage {
            body: Some(Body::Text(TextMessage { body })),
            timestamp_ms: sent_at_ms as u64,
            profile_key,
        };
        inner.send_dm(recipient_did, &msg.encode_to_vec(), None).await
    }

    /// Async receive_messages for use in tests running inside a tokio runtime.
    pub async fn receive_messages_async(&self) -> Result<Vec<DecryptedMessage>, AppError> {
        let mut inner = self.inner.lock().await;
        inner.receive_messages().await
    }

    /// Get DID (async-friendly, for tests).
    pub async fn did_async(&self) -> String {
        self.inner.lock().await.did.clone()
    }

    /// Look up a cached contact's display name (async, for tests and bots).
    /// Returns `None` if no profile has been received yet for this DID.
    pub async fn contact_display_name_async(&self, did: &str) -> Option<String> {
        let inner = self.inner.lock().await;
        inner.store.load_contact_profile(did).await
            .ok()
            .flatten()
            .map(|p| p.display_name)
            .filter(|n| !n.is_empty())
    }

    /// Get device_id (async-friendly, for tests).
    pub async fn device_id_async(&self) -> u32 {
        self.inner.lock().await.device_id
    }

    /// Async version of receive_messages_ws for use in tests and the testbot.
    pub async fn receive_messages_ws_async(&self) -> Result<Vec<DecryptedMessage>, AppError> {
        // 1. Ensure WS is connected.
        {
            let mut ws_guard = self.ws.lock().await;
            if ws_guard.is_none() {
                let inner = self.inner.lock().await;
                let token = inner.client.token()
                    .ok_or_else(|| AppError::Protocol("no session token for WS".into()))?
                    .to_string();
                let url = inner.client.server_url().to_string();
                drop(inner);
                *ws_guard = Some(net::ws::WsConnection::connect(&url, &token).await?);
            }
        }

        // 2. Wait for next message (ws lock only, inner is free for send_dm).
        let raw_msg = {
            let mut ws_guard = self.ws.lock().await;
            let ws_conn = ws_guard.as_mut().unwrap();
            match ws_conn.next_message().await {
                Ok(Some(msg)) => msg,
                Ok(None) => {
                    // Connection closed — clear so next call reconnects.
                    *ws_guard = None;
                    return Ok(vec![]);
                }
                Err(e) => {
                    *ws_guard = None;
                    return Err(e.into());
                }
            }
        };

        // 3. Decrypt (inner lock). If decryption fails, ack the message
        //    anyway so it doesn't block the queue forever, then skip it.
        let decrypted = {
            let mut inner = self.inner.lock().await;
            match inner.decrypt_inbound(&raw_msg).await {
                Ok(msg) => msg,
                Err(e) => {
                    eprintln!(
                        "[ws] failed to decrypt message {} from {:?}: {}, acking to skip",
                        raw_msg.id, raw_msg.sender_did, e
                    );
                    // Ack the undecryptable message so it doesn't block the queue.
                    let mut ws_guard = self.ws.lock().await;
                    if let Some(ws_conn) = ws_guard.as_mut() {
                        let _ = ws_conn.ack(&[raw_msg.id]).await;
                    }
                    // Return empty — caller will loop and get the next message.
                    return Ok(vec![]);
                }
            }
        };

        // 4. Ack via WS.
        {
            let mut ws_guard = self.ws.lock().await;
            if let Some(ws_conn) = ws_guard.as_mut() {
                let _ = ws_conn.ack(&[raw_msg.id]).await;
            }
        }

        // 5. Parse envelope. Handle receipts internally; return content messages.
        match ContentMessage::decode(decrypted.plaintext.as_slice()) {
            Ok(msg) => {
                // Process inbound profile_key (any variant may carry one).
                if !msg.profile_key.is_empty() {
                    let inner = self.inner.lock().await;
                    inner.handle_inbound_profile_key(&decrypted.sender_did, &msg.profile_key).await;
                }
                match msg.body {
                Some(Body::Receipt(receipt)) => {
                    // Receipt — update delivery status in store and buffer for Swift.
                    // DELIVERY (0) = status 2, READ (1) = status 3.
                    let status: u8 = if receipt.r#type == receipt_message::Type::Read as i32 { 3 } else { 2 };
                    let timestamps: Vec<i64> = receipt.timestamps.into_iter().map(|t| t as i64).collect();
                    if !timestamps.is_empty() {
                        let inner = self.inner.lock().await;
                        let conv_id = format!(
                            "dm-{}-{}",
                            inner.did, decrypted.sender_did
                        );
                        let _ = inner
                            .store
                            .update_delivery_status(&conv_id, &timestamps, status)
                            .await;
                        let mut updates = self.receipt_updates.lock().await;
                        for ts in &timestamps {
                            updates.push(DeliveryStatusUpdate {
                                conversation_id: conv_id.clone(),
                                sent_at_ms: *ts,
                                delivery_status: status,
                            });
                        }
                    }
                    Ok(vec![])
                }
                Some(Body::Text(text)) => {
                    // Content message — unwrap body and sender timestamp from envelope.
                    let body = text.body;
                    let sent_at = if msg.timestamp_ms > 0 { Some(msg.timestamp_ms as i64) } else { None };

                    // Auto-send delivery receipt back to the sender.
                    if let Some(ts) = sent_at {
                        let mut inner = self.inner.lock().await;
                        let profile_key = inner.own_profile_key().await;
                        let delivery = ContentMessage {
                            body: Some(Body::Receipt(ReceiptMessage {
                                r#type: receipt_message::Type::Delivery as i32,
                                timestamps: vec![ts as u64],
                            })),
                            timestamp_ms: 0,
                            profile_key,
                        };
                        let _ = inner.send_dm(
                            &decrypted.sender_did,
                            &delivery.encode_to_vec(),
                            None,
                        ).await;
                    }

                    Ok(vec![DecryptedMessage {
                        plaintext: body.into_bytes(),
                        sent_at_ms: sent_at,
                        ..decrypted
                    }])
                }
                None => {
                    // ContentMessage with no body — treat raw bytes as plain text (backward compat).
                    Ok(vec![decrypted])
                }
                }
            }
            Err(_) => {
                // Not a valid protobuf — treat raw bytes as plain text (backward compat).
                Ok(vec![decrypted])
            }
        }
    }
}

impl AppCoreInner {
    /// Process an inbound `profile_key` from a ContentMessage. If non-empty
    /// and different from any cached key, fetch the sender's encrypted blob,
    /// decrypt, and update the contact_profiles cache. Errors are swallowed
    /// — profile fetches are best-effort and must never block message
    /// delivery.
    async fn handle_inbound_profile_key(&self, sender_did: &str, profile_key: &[u8]) {
        if profile_key.len() != profile::PROFILE_KEY_LEN {
            return;
        }

        let needs_fetch = match self.store.load_contact_profile_key(sender_did).await {
            Ok(Some(cached)) => cached != profile_key,
            Ok(None) => true,
            Err(_) => return,
        };
        if !needs_fetch {
            return;
        }

        let blob = match self.client.get_profile(sender_did).await {
            Ok(Some(b)) => b,
            Ok(None) | Err(_) => return,
        };

        let mut key = [0u8; profile::PROFILE_KEY_LEN];
        key.copy_from_slice(profile_key);
        let plaintext = match profile::decrypt_profile(&blob, &key) {
            Ok(p) => p,
            Err(_) => return,
        };

        let _ = self.store.upsert_contact_profile(&store::profiles::ContactProfile {
            did: sender_did.to_string(),
            display_name: plaintext.display_name,
            profile_key: profile_key.to_vec(),
            fetched_at: Timestamp::now(),
        }).await;
    }

    /// Load the user's own profile key as bytes, or empty if not yet set.
    /// Empty bytes in the proto field signal "not sharing" — recipients ignore
    /// a zero-length `profile_key` field.
    async fn own_profile_key(&self) -> Vec<u8> {
        self.store
            .load_own_profile()
            .await
            .ok()
            .flatten()
            .map(|p| p.profile_key)
            .unwrap_or_default()
    }

    /// Send raw bytes (already enveloped) as an encrypted DM.
    /// Fan-out send: fetches the recipient's active device list and encrypts a
    /// copy of `plaintext` for each device, sending them as one batch.
    ///
    /// Mirrors Signal's `SignalServiceMessageSender.sendMessage` shape: callers
    /// don't think about device IDs. Stale-device handling (`409`/`410`) is a
    /// later improvement — for now, each send hits `GET /v1/accounts/{did}/devices`.
    async fn send_dm(
        &mut self,
        recipient_did: &str,
        plaintext: &[u8],
        expiry_secs: Option<i64>,
    ) -> Result<(), AppError> {
        let device_ids = self.client.fetch_devices(recipient_did).await?;
        if device_ids.is_empty() {
            return Err(AppError::Protocol(format!(
                "no active devices for recipient {recipient_did}"
            )));
        }

        let mut envelopes = Vec::with_capacity(device_ids.len());
        for device_id in device_ids {
            let env = self
                .encrypt_for_device(recipient_did, device_id as u32, plaintext, expiry_secs)
                .await?;
            envelopes.push(env);
        }

        self.client.send_messages(&envelopes).await?;
        Ok(())
    }

    /// Per-device encryption helper: establishes a Double Ratchet session if
    /// needed (fetching that device's prekey bundle), encrypts the plaintext,
    /// and returns the `OutboundMessage` envelope ready for `send_messages`.
    async fn encrypt_for_device(
        &mut self,
        recipient_did: &str,
        recipient_device_id: u32,
        plaintext: &[u8],
        expiry_secs: Option<i64>,
    ) -> Result<OutboundMessage, AppError> {
        let recipient_addr = DeviceAddress::new(
            AccountId::new(recipient_did),
            DeviceId::new(recipient_device_id),
        );

        let has_session = {
            use libsignal_protocol::SessionStore;
            let protocol_addr = libsignal_protocol::ProtocolAddress::new(
                recipient_did.to_string(),
                libsignal_protocol::DeviceId::try_from(recipient_device_id).unwrap(),
            );
            self.store.load_session(&protocol_addr).await
                .map_err(|e| AppError::Crypto(crypto::CryptoError::Signal(e)))?
                .is_some()
        };

        if !has_session {
            let bundle = self.client
                .fetch_prekey_bundle(recipient_did, recipient_device_id as i32)
                .await?;

            let recipient_bundle = crypto::RecipientKeyBundle {
                identity_key: bundle.identity_key.clone(),
                registration_id: bundle.registration_id as u32,
                device_id: recipient_device_id,
                signed_prekey: crypto::SignedPreKey {
                    id: bundle.signed_prekey_id as u32,
                    public_key: bundle.signed_prekey_public,
                    signature: bundle.signed_prekey_signature,
                },
                one_time_prekey: bundle.one_time_prekey.map(|(id, pk)| crypto::OneTimePreKey {
                    id: id as u32,
                    public_key: pk,
                }),
                kyber_prekey: crypto::prekeys::KyberPreKey {
                    id: bundle.kyber_prekey_id as u32,
                    public_key: bundle.kyber_prekey_public,
                    signature: bundle.kyber_prekey_signature,
                },
            };

            session::initiate_session(
                &mut self.store,
                &self.local_address,
                &recipient_addr,
                &recipient_bundle,
            ).await?;
        }

        let encrypted = session::encrypt(
            &mut self.store,
            &self.local_address,
            &recipient_addr,
            plaintext,
        ).await?;

        Ok(OutboundMessage {
            recipient_did: recipient_did.to_string(),
            recipient_device_id: recipient_device_id as i32,
            ciphertext: encrypted.ciphertext,
            message_kind: match encrypted.kind {
                MessageKind::PreKey => 0,
                MessageKind::Whisper => 1,
            },
            expiry_secs,
        })
    }

    async fn receive_messages(&mut self) -> Result<Vec<DecryptedMessage>, AppError> {
        let inbound = self.client.fetch_messages().await?;
        let mut decrypted = Vec::with_capacity(inbound.len());

        for msg in &inbound {
            let raw = self.decrypt_inbound(msg).await?;
            // Parse envelope: unwrap content, skip receipts (handled internally).
            match ContentMessage::decode(raw.plaintext.as_slice()) {
                Ok(content) => {
                    if !content.profile_key.is_empty() {
                        // Note that this will block on network if we have not already downloaded the contact's profile blob
                        self.handle_inbound_profile_key(&raw.sender_did, &content.profile_key).await;
                    }
                    match content.body {
                    Some(Body::Receipt(receipt)) => {
                        let status: u8 = if receipt.r#type == receipt_message::Type::Read as i32 { 3 } else { 2 };
                        let timestamps: Vec<i64> = receipt.timestamps.into_iter().map(|t| t as i64).collect();
                        if !timestamps.is_empty() {
                            let conv_id = format!("dm-{}-{}", self.did, raw.sender_did);
                            let _ = self.store.update_delivery_status(&conv_id, &timestamps, status).await;
                        }
                    }
                    Some(Body::Text(text)) => {
                        let body = text.body;
                        let sent_at = if content.timestamp_ms > 0 { Some(content.timestamp_ms as i64) } else { None };
                        // Auto-send delivery receipt.
                        if let Some(ts) = sent_at {
                            let profile_key = self.own_profile_key().await;
                            let delivery = ContentMessage {
                                body: Some(Body::Receipt(ReceiptMessage {
                                    r#type: receipt_message::Type::Delivery as i32,
                                    timestamps: vec![ts as u64],
                                })),
                                timestamp_ms: 0,
                                profile_key,
                            };
                            let _ = self.send_dm(
                                &raw.sender_did,
                                &delivery.encode_to_vec(),
                                None,
                            ).await;
                        }
                        decrypted.push(DecryptedMessage { plaintext: body.into_bytes(), sent_at_ms: sent_at, ..raw });
                    }
                    None => {
                        // ContentMessage with no body — backward compat.
                        decrypted.push(raw);
                    }
                    }
                }
                Err(_) => {
                    // Not valid protobuf — backward compat: raw plaintext.
                    decrypted.push(raw);
                }
            }
        }

        if !inbound.is_empty() {
            let ids: Vec<i64> = inbound.iter().map(|m| m.id).collect();
            self.client.ack_messages(&ids).await?;
        }

        Ok(decrypted)
    }

    async fn decrypt_inbound(
        &mut self,
        msg: &net::types::InboundMessage,
    ) -> Result<DecryptedMessage, AppError> {
        let sender_did = msg.sender_did.as_deref()
            .ok_or_else(|| AppError::Protocol("message missing sender_did".into()))?;
        let sender_device_id = msg.sender_device_id
            .ok_or_else(|| AppError::Protocol("message missing sender_device_id".into()))? as u32;

        let sender_addr = DeviceAddress::new(
            AccountId::new(sender_did),
            DeviceId::new(sender_device_id),
        );

        let encrypted = EncryptedMessage {
            ciphertext: msg.ciphertext.clone(),
            kind: if msg.message_kind == 0 { MessageKind::PreKey } else { MessageKind::Whisper },
        };

        let plaintext = session::decrypt(
            &mut self.store,
            &self.local_address,
            &sender_addr,
            &encrypted,
        ).await?;

        Ok(DecryptedMessage {
            server_id: msg.id,
            sender_did: sender_did.to_string(),
            sender_device_id,
            plaintext,
            sent_at_ms: None,
        })
    }
}
