//! Per-group symmetric key material.
//!
//! Wraps libsignal's `GroupMasterKey` / `GroupSecretParams` /
//! `GroupPublicParams`. The master key is the long-term group secret: it is
//! generated by the founder, shared E2E with members at invite time, and
//! used to derive everything else (group identifier, blob encryption key,
//! member-id encryption key). See `docs/03-groups.md` §2.4.
//!
//! What this module currently exposes:
//! - [`GroupKey::generate`] / [`GroupKey::from_bytes`] / [`GroupKey::to_bytes`]
//! - [`GroupKey::group_id`] — the server-visible routing identifier.
//! - [`GroupKey::encrypt_state`] / [`GroupKey::decrypt_state`] — opaque-to-
//!   server group state blob (Signal's "encrypted group" blob, AES-256-GCM-
//!   SIV under the master key).
//!
//! What it does **not** yet expose: `encrypt_member` / `decrypt_member`.
//! Those are deferred until the `AuthCredentialDid` work (§2.3) settles the
//! DID-to-curve-point encoding — the member-id ciphertext and the
//! credential's identity attribute must use the same representation, so
//! implementing them in isolation would risk locking in a wire format we
//! then have to change.

use curve25519_dalek::ristretto::RistrettoPoint;
use poksho::{ShoApi, ShoHmacSha256};
use rand::TryRngCore;
use zkcredential::attributes::{Domain, KeyPair, PublicKey, derive_default_generator_points};

use crate::error::CryptoError;

/// Encryption domain for `DidStruct`-shaped attributes (the DID-bound member
/// id). Distinct from libsignal's `UidEncryptionDomain` so that ciphertexts
/// for the two attribute types can't be statically confused; the derived key
/// is also distinct, since they use different SHO labels.
///
/// `type Attribute` is set to `[RistrettoPoint; 2]` (the raw shape) rather
/// than `DidStruct` directly, because the latter lives in
/// `crypto::groups::credentials` and the `Domain` trait is implemented here
/// in `group_key`. `DidStruct` impls `Attribute` so it can be encrypted with
/// a `KeyPair<DidEncryptionDomain>` despite the type mismatch.
pub struct DidEncryptionDomain;

impl Domain for DidEncryptionDomain {
    type Attribute = [RistrettoPoint; 2];

    const ID: &'static str = "Actnet_ZKGroup_20260531_DidEncryption";

    #[allow(non_snake_case)]
    fn G_a() -> [RistrettoPoint; 2] {
        static STORAGE: std::sync::OnceLock<[RistrettoPoint; 2]> = std::sync::OnceLock::new();
        *derive_default_generator_points::<Self>(&STORAGE)
    }
}

pub type DidEncryptionKeyPair = KeyPair<DidEncryptionDomain>;
pub type DidEncryptionPublicKey = PublicKey<DidEncryptionDomain>;

/// Server-visible group routing identifier. Derived deterministically from
/// the master key; safe to expose because it leaks neither the key nor
/// membership.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct GroupId(pub [u8; 32]);

/// Wraps `GroupMasterKey` + the derived `GroupSecretParams`. Cloning is
/// cheap (the inner types are small). Equality is byte-equality on the
/// master key.
#[derive(Clone)]
pub struct GroupKey {
    bytes: [u8; zkgroup::GROUP_MASTER_KEY_LEN],
    secret: zkgroup::groups::GroupSecretParams,
    did_enc_key_pair: DidEncryptionKeyPair,
}

fn derive_did_key(master: &[u8; zkgroup::GROUP_MASTER_KEY_LEN]) -> DidEncryptionKeyPair {
    let mut sho = ShoHmacSha256::new(b"Actnet_ZKGroup_20260531_DidEncKey_DeriveFromMasterKey");
    sho.absorb_and_ratchet(master);
    KeyPair::<DidEncryptionDomain>::derive_from(&mut sho)
}

impl GroupKey {
    pub fn generate() -> Self {
        let mut bytes = [0u8; zkgroup::GROUP_MASTER_KEY_LEN];
        rand::rngs::OsRng
            .try_fill_bytes(&mut bytes)
            .expect("OS RNG failed");
        Self::from_bytes(bytes)
    }

    pub fn from_bytes(bytes: [u8; zkgroup::GROUP_MASTER_KEY_LEN]) -> Self {
        let master = zkgroup::groups::GroupMasterKey::new(bytes);
        let secret = zkgroup::groups::GroupSecretParams::derive_from_master_key(master);
        let did_enc_key_pair = derive_did_key(&bytes);
        Self {
            bytes,
            secret,
            did_enc_key_pair,
        }
    }

    pub fn to_bytes(&self) -> [u8; zkgroup::GROUP_MASTER_KEY_LEN] {
        self.bytes
    }

    pub fn group_id(&self) -> GroupId {
        GroupId(self.secret.get_group_identifier())
    }

    /// Encrypt the group's state blob. Uses fresh randomness from the OS RNG
    /// per call. Output is opaque to the server.
    ///
    /// Padding is *not* applied here — callers that want to hide length
    /// information should pad before calling (see Signal's pattern of
    /// rounding to fixed-size buckets in the encrypted state blob).
    pub fn encrypt_state(&self, plaintext: &[u8]) -> Vec<u8> {
        let mut randomness = [0u8; zkgroup::RANDOMNESS_LEN];
        rand::rngs::OsRng
            .try_fill_bytes(&mut randomness)
            .expect("OS RNG failed");
        self.secret.encrypt_blob(randomness, plaintext)
    }

    pub fn decrypt_state(&self, ciphertext: &[u8]) -> Result<Vec<u8>, CryptoError> {
        self.secret
            .decrypt_blob(ciphertext)
            .map_err(|_| CryptoError::InvalidCiphertext)
    }

    /// Borrow the underlying `GroupSecretParams` for use in the credentials
    /// module (presentation generation needs it). Kept crate-private so
    /// callers outside `crypto::groups` stay scheme-agnostic.
    #[allow(dead_code)] // used by upcoming endorsement / member encryption code
    pub(crate) fn secret_params(&self) -> &zkgroup::groups::GroupSecretParams {
        &self.secret
    }

    /// The `DidEncryptionDomain` key pair derived from the master key.
    /// Used to encrypt DID-bearing attributes during credential presentation
    /// and (later) to encrypt member ids server-side.
    pub(crate) fn did_enc_key_pair(&self) -> &DidEncryptionKeyPair {
        &self.did_enc_key_pair
    }

    /// Bundle of the public values the server needs in order to verify
    /// presentations against this group. Uploaded by the founder at
    /// create-group time and stored server-side (see §3.2's
    /// `group_public_params` column).
    pub fn public_params(&self) -> GroupPublicParams {
        GroupPublicParams {
            group_id: self.group_id(),
            did_enc_public_key: self.did_enc_key_pair.public_key,
        }
    }
}

/// Server-visible public material for a group. Contains the routing
/// `group_id` and the public half of the DID encryption key — everything
/// needed to verify an `AuthCredentialDidPresentation` without learning any
/// member's identity.
#[derive(Clone)]
pub struct GroupPublicParams {
    group_id: GroupId,
    did_enc_public_key: DidEncryptionPublicKey,
}

impl GroupPublicParams {
    pub fn group_id(&self) -> GroupId {
        self.group_id
    }

    pub(crate) fn did_enc_public_key(&self) -> &DidEncryptionPublicKey {
        &self.did_enc_public_key
    }

    /// Encode for the wire — clients upload this at create-group time and
    /// the server stores the bytes verbatim. Stable for a given pinned
    /// libsignal commit.
    pub fn to_bytes(&self) -> Vec<u8> {
        let wire = GroupPublicParamsWire {
            group_id: self.group_id.0,
            did_enc_public_key: bincode::serialize(&self.did_enc_public_key)
                .expect("serialize DidEncryptionPublicKey"),
        };
        bincode::serialize(&wire).expect("serialize GroupPublicParamsWire")
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, CryptoError> {
        let wire: GroupPublicParamsWire =
            bincode::deserialize(bytes).map_err(|_| CryptoError::ZkgroupDeserialize)?;
        let did_enc_public_key = bincode::deserialize(&wire.did_enc_public_key)
            .map_err(|_| CryptoError::ZkgroupDeserialize)?;
        Ok(Self {
            group_id: GroupId(wire.group_id),
            did_enc_public_key,
        })
    }
}

#[derive(serde::Serialize, serde::Deserialize)]
struct GroupPublicParamsWire {
    group_id: [u8; 32],
    did_enc_public_key: Vec<u8>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_roundtrips_through_bytes() {
        let key = GroupKey::generate();
        let bytes = key.to_bytes();
        let again = GroupKey::from_bytes(bytes);
        assert_eq!(again.to_bytes(), bytes);
        assert_eq!(again.group_id(), key.group_id());
    }

    #[test]
    fn different_keys_yield_different_group_ids() {
        let a = GroupKey::generate();
        let b = GroupKey::generate();
        assert_ne!(a.to_bytes(), b.to_bytes());
        assert_ne!(a.group_id(), b.group_id());
    }

    #[test]
    fn state_roundtrip_with_padding_extremes() {
        let key = GroupKey::generate();
        for plaintext in [b"".as_ref(), b"x", &[0u8; 16][..], &vec![0xAB; 4096][..]] {
            let ct = key.encrypt_state(plaintext);
            assert_ne!(ct, plaintext, "ciphertext must differ from plaintext");
            let pt = key.decrypt_state(&ct).expect("decrypt");
            assert_eq!(pt, plaintext);
        }
    }

    #[test]
    fn state_decrypt_rejects_wrong_key() {
        let a = GroupKey::generate();
        let b = GroupKey::generate();
        let ct = a.encrypt_state(b"secret group state");
        assert!(b.decrypt_state(&ct).is_err());
    }

    #[test]
    fn state_decrypt_rejects_tampered_ciphertext() {
        let key = GroupKey::generate();
        let mut ct = key.encrypt_state(b"hello");
        // Flip a bit in the first byte; AEAD must reject.
        ct[0] ^= 0x01;
        assert!(key.decrypt_state(&ct).is_err());
    }

    #[test]
    fn encrypt_is_nondeterministic() {
        let key = GroupKey::generate();
        let a = key.encrypt_state(b"same plaintext");
        let b = key.encrypt_state(b"same plaintext");
        assert_ne!(a, b, "fresh randomness should yield distinct ciphertexts");
    }
}
