//! Per-group symmetric key material.
//!
//! Thin newtype wrapper around `zkgroup::GroupSecretParams` /
//! `zkgroup::GroupPublicParams`. The master key is the long-term group
//! secret: it's generated by the founder, shared E2E with members at
//! invite time, and used to derive everything else (group identifier,
//! blob encryption key, member-id encryption key). See
//! `docs/03-groups.md` §2.3 / §2.4 for the identity-attribute history
//! (`encrypt_member_id` now uses stock `zkgroup::groups::UuidCiphertext`
//! with `Aci::from(UUID(did))` as the carried attribute).
//!
//! Surface:
//! - [`GroupKey::generate`] / [`GroupKey::from_bytes`] / [`GroupKey::to_bytes`]
//! - [`GroupKey::group_id`] — server-visible routing identifier.
//! - [`GroupKey::encrypt_state`] / [`GroupKey::decrypt_state`] — opaque-to-
//!   server group state blob (AES-256-GCM-SIV under the master key).
//! - [`GroupKey::encrypt_member_id`] — produces an `EncryptedMemberId`
//!   for an arbitrary DID, deterministic in `(did, group_key)`.
//! - [`GroupKey::public_params`] — bundle uploaded at create-group time.

use libsignal_core::Aci;
use rand::TryRngCore;
use uuid::Uuid;

use crate::error::CryptoError;

/// Server-visible group routing identifier. Derived deterministically
/// from the master key; safe to expose because it leaks neither the key
/// nor membership.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct GroupId(pub [u8; 32]);

/// Stock zkgroup ciphertext over a UUID-shaped attribute. See §2.3 for
/// why the carried attribute is `Aci::from(UUID(did))`.
pub type EncryptedMemberId = zkgroup::groups::UuidCiphertext;

/// Wraps `zkgroup::GroupSecretParams`. Cloning is cheap.
#[derive(Clone)]
pub struct GroupKey {
    bytes: [u8; zkgroup::GROUP_MASTER_KEY_LEN],
    secret: zkgroup::groups::GroupSecretParams,
}

impl GroupKey {
    pub fn generate() -> Self {
        let mut bytes = [0u8; zkgroup::GROUP_MASTER_KEY_LEN];
        rand::rngs::OsRng
            .try_fill_bytes(&mut bytes)
            .expect("OS RNG failed");
        Self::from_bytes(bytes)
    }

    pub fn from_bytes(bytes: [u8; zkgroup::GROUP_MASTER_KEY_LEN]) -> Self {
        let master = zkgroup::groups::GroupMasterKey::new(bytes);
        let secret = zkgroup::groups::GroupSecretParams::derive_from_master_key(master);
        Self { bytes, secret }
    }

    pub fn to_bytes(&self) -> [u8; zkgroup::GROUP_MASTER_KEY_LEN] {
        self.bytes
    }

    pub fn group_id(&self) -> GroupId {
        GroupId(self.secret.get_group_identifier())
    }

    /// Encrypt the group's state blob. Uses fresh randomness from the OS
    /// RNG per call. Output is opaque to the server.
    ///
    /// Padding is *not* applied here — callers that want to hide length
    /// information should pad before calling.
    pub fn encrypt_state(&self, plaintext: &[u8]) -> Vec<u8> {
        let mut randomness = [0u8; zkgroup::RANDOMNESS_LEN];
        rand::rngs::OsRng
            .try_fill_bytes(&mut randomness)
            .expect("OS RNG failed");
        self.secret.encrypt_blob(randomness, plaintext)
    }

    pub fn decrypt_state(&self, ciphertext: &[u8]) -> Result<Vec<u8>, CryptoError> {
        self.secret
            .decrypt_blob(ciphertext)
            .map_err(|_| CryptoError::InvalidCiphertext)
    }

    /// Compute the `EncryptedMemberId` for an arbitrary DID under this
    /// group key. Deterministic in `(did, group_key)`, so the same DID
    /// always produces the same ciphertext within a group — which is
    /// what makes server-side `member_credentials` lookups by EMI work.
    /// Different groups produce different ciphertexts because the
    /// per-group encryption key differs.
    pub fn encrypt_member_id(&self, did: &str) -> EncryptedMemberId {
        let aci = Aci::from(did_to_uuid(did));
        self.secret.encrypt_service_id(aci.into())
    }

    /// Borrow the underlying `GroupSecretParams`. Used by
    /// `AuthCredentialWithPniZkc::present` and (Stage 6 PR 2)
    /// `GroupSendEndorsementsResponse::receive_with_*`.
    pub fn zkgroup_secret(&self) -> &zkgroup::groups::GroupSecretParams {
        &self.secret
    }

    /// Bundle of the public values the server needs in order to verify
    /// presentations against this group. Uploaded by the founder at
    /// create-group time and stored server-side.
    pub fn public_params(&self) -> GroupPublicParams {
        GroupPublicParams {
            inner: self.secret.get_public_params(),
        }
    }
}

/// Derive the UUID we feed into zkgroup as the identity attribute for a
/// given DID. `UUID(did) := SHA-256(b"actnet-did-to-uuid-v1" || did)[..16]`.
/// All clients and the server agree on this derivation, so encrypting
/// the same DID under the same group key always produces the same
/// `EncryptedMemberId`. See `docs/03-groups.md` §2.3.
pub fn did_to_uuid(did: &str) -> Uuid {
    use sha2::{Digest as _, Sha256};
    const DOMAIN: &[u8] = b"actnet-did-to-uuid-v1";
    let mut hasher = Sha256::new();
    hasher.update(DOMAIN);
    hasher.update(did.as_bytes());
    let digest = hasher.finalize();
    let mut bytes = [0u8; 16];
    bytes.copy_from_slice(&digest[..16]);
    Uuid::from_bytes(bytes)
}

/// Server-visible public material for a group. Contains the routing
/// `group_id` and the public material needed to verify a presentation —
/// everything stock zkgroup needs, nothing identity-bearing.
#[derive(Clone)]
pub struct GroupPublicParams {
    inner: zkgroup::groups::GroupPublicParams,
}

impl GroupPublicParams {
    pub fn group_id(&self) -> GroupId {
        GroupId(self.inner.get_group_identifier())
    }

    /// Borrow the underlying zkgroup public params. Used by server-side
    /// presentation verification.
    pub fn zkgroup(&self) -> &zkgroup::groups::GroupPublicParams {
        &self.inner
    }

    /// Encode for the wire — clients upload this at create-group time
    /// and the server stores the bytes verbatim.
    pub fn to_bytes(&self) -> Vec<u8> {
        zkgroup::serialize(&self.inner)
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, CryptoError> {
        let inner = zkgroup::deserialize::<zkgroup::groups::GroupPublicParams>(bytes)
            .map_err(|_| CryptoError::ZkgroupDeserialize)?;
        Ok(Self { inner })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_roundtrips_through_bytes() {
        let key = GroupKey::generate();
        let bytes = key.to_bytes();
        let again = GroupKey::from_bytes(bytes);
        assert_eq!(again.to_bytes(), bytes);
        assert_eq!(again.group_id(), key.group_id());
    }

    #[test]
    fn different_keys_yield_different_group_ids() {
        let a = GroupKey::generate();
        let b = GroupKey::generate();
        assert_ne!(a.to_bytes(), b.to_bytes());
        assert_ne!(a.group_id(), b.group_id());
    }

    #[test]
    fn state_roundtrip_with_padding_extremes() {
        let key = GroupKey::generate();
        for plaintext in [b"".as_ref(), b"x", &[0u8; 16][..], &vec![0xAB; 4096][..]] {
            let ct = key.encrypt_state(plaintext);
            assert_ne!(ct, plaintext, "ciphertext must differ from plaintext");
            let pt = key.decrypt_state(&ct).expect("decrypt");
            assert_eq!(pt, plaintext);
        }
    }

    #[test]
    fn state_decrypt_rejects_wrong_key() {
        let a = GroupKey::generate();
        let b = GroupKey::generate();
        let ct = a.encrypt_state(b"secret group state");
        assert!(b.decrypt_state(&ct).is_err());
    }

    #[test]
    fn state_decrypt_rejects_tampered_ciphertext() {
        let key = GroupKey::generate();
        let mut ct = key.encrypt_state(b"hello");
        ct[0] ^= 0x01;
        assert!(key.decrypt_state(&ct).is_err());
    }

    #[test]
    fn encrypt_is_nondeterministic() {
        let key = GroupKey::generate();
        let a = key.encrypt_state(b"same plaintext");
        let b = key.encrypt_state(b"same plaintext");
        assert_ne!(a, b);
    }

    #[test]
    fn did_to_uuid_is_deterministic_and_domain_separated() {
        let a = did_to_uuid("did:plc:alice");
        let b = did_to_uuid("did:plc:alice");
        let c = did_to_uuid("did:plc:bob");
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn encrypt_member_id_deterministic_per_did_and_group() {
        let key = GroupKey::generate();
        let a = key.encrypt_member_id("did:plc:alice");
        let b = key.encrypt_member_id("did:plc:alice");
        let c = key.encrypt_member_id("did:plc:bob");
        let a_bytes = zkgroup::serialize(&a);
        let b_bytes = zkgroup::serialize(&b);
        let c_bytes = zkgroup::serialize(&c);
        assert_eq!(a_bytes, b_bytes);
        assert_ne!(a_bytes, c_bytes);
    }

    #[test]
    fn encrypt_member_id_differs_across_groups() {
        let g1 = GroupKey::generate();
        let g2 = GroupKey::generate();
        let a1 = g1.encrypt_member_id("did:plc:alice");
        let a2 = g2.encrypt_member_id("did:plc:alice");
        assert_ne!(zkgroup::serialize(&a1), zkgroup::serialize(&a2));
    }
}
