plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "net.theavalanche.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "net.theavalanche.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        // Ship only the ABIs we cross-compile libapp_core.so for (see ANDROID_ABIS
        // in the Makefile). Without this, JNA's @aar drags in libjnidispatch.so for
        // armeabi/mips/x86 too, and a device on one of those ABIs would load JNA but
        // find no libapp_core.so and crash at startup.
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }

    // UniFFI-generated Kotlin glue lives outside src/ (it's a build artifact,
    // regenerated by `make android-bindings`). The matching native libraries are
    // cross-compiled into src/main/jniLibs/<abi>/libapp_core.so, which AGP picks
    // up automatically.
    sourceSets {
        getByName("main") {
            java.srcDir("${rootProject.projectDir}/Generated")
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    // Navigation
    implementation(libs.androidx.navigation.compose)

    // Coroutines
    implementation(libs.kotlinx.coroutines.android)

    // JSON persistence (SharedPreferences-backed metadata; mirrors iOS Codable)
    implementation(libs.kotlinx.serialization.json)

    // Rust core via UniFFI. The generated Kotlin binding (uniffi.app_core) calls
    // into libapp_core.so through JNA, which must be the @aar artifact so JNA's
    // own native dispatch library is bundled for Android.
    implementation(libs.jna) { artifact { type = "aar" } }

    // QR scanning for onboarding (CameraX + ZXing; ZXing avoids Google Play Services
    // so the app works on de-Googled Android)
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    implementation(libs.zxing.android.embedded)

    testImplementation(libs.junit)
    debugImplementation(libs.androidx.compose.ui.tooling)
}