// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	createAccount: (serverUrl: string, dbPath: string, dbKey: string, prfOutput: number[], displayName: string, inviteToken: string | null) => typedError<AccountResult, string>(__TAURI_INVOKE("create_account", { serverUrl, dbPath, dbKey, prfOutput, displayName, inviteToken })),
	login: (dbPath: string, dbKey: string) => typedError<AccountResult, string>(__TAURI_INVOKE("login", { dbPath, dbKey })),
	recoverFromBlob: (serverUrl: string, did: string, prfOutput: number[], dbPath: string, dbKey: string, displayName: string) => typedError<AccountResult, string>(__TAURI_INVOKE("recover_from_blob", { serverUrl, did, prfOutput, dbPath, dbKey, displayName })),
	sendDm: (recipientDid: string, plaintext: number[], sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_dm", { recipientDid, plaintext, sentAtMs })),
	sendGroupMessage: (groupId: string, plaintext: number[], sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_group_message", { groupId, plaintext, sentAtMs })),
	receiveMessages: () => typedError<DecryptedMessage[], string>(__TAURI_INVOKE("receive_messages")),
	nextEvents: () => typedError<IncomingEvent[], string>(__TAURI_INVOKE("next_events")),
	saveMessage: (msg: StoredMessageFfi) => typedError<null, string>(__TAURI_INVOKE("save_message", { msg })),
	loadConversations: () => typedError<ConversationSummaryFfi[], string>(__TAURI_INVOKE("load_conversations")),
	loadMessages: (conversationId: string) => typedError<StoredMessageFfi[], string>(__TAURI_INVOKE("load_messages", { conversationId })),
	markMessagesRead: (conversationId: string, upToSentAtMs: number) => typedError<number, string>(__TAURI_INVOKE("mark_messages_read", { conversationId, upToSentAtMs })),
	unreadCount: (conversationId: string) => typedError<number, string>(__TAURI_INVOKE("unread_count", { conversationId })),
	did: () => typedError<string, string>(__TAURI_INVOKE("did")),
	deviceId: () => typedError<number, string>(__TAURI_INVOKE("device_id")),
	ownDisplayName: () => typedError<string, string>(__TAURI_INVOKE("own_display_name")),
	setDisplayName: (displayName: string) => typedError<null, string>(__TAURI_INVOKE("set_display_name", { displayName })),
	hasRecovery: () => typedError<boolean, string>(__TAURI_INVOKE("has_recovery")),
	contactDisplayName: (did: string) => typedError<string, string>(__TAURI_INVOKE("contact_display_name", { did })),
	getAccountInfo: (did: string) => typedError<AccountInfoFfi, string>(__TAURI_INVOKE("get_account_info", { did })),
	refreshContactProfile: (did: string) => typedError<boolean, string>(__TAURI_INVOKE("refresh_contact_profile", { did })),
	listContacts: () => typedError<ContactRowFfi[], string>(__TAURI_INVOKE("list_contacts")),
	touchContact: (did: string, curated: boolean) => typedError<null, string>(__TAURI_INVOKE("touch_contact", { did, curated })),
	fetchAndCacheProfile: (did: string, profileKey: number[]) => typedError<null, string>(__TAURI_INVOKE("fetch_and_cache_profile", { did, profileKey })),
	primeContactProfile: (did: string, displayName: string, profileKey: number[]) => typedError<null, string>(__TAURI_INVOKE("prime_contact_profile", { did, displayName, profileKey })),
	blockContact: (did: string) => typedError<null, string>(__TAURI_INVOKE("block_contact", { did })),
	unblockContact: (did: string) => typedError<null, string>(__TAURI_INVOKE("unblock_contact", { did })),
	leaveServer: () => typedError<null, string>(__TAURI_INVOKE("leave_server")),
	deleteIdentity: () => typedError<null, string>(__TAURI_INVOKE("delete_identity")),
	fetchProjects: () => typedError<ProjectInfoFfi[], string>(__TAURI_INVOKE("fetch_projects")),
	requestProjectToken: (projectUrl: string) => typedError<string, string>(__TAURI_INVOKE("request_project_token", { projectUrl })),
	validateInvite: (token: string) => typedError<InviteInfo, string>(__TAURI_INVOKE("validate_invite", { token })),
	connectionState: () => typedError<ConnectionState, string>(__TAURI_INVOKE("connection_state")),
	waitForConnectionStateChange: (last: ConnectionState) => typedError<ConnectionState, string>(__TAURI_INVOKE("wait_for_connection_state_change", { last })),
	createGroup: (title: string, description: string, expirySeconds: number) => typedError<CreatedGroupFfi, string>(__TAURI_INVOKE("create_group", { title, description, expirySeconds })),
	fetchGroupState: (groupId: string) => typedError<GroupSummaryFfi, string>(__TAURI_INVOKE("fetch_group_state", { groupId })),
	cachedGroupState: (groupId: string) => typedError<{
	groupId: string,
	masterKey: number[],
	revision: number,
	title: string,
	description: string,
	expirySeconds: number,
	members: GroupMemberFfi[],
	pendingInvites: GroupPendingFfi[],
	pendingApprovals: GroupPendingFfi[],
} | null, string>(__TAURI_INVOKE("cached_group_state", { groupId })),
	inviteMember: (groupId: string, recipientDid: string, role: number) => typedError<null, string>(__TAURI_INVOKE("invite_member", { groupId, recipientDid, role })),
	acceptInvite: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("accept_invite", { groupId })),
	declineInvite: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("decline_invite", { groupId })),
	cancelJoinRequest: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_join_request", { groupId })),
	approveJoinRequest: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("approve_join_request", { groupId, encryptedMemberId })),
	denyJoinRequest: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("deny_join_request", { groupId, encryptedMemberId })),
	removeMember: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("remove_member", { groupId, encryptedMemberId })),
	leaveGroup: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("leave_group", { groupId })),
	isGroupMember: (groupId: string) => typedError<boolean, string>(__TAURI_INVOKE("is_group_member", { groupId })),
	changeMemberRole: (groupId: string, encryptedMemberId: string, newRole: number) => typedError<null, string>(__TAURI_INVOKE("change_member_role", { groupId, encryptedMemberId, newRole })),
	setGroupExpiry: (groupId: string, expirySeconds: number) => typedError<null, string>(__TAURI_INVOKE("set_group_expiry", { groupId, expirySeconds })),
	setGroupTitle: (groupId: string, newTitle: string) => typedError<null, string>(__TAURI_INVOKE("set_group_title", { groupId, newTitle })),
	groupExpirySeconds: (groupId: string) => typedError<number, string>(__TAURI_INVOKE("group_expiry_seconds", { groupId })),
	applyPendingGroupChanges: (groupId: string) => typedError<number, string>(__TAURI_INVOKE("apply_pending_group_changes", { groupId })),
	listGroups: () => typedError<string[], string>(__TAURI_INVOKE("list_groups")),
	sendReaction: (target: MessageTarget, targetAuthor: string, targetSentAtMs: number, emoji: string, remove: boolean, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_reaction", { target, targetAuthor, targetSentAtMs, emoji, remove, sentAtMs })),
	sendEdit: (target: MessageTarget, targetSentAtMs: number, newBody: string, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_edit", { target, targetSentAtMs, newBody, sentAtMs })),
	sendDelete: (target: MessageTarget, targetAuthor: string, targetSentAtMs: number, forEveryone: boolean, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_delete", { target, targetAuthor, targetSentAtMs, forEveryone, sentAtMs })),
	loadReactions: (conversationId: string) => typedError<ReactionFfi[], string>(__TAURI_INVOKE("load_reactions", { conversationId })),
	loadMessageRevisions: (conversationId: string, author: string, sentAtMs: number) => typedError<MessageRevisionFfi[], string>(__TAURI_INVOKE("load_message_revisions", { conversationId, author, sentAtMs })),
};

/* Types */
/**  Public metadata for an account. Mirrors app-core `AccountInfoFfi`. */
export type AccountInfoFfi = {
	did: string,
	displayName: string | null,
	isBot: boolean,
};

/**
 *  Result returned by account-factory commands (`create_account`, `login`,
 *  `recover_from_blob`). Desktop-specific convenience type — app-core returns
 *  `Arc<AppCore>` from these constructors; we extract the fields the UI needs.
 */
export type AccountResult = {
	did: string,
	displayName: string,
};

/**
 *  Liveness of the connection to the homeserver. Mirrors app-core
 *  `ConnectionState`.
 */
export type ConnectionState = { type: "disconnected" } | { type: "connecting" } | { type: "connected" } | {
	type: "reconnecting",
} & ReconnectingState;

/**  Minimal contact-list row. Mirrors app-core `ContactRowFfi`. */
export type ContactRowFfi = {
	did: string,
	displayName: string,
	isCurated: boolean,
	lastInteractionAtMs: number,
};

/**
 *  A conversation summary for the chat list. Mirrors app-core
 *  `ConversationSummaryFfi`.
 */
export type ConversationSummaryFfi = {
	conversationId: string,
	groupTitle: string | null,
	lastMessage: StoredMessageFfi | null,
	isRequest: boolean,
	isBlocked: boolean,
};

/**  Result of `create_group`. Mirrors app-core `CreatedGroupFfi`. */
export type CreatedGroupFfi = {
	groupId: string,
	masterKey: number[],
};

/**  A decrypted inbound message (mirrors app-core `DecryptedMessage`). */
export type DecryptedMessage = {
	serverId: number,
	senderDid: string,
	senderDeviceId: number,
	plaintext: number[],
	sentAtMs: number | null,
	groupId: string | null,
	expireTimerSecs: number,
	profileKey: number[] | null,
	isRequest: boolean,
};

/**
 *  A delivery-status update for an outgoing message (e.g. read receipt).
 *  Mirrors app-core `DeliveryStatusUpdate`.
 */
export type DeliveryStatusUpdate = {
	conversationId: string,
	sentAtMs: number,
	deliveryStatus: number,
};

export type DmTarget = {
	recipientDid: string,
};

/**
 *  Membership/metadata change kind for group timeline entries.
 *  Mirrors app-core `GroupEventKind`.
 */
export type GroupEventKind = "memberJoined" | "memberJoinedViaLink" | "memberRequestedToJoin" | "memberInvited" | "memberLeft" | "memberRemoved" | "joinRequestApproved" | "joinRequestDenied" | "inviteDeclined" | "joinRequestCancelled" | "roleChangedToAdmin" | "roleChangedToMember" | "titleChanged" | "descriptionChanged" | "expiryChanged" | "policyChanged";

export type GroupInviteEvent = {
	groupId: string,
	hostingServerUrl: string,
	inviterDid: string,
};

/**  A member's row in a group. Mirrors app-core `GroupMemberFfi`. */
export type GroupMemberFfi = {
	did: string,
	encryptedMemberId: string,
	role: number,
	joinedAtMs: number,
};

export type GroupMetadataChangedEvent = {
	event: GroupMetadataEvent,
};

/**
 *  One derived chat-timeline entry describing a membership/metadata change.
 *  Mirrors app-core `GroupMetadataEvent`.
 */
export type GroupMetadataEvent = {
	groupId: string,
	revision: number,
	kind: GroupEventKind,
	actorDid: string,
	targetDid: string,
	targetEmi: string,
	occurredAtMs: number,
	expirySeconds: number,
	newTitle: string,
	summary: string,
};

/**  A pending invite or approval entry. Mirrors app-core `GroupPendingFfi`. */
export type GroupPendingFfi = {
	encryptedMemberId: string,
	timestampMs: number,
};

/**  Snapshot of a group's decrypted state. Mirrors app-core `GroupSummaryFfi`. */
export type GroupSummaryFfi = {
	groupId: string,
	masterKey: number[],
	revision: number,
	title: string,
	description: string,
	expirySeconds: number,
	members: GroupMemberFfi[],
	pendingInvites: GroupPendingFfi[],
	pendingApprovals: GroupPendingFfi[],
};

export type GroupTarget = {
	groupId: string,
};

/**
 *  A single event surfaced to the FFI from the background reconnect task.
 *  Mirrors app-core `IncomingEvent`.
 */
export type IncomingEvent = {
	type: "message",
} & MessageEvent | {
	type: "receiptUpdate",
} & ReceiptUpdateEvent | {
	type: "groupInvite",
} & GroupInviteEvent | {
	type: "messageEdited",
} & MessageEditedEvent | {
	type: "messageDeleted",
} & MessageDeletedEvent | {
	type: "reactionUpdated",
} & ReactionUpdatedEvent | { type: "storageSynced" } | {
	type: "groupMetadataChanged",
} & GroupMetadataChangedEvent | {
	type: "messagesExpired",
} & MessagesExpiredEvent;

/**  Decoded invite token info. Mirrors app-core `InviteInfo`. */
export type InviteInfo = {
	serverUrl: string,
	serverName: string,
	inviterDid: string | null,
	postOnboardingRedirect: string | null,
	inviterDisplayName: string | null,
	inviterProfileKey: number[] | null,
};

export type MessageDeletedEvent = {
	conversationId: string,
	authorDid: string,
	sentAtMs: number,
};

export type MessageEditedEvent = {
	conversationId: string,
	authorDid: string,
	sentAtMs: number,
	newBody: string,
	editedAtMs: number,
};

export type MessageEvent = {
	msg: DecryptedMessage,
};

/**  A prior body of an edited message. Mirrors app-core `MessageRevisionFfi`. */
export type MessageRevisionFfi = {
	body: string,
	replacedAtMs: number,
};

/**  Where a content operation is directed. Mirrors app-core `MessageTarget`. */
export type MessageTarget = {
	type: "dm",
} & DmTarget | {
	type: "group",
} & GroupTarget;

export type MessagesExpiredEvent = {
	conversationIds: string[],
};

/**  A first-party Project. Mirrors app-core `ProjectInfoFfi`. */
export type ProjectInfoFfi = {
	name: string,
	url: string,
	description: string,
};

/**  A reaction on a message. Mirrors app-core `ReactionFfi`. */
export type ReactionFfi = {
	conversationId: string,
	targetAuthor: string,
	targetSentAtMs: number,
	reactorDid: string,
	emoji: string,
	reactedAtMs: number,
};

export type ReactionUpdatedEvent = {
	conversationId: string,
	targetAuthor: string,
	targetSentAtMs: number,
	reactorDid: string,
	emoji: string,
	removed: boolean,
};

export type ReceiptUpdateEvent = {
	update: DeliveryStatusUpdate,
};

export type ReconnectingState = {
	nextAttemptAtMs: number,
};

/**
 *  A message from local history (persisted in SQLCipher).
 *  Mirrors app-core `StoredMessageFfi`.
 */
export type StoredMessageFfi = {
	id: string,
	conversationId: string,
	senderDid: string,
	body: string,
	sentAtMs: number,
	editedAtMs: number | null,
	readAtMs: number | null,
	deliveryStatus: number,
	editCount: number,
	deleted: boolean,
	kind: number,
	metadata: string | null,
	expireTimerSecs: number,
	expireAtMs: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

