// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	createAccount: (serverUrl: string, dbPath: string, dbKey: string, prfOutput: number[], displayName: string, inviteToken: string | null) => typedError<AccountResult, string>(__TAURI_INVOKE("create_account", { serverUrl, dbPath, dbKey, prfOutput, displayName, inviteToken })),
	login: (dbPath: string, dbKey: string) => typedError<AccountResult, string>(__TAURI_INVOKE("login", { dbPath, dbKey })),
	recoverFromBlob: (serverUrl: string, did: string, prfOutput: number[], dbPath: string, dbKey: string, displayName: string) => typedError<AccountResult, string>(__TAURI_INVOKE("recover_from_blob", { serverUrl, did, prfOutput, dbPath, dbKey, displayName })),
	sendDm: (recipientDid: string, plaintext: number[], sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_dm", { recipientDid, plaintext, sentAtMs })),
	sendGroupMessage: (groupId: string, plaintext: number[], sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_group_message", { groupId, plaintext, sentAtMs })),
	/**
	 *  Async so it runs off the main thread. `app_core.next_events()` blocks until
	 *  decrypted events arrive (WebSocket push via app-core's MPSC channel), so it
	 *  must not run on the main thread — that would freeze the WebView. We clone the
	 *  `Arc<AppCore>` out of `State` *before* awaiting (a `State` reference cannot be
	 *  held across an await point) and run the blocking call on the blocking pool.
	 */
	nextEvents: () => typedError<IncomingEvent[], string>(__TAURI_INVOKE("next_events")),
	saveMessage: (msg: StoredMessageFfi) => typedError<null, string>(__TAURI_INVOKE("save_message", { msg })),
	loadConversations: () => typedError<ConversationSummaryFfi[], string>(__TAURI_INVOKE("load_conversations")),
	loadMessages: (conversationId: string) => typedError<StoredMessageFfi[], string>(__TAURI_INVOKE("load_messages", { conversationId })),
	markMessagesRead: (conversationId: string, upToSentAtMs: number) => typedError<number, string>(__TAURI_INVOKE("mark_messages_read", { conversationId, upToSentAtMs })),
	unreadCount: (conversationId: string) => typedError<number, string>(__TAURI_INVOKE("unread_count", { conversationId })),
	did: () => typedError<string, string>(__TAURI_INVOKE("did")),
	deviceId: () => typedError<number, string>(__TAURI_INVOKE("device_id")),
	ownDisplayName: () => typedError<string, string>(__TAURI_INVOKE("own_display_name")),
	setDisplayName: (displayName: string) => typedError<null, string>(__TAURI_INVOKE("set_display_name", { displayName })),
	hasRecovery: () => typedError<boolean, string>(__TAURI_INVOKE("has_recovery")),
	/**
	 *  Re-encrypt and upload this account's recovery blob for the given PRF output
	 *  and server list. The PRF output must be exactly 32 bytes — desktop has no
	 *  passkey/PRF authenticator, so the only caller is the recovery-phrase setup
	 *  flow, which feeds the 32-byte seed derived from the phrase
	 *  (`recovery_phrase_to_seed`). See `desktop/CLAUDE.md` (passkey divergence).
	 */
	updateRecoveryBlob: (prfOutput: number[], servers: string[]) => typedError<null, string>(__TAURI_INVOKE("update_recovery_blob", { prfOutput, servers })),
	/**  This account's home (primary) server URL. */
	homeServer: () => typedError<string, string>(__TAURI_INVOKE("home_server")),
	/**
	 *  Generate a fresh 12-word BIP39 recovery phrase. Stateless — drives the
	 *  recovery-phrase *setup* flow (desktop has no passkey/PRF path).
	 */
	generateRecoveryPhrase: () => typedError<string, string>(__TAURI_INVOKE("generate_recovery_phrase")),
	/**
	 *  Validate a BIP39 recovery phrase and derive its 32-byte seed (the PRF-output
	 *  stand-in for `update_recovery_blob` / `derive_did_from_passkey`).
	 */
	recoveryPhraseToSeed: (phrase: string) => typedError<number[], string>(__TAURI_INVOKE("recovery_phrase_to_seed", { phrase })),
	/**
	 *  Recompute the DID a given seed + signup server URL would produce, without
	 *  fetching anything. The recovery-phrase restore flow needs the DID before it
	 *  can download the recovery blob (the phrase carries no DID, unlike a passkey
	 *  userHandle).
	 */
	deriveDidFromPasskey: (prfOutput: number[], signupServerUrl: string) => typedError<string, string>(__TAURI_INVOKE("derive_did_from_passkey", { prfOutput, signupServerUrl })),
	contactDisplayName: (did: string) => typedError<string, string>(__TAURI_INVOKE("contact_display_name", { did })),
	getAccountInfo: (did: string) => typedError<AccountInfoFfi, string>(__TAURI_INVOKE("get_account_info", { did })),
	refreshContactProfile: (did: string) => typedError<boolean, string>(__TAURI_INVOKE("refresh_contact_profile", { did })),
	listContacts: () => typedError<ContactRowFfi[], string>(__TAURI_INVOKE("list_contacts")),
	touchContact: (did: string, curated: boolean) => typedError<null, string>(__TAURI_INVOKE("touch_contact", { did, curated })),
	fetchAndCacheProfile: (did: string, profileKey: number[]) => typedError<null, string>(__TAURI_INVOKE("fetch_and_cache_profile", { did, profileKey })),
	primeContactProfile: (did: string, displayName: string, profileKey: number[]) => typedError<null, string>(__TAURI_INVOKE("prime_contact_profile", { did, displayName, profileKey })),
	blockContact: (did: string) => typedError<null, string>(__TAURI_INVOKE("block_contact", { did })),
	unblockContact: (did: string) => typedError<null, string>(__TAURI_INVOKE("unblock_contact", { did })),
	leaveServer: () => typedError<null, string>(__TAURI_INVOKE("leave_server")),
	deleteIdentity: () => typedError<null, string>(__TAURI_INVOKE("delete_identity")),
	/**
	 *  Drops the `Arc<AppCore>` handle so `get_app` returns "no account". Called by
	 *  the frontend on logout / mode-switch. The TS-owned polling loop has already
	 *  been stopped, so there is no background thread to cancel — this just releases
	 *  the core so the old reconnect task + WS connection die on drop.
	 */
	clearSession: () => typedError<null, string>(__TAURI_INVOKE("clear_session")),
	fetchProjects: () => typedError<ProjectInfoFfi[], string>(__TAURI_INVOKE("fetch_projects")),
	requestProjectToken: (projectUrl: string) => typedError<string, string>(__TAURI_INVOKE("request_project_token", { projectUrl })),
	validateInvite: (token: string) => typedError<InviteInfo, string>(__TAURI_INVOKE("validate_invite", { token })),
	connectionState: () => typedError<ConnectionState, string>(__TAURI_INVOKE("connection_state")),
	/**
	 *  Async + `spawn_blocking` for the same reason as `next_events`: this parks on
	 *  `ffi_runtime().block_on(rx.changed().await)` until the connection state
	 *  changes, so it must not run on the main thread or it freezes the WebView.
	 *  `startConnectionLoop` long-polls this concurrently with the event loop.
	 */
	waitForConnectionStateChange: (last: ConnectionState) => typedError<ConnectionState, string>(__TAURI_INVOKE("wait_for_connection_state_change", { last })),
	createGroup: (title: string, description: string, expirySeconds: number) => typedError<CreatedGroupFfi, string>(__TAURI_INVOKE("create_group", { title, description, expirySeconds })),
	fetchGroupState: (groupId: string) => typedError<GroupSummaryFfi, string>(__TAURI_INVOKE("fetch_group_state", { groupId })),
	cachedGroupState: (groupId: string) => typedError<{
	groupId: string,
	masterKey: number[],
	revision: number,
	title: string,
	description: string,
	expirySeconds: number,
	members: GroupMemberFfi[],
	pendingInvites: GroupPendingFfi[],
	pendingApprovals: GroupPendingFfi[],
} | null, string>(__TAURI_INVOKE("cached_group_state", { groupId })),
	inviteMember: (groupId: string, recipientDid: string, role: number) => typedError<null, string>(__TAURI_INVOKE("invite_member", { groupId, recipientDid, role })),
	acceptInvite: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("accept_invite", { groupId })),
	declineInvite: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("decline_invite", { groupId })),
	cancelJoinRequest: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_join_request", { groupId })),
	approveJoinRequest: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("approve_join_request", { groupId, encryptedMemberId })),
	denyJoinRequest: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("deny_join_request", { groupId, encryptedMemberId })),
	removeMember: (groupId: string, encryptedMemberId: string) => typedError<null, string>(__TAURI_INVOKE("remove_member", { groupId, encryptedMemberId })),
	leaveGroup: (groupId: string) => typedError<null, string>(__TAURI_INVOKE("leave_group", { groupId })),
	isGroupMember: (groupId: string) => typedError<boolean, string>(__TAURI_INVOKE("is_group_member", { groupId })),
	changeMemberRole: (groupId: string, encryptedMemberId: string, newRole: number) => typedError<null, string>(__TAURI_INVOKE("change_member_role", { groupId, encryptedMemberId, newRole })),
	setGroupExpiry: (groupId: string, expirySeconds: number) => typedError<null, string>(__TAURI_INVOKE("set_group_expiry", { groupId, expirySeconds })),
	setGroupTitle: (groupId: string, newTitle: string) => typedError<null, string>(__TAURI_INVOKE("set_group_title", { groupId, newTitle })),
	groupExpirySeconds: (groupId: string) => typedError<number, string>(__TAURI_INVOKE("group_expiry_seconds", { groupId })),
	applyPendingGroupChanges: (groupId: string) => typedError<number, string>(__TAURI_INVOKE("apply_pending_group_changes", { groupId })),
	listGroups: () => typedError<string[], string>(__TAURI_INVOKE("list_groups")),
	sendReaction: (target: MessageTarget, targetAuthor: string, targetSentAtMs: number, emoji: string, remove: boolean, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_reaction", { target, targetAuthor, targetSentAtMs, emoji, remove, sentAtMs })),
	sendEdit: (target: MessageTarget, targetSentAtMs: number, newBody: string, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_edit", { target, targetSentAtMs, newBody, sentAtMs })),
	sendDelete: (target: MessageTarget, targetAuthor: string, targetSentAtMs: number, forEveryone: boolean, sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_delete", { target, targetAuthor, targetSentAtMs, forEveryone, sentAtMs })),
	loadReactions: (conversationId: string) => typedError<ReactionFfi[], string>(__TAURI_INVOKE("load_reactions", { conversationId })),
	loadMessageRevisions: (conversationId: string, author: string, sentAtMs: number) => typedError<MessageRevisionFfi[], string>(__TAURI_INVOKE("load_message_revisions", { conversationId, author, sentAtMs })),
	/**
	 *  Drain decrypted messages from app-core's queue. The Desktop event loop polls
	 *  `next_events`; this lower-level call is plumbed for parity with iOS/Android.
	 */
	receiveMessages: () => typedError<DecryptedMessage[], string>(__TAURI_INVOKE("receive_messages")),
	/**
	 *  Recover an account from a BIP39 recovery phrase. Mirrors `recover_from_blob`
	 *  but derives the 32-byte recovery seed from the phrase first
	 *  (`recovery_phrase_to_seed` returns exactly 32 bytes, satisfying
	 *  `recover_from_blob`'s `len() == 32` check). The seed plays the role of
	 *  `prf_output` in the blob recovery path.
	 */
	recoverFromPhrase: (phrase: string, serverUrl: string, did: string, dbPath: string, dbKey: string, displayName: string) => typedError<AccountResult, string>(__TAURI_INVOKE("recover_from_phrase", { phrase, serverUrl, did, dbPath, dbKey, displayName })),
	sendReadReceipt: (recipientDid: string, timestamps: number[]) => typedError<null, string>(__TAURI_INVOKE("send_read_receipt", { recipientDid, timestamps })),
	joinViaLink: (masterKey: number[], hostingServerUrl: string, password: number[]) => typedError<JoinResultFfi, string>(__TAURI_INVOKE("join_via_link", { masterKey, hostingServerUrl, password })),
	acceptRequest: (did: string) => typedError<null, string>(__TAURI_INVOKE("accept_request", { did })),
	deleteRequest: (did: string) => typedError<null, string>(__TAURI_INVOKE("delete_request", { did })),
	setPendingRequest: (did: string, pending: boolean) => typedError<null, string>(__TAURI_INVOKE("set_pending_request", { did, pending })),
	reportAndBlock: (did: string, reason: string) => typedError<null, string>(__TAURI_INVOKE("report_and_block", { did, reason })),
	listBlocked: () => typedError<ContactRowFfi[], string>(__TAURI_INVOKE("list_blocked")),
	getConversationTimer: (conversationId: string) => typedError<number | null, string>(__TAURI_INVOKE("get_conversation_timer", { conversationId })),
	setConversationTimer: (recipientDid: string, expirySecs: number | null) => typedError<null, string>(__TAURI_INVOKE("set_conversation_timer", { recipientDid, expirySecs })),
	deleteExpiredMessages: () => typedError<string[], string>(__TAURI_INVOKE("delete_expired_messages")),
	/**
	 *  Encrypt and upload an attachment blob, returning the pointer to send. Async +
	 *  `spawn_blocking` because the upload does network I/O (mirrors `next_events`'s
	 *  off-thread pattern so the WebView never freezes).
	 */
	uploadAttachment: (plaintext: number[], contentType: string, fileName: string | null, width: number, height: number, durationMs: number, thumbnail: number[], flags: number) => typedError<AttachmentFfi, string>(__TAURI_INVOKE("upload_attachment", { plaintext, contentType, fileName, width, height, durationMs, thumbnail, flags })),
	/**
	 *  Download, verify, and decrypt an attachment blob; returns the plaintext bytes.
	 *  Caches the decrypted blob on disk and records the path via app-core's
	 *  `set_attachment_downloaded`, so re-opening a transcript (or restarting) reads
	 *  from disk instead of re-fetching + re-decrypting (mirrors iOS). Async +
	 *  `spawn_blocking` (network + filesystem I/O).
	 */
	downloadAttachment: (attachment: AttachmentFfi) => typedError<number[], string>(__TAURI_INVOKE("download_attachment", { attachment })),
	/**
	 *  Send a message carrying attachments and/or link previews to a DM or group.
	 *  One path for both targets (the `MessageTarget` fork lives in app-core). Async
	 *  + `spawn_blocking` (network I/O).
	 */
	sendMessageWithAttachments: (target: MessageTarget, body: string, attachments: AttachmentFfi[], previews: LinkPreviewFfi[], sentAtMs: number) => typedError<null, string>(__TAURI_INVOKE("send_message_with_attachments", { target, body, attachments, previews, sentAtMs })),
	/**
	 *  Open a validated http(s) URL in the OS default browser. The WebView must never
	 *  navigate to message URLs in-app (A2); link clicks and link-preview card taps
	 *  route here. Non-web schemes are rejected.
	 */
	openExternal: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_external", { url })),
	/**
	 *  Fetch a URL and scrape its OG/meta tags + og:image bytes (A4). Lives in Rust
	 *  because the WebView's CSP forbids external fetches (`connect-src ipc:`).
	 *  Size-capped, timed out, and http(s)-only. Returns a text-only card when no
	 *  image is found or the image fetch fails — never errors on a missing image.
	 */
	fetchLinkPreview: (url: string) => typedError<LinkPreviewMetaFfi, string>(__TAURI_INVOKE("fetch_link_preview", { url })),
	/**
	 *  New device: generate this device's pairing code (show mode). Creates the
	 *  handshake handle and stores it for the subsequent `device_link_await_step`.
	 */
	deviceLinkCreatePairing: (mailboxServer: string | null) => typedError<string, string>(__TAURI_INVOKE("device_link_create_pairing", { mailboxServer })),
	/**
	 *  New device: accept (paste) the existing device's pairing code (scan mode).
	 *  Stores the handshake handle for the subsequent `device_link_await_step`.
	 */
	deviceLinkAcceptPairing: (code: string) => typedError<null, string>(__TAURI_INVOKE("device_link_accept_pairing", { code })),
	/**
	 *  New device: one non-blocking step toward completing the link. Returns the
	 *  linked account (and installs it as the active account in `AppState`) once the
	 *  bundle has arrived; `None` while still waiting. Requires a prior
	 *  `device_link_create_pairing` / `device_link_accept_pairing`.
	 */
	deviceLinkAwaitStep: (dbPath: string, dbKey: string) => typedError<{
	did: string,
	displayName: string,
} | null, string>(__TAURI_INVOKE("device_link_await_step", { dbPath, dbKey })),
	/**  New device: abandon an in-progress pairing (cancel / view teardown). */
	deviceLinkReset: () => typedError<null, string>(__TAURI_INVOKE("device_link_reset")),
	/**
	 *  Existing device: generate this device's pairing code for a new device to
	 *  enter (show mode). Follow with `link_send_bundle_step` polling.
	 */
	linkCreatePairing: (mailboxServer: string | null) => typedError<string, string>(__TAURI_INVOKE("link_create_pairing", { mailboxServer })),
	/**
	 *  Existing device: accept (paste) the new device's pairing code (scan mode).
	 *  Follow with `link_send_bundle_step` polling.
	 */
	linkAcceptPairing: (code: string) => typedError<null, string>(__TAURI_INVOKE("link_accept_pairing", { code })),
	/**
	 *  Existing device: one non-blocking step of sealing + sending the provisioning
	 *  bundle. Returns true when done; the TS layer polls this.
	 */
	linkSendBundleStep: () => typedError<boolean, string>(__TAURI_INVOKE("link_send_bundle_step")),
};

/* Types */
/**
 *  Public metadata for an account: display name and bot flag.
 * 
 *  `display_name` is only populated for bot accounts. Human display names are
 *  exchanged via encrypted profile bundles (client-to-client), never stored on
 *  the server.
 */
export type AccountInfoFfi = {
	did: string,
	displayName: string | null,
	isBot: boolean,
};

export type AccountResult = {
	did: string,
	displayName: string,
};

/**
 *  An end-to-end-encrypted attachment (docs/35-attachments.md).
 * 
 *  One type spans the whole lifecycle: the pointer fields (`url`..`flags`)
 *  mirror the wire `AttachmentPointer`; `id`/`local_path`/`downloaded_at_ms`
 *  carry local state once the attachment is persisted/downloaded. A freshly
 *  uploaded pointer has an empty `id` and no local state.
 */
export type AttachmentFfi = {
	/**  Local row id; empty for a freshly-uploaded pointer not yet persisted. */
	id: string,
	/**  Full download URL on the hosting homeserver. */
	url: string,
	contentType: string,
	/**  64-byte attachment key (`aes ‖ hmac`). */
	key: number[],
	/**  32-byte SHA-256 of the stored ciphertext blob. */
	digest: number[],
	/**  Unpadded plaintext size in bytes. */
	sizeBytes: number,
	fileName: string | null,
	width: number,
	height: number,
	durationMs: number,
	blurhash: string | null,
	/**  Small decrypted preview (downscaled JPEG); empty if none. */
	thumbnail: number[],
	caption: string | null,
	/**  Bitset (VOICE_NOTE, GIF, ...). */
	flags: number,
	/**
	 *  Filesystem path of the decrypted full blob once downloaded; `None`
	 *  until the consumer downloads it and records the path via
	 *  `set_attachment_downloaded`.
	 */
	localPath: string | null,
	downloadedAtMs: number | null,
};

/**
 *  Liveness of the connection to the homeserver.
 * 
 *  Owned by the `AppCore` background reconnect task; observed by UI via
 *  `connection_state()` and `wait_for_connection_state_change()`.
 */
export type ConnectionState = 
/**  Initial state; reconnect task hasn't run yet. */
{ type: "disconnected" } | 
/**  An attempt is in flight (handshake / lazy auth). */
{ type: "connecting" } | 
/**  WebSocket is open. Steady state. */
{ type: "connected" } | 
/**  Last attempt failed; backing off until `next_attempt_at_ms`. */
{ type: "reconnecting"; next_attempt_at_ms: number };

/**
 *  Minimal contact-list row backing the compose autocomplete and the People
 *  list. `display_name` is the cached profile display name (empty if no
 *  profile has been fetched yet — callers fall back to the DID).
 */
export type ContactRowFfi = {
	did: string,
	displayName: string,
	isCurated: boolean,
	lastInteractionAtMs: number,
};

/**
 *  A conversation summary used to build the chat list on startup: one row
 *  per conversation, with the most recent message attached if any. A
 *  `None` `last_message` is a known conversation (e.g. a group you've been
 *  invited to) that hasn't seen any messages yet — the UI typically renders
 *  it with a placeholder preview.
 */
export type ConversationSummaryFfi = {
	conversationId: string,
	/**
	 *  For group conversations, the group's title resolved from
	 *  locally-persisted state. `None` for DMs, and for groups whose state
	 *  hasn't been fetched yet (e.g. a freshly received invite) — the chat
	 *  list falls back to a network fetch in that case.
	 */
	groupTitle: string | null,
	lastMessage: StoredMessageFfi | null,
	/**
	 *  MIME type of `last_message`'s first attachment (docs/35), or `None` when
	 *  it has none. The chat list renders a type-aware preview (an image type
	 *  previews as "Photo", anything else as "Attachment") for a caption-less
	 *  attachment whose `body` is empty; the blobs themselves are not loaded here.
	 */
	lastMessageAttachmentContentType: string | null,
	/**
	 *  True for a DM from an un-curated, un-blocked sender — an unaccepted
	 *  message request (docs/12 §1). The chat list shows a "Message request"
	 *  label and the conversation opens into the Accept/Delete/Report gate.
	 *  Always false for groups.
	 */
	isRequest: boolean,
	/**
	 *  True for a DM with a blocked contact (docs/12 §2). The chat list routes
	 *  these into a Blocked section. Always false for groups.
	 */
	isBlocked: boolean,
	/**
	 *  Number of unread inbound messages — the chat list's unread badge. Read
	 *  straight from the persisted store (`read_at IS NULL`, excluding our own
	 *  messages and expired rows), so it is correct for every conversation, not
	 *  just those whose messages are currently cached in the UI.
	 */
	unreadCount: number,
};

/**
 *  Result of `create_group`. `group_id` is URL-safe-no-pad base64;
 *  `master_key` is the 32-byte zkgroup master key (caller stashes for
 *  invite links).
 */
export type CreatedGroupFfi = {
	groupId: string,
	masterKey: number[],
};

/**  A decrypted inbound message. */
export type DecryptedMessage = {
	serverId: number,
	senderDid: string,
	senderDeviceId: number,
	plaintext: number[],
	/**  Sender's sent_at timestamp (from envelope). None for legacy messages. */
	sentAtMs: number | null,
	/**
	 *  URL-safe-no-pad base64 of the group_id when this message arrived as a
	 *  `proto::GroupMessage` body. `None` for plain DMs.
	 */
	groupId: string | null,
	/**
	 *  Disappearing-messages timer stamped on the envelope (docs/03 §5);
	 *  seconds, `0` = no expiry. The client persists it via `save_message`.
	 */
	expireTimerSecs: number,
	/**
	 *  The sender's profile key carried on the envelope, if any (any variant
	 *  may carry one). app-core no longer fetches/caches the sender's profile
	 *  automatically; a consumer that wants display names calls
	 *  `fetch_and_cache_profile(sender_did, profile_key)` with this. `None`
	 *  when the envelope carried no key.
	 */
	profileKey: number[] | null,
	/**
	 *  True when this is an inbound DM from a sender that does not auto-pass the
	 *  message-request gate (docs/12 §1) — i.e. the consumer should treat it as
	 *  a *message request* and, if it tracks requests, call
	 *  `set_pending_request(sender_did, true)`. Always `false` for group
	 *  deliveries and for senders that pass the gate (curated or known bot).
	 *  app-core no longer sets the pending-request flag itself; it only reports
	 *  the verdict so the consumer can decide whether to persist it.
	 */
	isRequest: boolean,
	/**
	 *  Attachment pointers carried on a text body (docs/35). Empty for messages
	 *  with no attachments. The consumer persists these via `save_message` and
	 *  fetches the blobs via `download_attachment`.
	 */
	attachments: AttachmentFfi[],
	/**
	 *  Link-preview cards (docs/35). Already anti-spoof-filtered: only previews
	 *  whose `url` occurs in the body are surfaced.
	 */
	previews: LinkPreviewFfi[],
};

/**  A delivery status update for an outgoing message (e.g. read receipt received). */
export type DeliveryStatusUpdate = {
	conversationId: string,
	sentAtMs: number,
	deliveryStatus: number,
};

/**
 *  Kind of a derived group timeline entry (docs/03 §3.6), reconstructed from a
 *  `GroupChange`'s actions plus the surrounding state snapshots. Keep this list
 *  **append-only** — the numeric `kind_code` is persisted in
 *  `message_history.kind`.
 */
export type GroupEventKind = 
/**  A pending invitee accepted (promoted themselves into the group). */
"memberJoined" | 
/**  Someone joined directly via an open invite link. */
"memberJoinedViaLink" | 
/**  Someone requested to join via a request-to-join link (awaits approval). */
"memberRequestedToJoin" | 
/**  An admin invited someone (they're now pending). */
"memberInvited" | 
/**  A member removed themselves. */
"memberLeft" | 
/**  An admin removed another member. */
"memberRemoved" | 
/**  An admin approved a pending join request. */
"joinRequestApproved" | 
/**  An admin denied a pending join request. */
"joinRequestDenied" | 
/**  An invitee declined an invitation. */
"inviteDeclined" | 
/**  A requester cancelled their own join request. */
"joinRequestCancelled" | 
/**  A member was promoted to admin. */
"roleChangedToAdmin" | 
/**  A member's admin role was removed. */
"roleChangedToMember" | 
/**  The group title changed. */
"titleChanged" | 
/**  The group description changed. */
"descriptionChanged" | 
/**  The disappearing-message timer changed. */
"expiryChanged" | 
/**  The group policy (join policy / announcement-only / link password) changed. */
"policyChanged";

/**  A member's row in a group, decrypted under the group key. */
export type GroupMemberFfi = {
	did: string,
	/**
	 *  URL-safe-no-pad base64 of the encrypted_member_id. Pass this verbatim
	 *  to admin actions (remove_member, change_member_role, …).
	 */
	encryptedMemberId: string,
	/**  0 = Member, 1 = Admin. */
	role: number,
	joinedAtMs: number,
};

/**
 *  One derived chat-timeline entry describing a membership/metadata change
 *  (docs/03 §3.6). Persisted as a system row in `message_history` and surfaced
 *  to the UI via `IncomingEvent::GroupMetadataChanged`.
 */
export type GroupMetadataEvent = {
	/**  URL-safe-no-pad base64 group_id this entry belongs to. */
	groupId: string,
	/**  Revision this change produced (the post-change revision). */
	revision: number,
	kind: GroupEventKind,
	/**
	 *  DID of the member who performed the change, from the sub-encrypted
	 *  `change_meta`. Empty when attribution was unavailable (pre-§3.6 change).
	 */
	actorDid: string,
	/**
	 *  DID of the member the change is about, when resolvable from the
	 *  surrounding state. Empty when the target's DID isn't known to us (e.g. a
	 *  still-pending invitee whose DID we never learned).
	 */
	targetDid: string,
	/**  base64 encrypted_member_id of the target, when the action names one. */
	targetEmi: string,
	/**
	 *  Best-effort millis the change occurred — pulled from a relevant state
	 *  timestamp (join/invite/request) where available, else fill time.
	 */
	occurredAtMs: number,
	/**
	 *  For `ExpiryChanged`, the new disappearing-message timer in seconds
	 *  (`0` = off). Lets the UI render "set disappearing messages to 4 weeks"
	 *  without a separate state lookup. `0` for all other kinds.
	 */
	expirySeconds: number,
	/**
	 *  For `TitleChanged`, the new group name, so the UI can render
	 *  "changed the group name to 'X'". Empty for all other kinds.
	 */
	newTitle: string,
	/**
	 *  Pre-rendered English one-liner (using DIDs, not display names) for
	 *  headless consumers / logging. UIs should render from the structured
	 *  fields instead, resolving DIDs to display names.
	 */
	summary: string,
};

/**
 *  A pending invite or approval entry. `timestamp_ms` carries either
 *  `invited_at_ms` (for invites) or `requested_at_ms` (for approvals).
 */
export type GroupPendingFfi = {
	encryptedMemberId: string,
	timestampMs: number,
};

/**  Snapshot of a group's decrypted state. */
export type GroupSummaryFfi = {
	groupId: string,
	masterKey: number[],
	revision: number,
	title: string,
	description: string,
	expirySeconds: number,
	members: GroupMemberFfi[],
	pendingInvites: GroupPendingFfi[],
	pendingApprovals: GroupPendingFfi[],
};

/**
 *  A single event surfaced to the FFI from the background reconnect task.
 *  Drained in batches by `next_events()`.
 */
export type IncomingEvent = 
/**  A decrypted content message. */
{ type: "message"; msg: DecryptedMessage } | 
/**  A delivery status update from a read receipt. */
{ type: "receiptUpdate"; update: DeliveryStatusUpdate } | 
/**
 *  Received a `GroupContext` DM — we've been invited to a group. The
 *  master key has already been persisted; the UI should refresh its
 *  conversation list so the group appears.
 */
{ type: "groupInvite"; group_id: string; hosting_server_url: string; inviter_did: string } | 
/**
 *  A prior message was edited in place (docs/36). The store has already
 *  been updated; the UI should refresh the message's body / "Edited" mark.
 */
{ type: "messageEdited"; conversation_id: string; author_did: string; sent_at_ms: number; new_body: string; edited_at_ms: number } | 
/**
 *  A prior message was deleted FOR_EVERYONE (docs/36). The store now holds
 *  a tombstone; the UI should render the deleted placeholder.
 */
{ type: "messageDeleted"; conversation_id: string; author_did: string; sent_at_ms: number } | 
/**
 *  A reaction was added/changed (`removed = false`) or cleared
 *  (`removed = true`) on a target message (docs/33). The store reflects it;
 *  the UI should refresh the target's reaction cluster.
 */
{ type: "reactionUpdated"; conversation_id: string; target_author: string; target_sent_at_ms: number; reactor_did: string; emoji: string; removed: boolean } | 
/**
 *  A background storage sync pulled and applied remote durable-state
 *  records (e.g. a group master key synced from another device, or an
 *  updated contact/profile). The domain tables are already updated; the UI
 *  should rebuild its conversation list so newly-synced groups/contacts
 *  appear without an app restart. Same "refresh the list" contract as
 *  `GroupInvite`, but driven by the storage service rather than a DM.
 */
{ type: "storageSynced" } | 
/**
 *  A group membership/metadata change was derived from the change log
 *  (docs/03 §3.6) while applying pending changes — e.g. "Alice added Bob",
 *  "Bob left", "Carol was made an admin". The store already holds the
 *  matching system row in `message_history`; the UI should refresh the
 *  conversation timeline. Emitted once per derived entry.
 */
{ type: "groupMetadataChanged"; event: GroupMetadataEvent } | 
/**
 *  The disappearing-messages reaper hard-deleted one or more messages whose
 *  timer elapsed (docs/03 §5). The store no longer holds them; the UI should
 *  refresh the listed conversations (timeline + chat-list preview).
 */
{ type: "messagesExpired"; conversation_ids: string[] } | 
/**
 *  A single conversation's stored content changed locally and the UI should
 *  re-read just that conversation (its open timeline + chat-list preview).
 *  Emitted when a `SyncSent`/`SyncRead` transcript from another of my own
 *  devices (docs/04 §5.4) is applied over the live WS path — a message I
 *  sent, an edit/delete/reaction I made, or read-state I cleared elsewhere.
 *  Unlike `StorageSynced` this names the affected conversation, so the UI
 *  refreshes one timeline instead of rebuilding everything.
 */
{ type: "conversationUpdated"; conversation_id: string };

/**  Decoded invite token info returned to the mobile layer. */
export type InviteInfo = {
	serverUrl: string,
	serverName: string,
	inviterDid: string | null,
	postOnboardingRedirect: string | null,
	/**
	 *  Inviter's plaintext display name from the token. Shown on the invite
	 *  acceptance screen before any server communication. The encrypted
	 *  profile blob is the source of truth once fetched.
	 */
	inviterDisplayName: string | null,
	/**
	 *  Inviter's 32-byte profile key from the token, base64url-encoded.
	 *  The new client primes its contact_profiles cache with this so the
	 *  auto-DM can show the inviter's name from the very first frame.
	 */
	inviterProfileKey: number[] | null,
	/**
	 *  Operator's privacy policy URL for `server_url`, resolved server-side as
	 *  part of invite validation (same source as `GET /v1/info`). `None` when
	 *  the operator configured none. Onboarding screens read this directly
	 *  instead of making a separate server call.
	 */
	privacyPolicyUrl: string | null,
};

/**  Outcome of `join_via_link`. */
export type JoinResultFfi = 
/**  Admitted directly into `member_credentials` (OpenLink policy). */
{ type: "member" } | 
/**
 *  Placed in `members_pending_approval` (RequestToJoin policy);
 *  admins must approve before the requester can act.
 */
{ type: "pending" };

/**
 *  A rich link-preview card (docs/35). The sender generates it at compose time;
 *  `image` (the og:image) is a normal [`AttachmentFfi`] so it rides the E2E
 *  attachment path and the client downloads it like any other blob. `None`
 *  image means a text-only card.
 */
export type LinkPreviewFfi = {
	/**  The previewed URL — must occur in the message body (anti-spoof). */
	url: string,
	title: string,
	description: string,
	/**  Article published date, unix millis; 0 = unknown. */
	dateMs: number,
	image: AttachmentFfi | null,
};

/**
 *  Raw OG/meta scrape for a URL (A4). Desktop-specific (not in app-core) — the
 *  frontend turns the og:image bytes into an encrypted `AttachmentFfi` via
 *  `upload_attachment`, then assembles a `LinkPreviewFfi` for the send path
 *  (mirrors iOS `AppState.fetchLinkPreview`). `image_bytes` is empty for a
 *  text-only card.
 */
export type LinkPreviewMetaFfi = {
	url: string,
	title: string,
	description: string,
	dateMs: number,
	imageBytes: number[],
	imageContentType: string | null,
};

/**  A prior body of an edited message, for the edit-history sheet. */
export type MessageRevisionFfi = {
	body: string,
	replacedAtMs: number,
};

/**
 *  Where a content operation (reaction / edit / delete) is directed: a DM with
 *  a peer, or a group. Reaction/edit/delete share one API surface across both;
 *  only the conversation key and the transport differ, and that fork lives in
 *  `AppCoreInner::send_to_target`. (Plain-text sends keep their own
 *  `send_dm` / `send_group_message` entry points.)
 */
export type MessageTarget = { type: "dm"; recipient_did: string } | { type: "group"; group_id: string };

/**  A Project available on the homeserver. */
export type ProjectInfoFfi = {
	name: string,
	url: string,
	description: string,
};

/**
 *  A reaction on a message (docs/33-reactions.md), keyed by the target's wire
 *  identity `(target_author, target_sent_at_ms)`. The UI clusters these by
 *  target and by emoji.
 */
export type ReactionFfi = {
	conversationId: string,
	targetAuthor: string,
	targetSentAtMs: number,
	reactorDid: string,
	emoji: string,
	reactedAtMs: number,
};

/**  A message from local history (persisted in SQLCipher). */
export type StoredMessageFfi = {
	id: string,
	conversationId: string,
	senderDid: string,
	body: string,
	sentAtMs: number,
	editedAtMs: number | null,
	/**  NULL = unread, Some = unix millis when marked read. */
	readAtMs: number | null,
	/**  0 = sending, 1 = sent, 2 = delivered, 3 = read. */
	deliveryStatus: number,
	/**  Number of times edited; drives the "Edited" affordance and the human cap. */
	editCount: number,
	/**  True = FOR_EVERYONE tombstone (render "This message was deleted"). */
	deleted: boolean,
	/**
	 *  0 = normal chat bubble; >0 = a system/metadata timeline entry
	 *  (docs/03 §3.6 group event). Render kind>0 as a centered grey line.
	 *  The numeric values match `GroupEventKind` order; `metadata` carries the
	 *  structured actor/target for localization.
	 */
	kind: number,
	/**
	 *  JSON for system rows (`{ "event": <kind>, "actor_did": .., "target_did": ..,
	 *  "target_emi": .. }`); `None` for normal chat messages.
	 */
	metadata: string | null,
	/**  Disappearing-messages timer in seconds (docs/03 §5); `0` = no expiry. */
	expireTimerSecs: number,
	/**
	 *  Unix-millis deletion deadline once the countdown has started (on read),
	 *  or `None`. The UI schedules the live disappear from this.
	 */
	expireAtMs: number | null,
	/**
	 *  Attachments on this message (docs/35), ordered. Empty for plain text.
	 *  Populated by `load_messages`; persisted by `save_message`.
	 */
	attachments: AttachmentFfi[],
	/**
	 *  Link-preview cards on this message (docs/35), ordered. Populated by
	 *  `load_messages`; persisted by `save_message`.
	 */
	previews: LinkPreviewFfi[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

